### ISSUE TITLE
批量mysql-mysql任务，采用perjob模式执行任务，yarn上任务一直想完成，但是flinkx任务仍然还在运行

### ISSUE THREAD

**Issue by biandou1313** [DTStack/chunjun#1023]
现象：
![1657007530(1)](https://user-images.githubusercontent.com/34857750/177278035-8a11549b-1336-4a0f-939f-4515139f80ca.png)
![1657007576(1)](https://user-images.githubusercontent.com/34857750/177278163-720f8147-7836-4a64-8144-97fb5140a644.png)
![1657007598(1)](https://user-images.githubusercontent.com/34857750/177278252-490c6bb3-6e73-4db6-9394-d092dd2b3e75.png)
日志：
hadoop上：
![1657007836(1)](https://user-images.githubusercontent.com/34857750/177278974-ffa2211c-176e-4743-ac69-823ede4cfab3.png)

**Comment by biandou1313** [comment]
这种情况：
![1657014355(1)](https://user-images.githubusercontent.com/34857750/177300649-e2640c73-1b15-4b2c-9943-b04e7ae5be2a.png)

**Comment by biandou1313** [comment]
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IllegalArgumentException: WritingRecordError: error writing record [2] exceed limit [0]
+I(18,xulei,22,rwerw)
com.dtstack.flinkx.throwable.WriteRecordException: 
JdbcOutputFormat [424855509674229824] writeRecord error: when converting field[0] in Row(+I(18,xulei,22,rwerw))
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '18' for key 'PRIMARY'
  at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.processWriteException(JdbcOutputFormat.java:342)
  at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:181)
  at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:465)
  at java.util.ArrayList.forEach(ArrayList.java:1259)
  at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:485)
  at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.getFormatState(BaseRichOutputFormat.java:576)
  at com.dtstack.flinkx.sink.DtOutputFormatSinkFunction.snapshotState(DtOutputFormatSinkFunction.java:147)
  at org.apache.flink.streaming.util.functions.StreamingFunctionUtils.trySnapshotFunctionState(StreamingFunctionUtils.java:118)
  at org.apache.flink.streaming.util.functions.StreamingFunctionUtils.snapshotFunctionState(StreamingFunctionUtils.java:99)
  at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.snapshotState(AbstractUdfStreamOperator.java:89)
  at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:205)
  at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:162)
  at org.apache.flink.streaming.api.operators.AbstractStreamOperator.snapshotState(AbstractStreamOperator.java:371)
  at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointStreamOperator(SubtaskCheckpointCoordinatorImpl.java:686)
  at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.buildOperatorSnapshotFutures(SubtaskCheckpointCoordinatorImpl.java:607)
  at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.takeSnapshotSync(SubtaskCheckpointCoordinatorImpl.java:572)
  at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:298)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$9(StreamTask.java:1004)
  at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:988)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpoint(StreamTask.java:912)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$triggerCheckpointAsync$8(StreamTask.java:885)
  at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
  at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90)
  at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:317)
  at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:189)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:617)
  at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:581)
  at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:755)
  at org.apache.flink.runtime.taskmanager.Task.run(Task.java:570)
  at java.lang.Thread.run(Thread.java:748)

**Comment by PaddyMelody** [comment]
1. Problems caused by primary key Duplicate
2. The jobName on YARN is the same, but the applicationId is different，So they are different for several tasks
