### ISSUE TITLE
emqx与redis联合查询 插入数据到mysql里面，报错ava.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1050]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### **背景**
1、flink是1.12.7
2、chunjun是1.12.7  
3、除此之外没有其他的平台了
4、我做了一个小的demo，然后写数据到redis集群里面，然后也成功了！
5、说明我搭建的背景环境应该是没有问题的。
###  **问题代码**
-- 源表
CREATE TABLE source1
(id int,
head_code varchar,
PROCTIME AS PROCTIME()
)WITH(
'connector'='emqx-x'
,'broker'='tcp://IP:1883'
,'topic'='amq/topic'
,'isCleanSession'='true'
,'qos'='0'
,'username'='OPC_102'
,'password'='Opc_2020'
,'format'='json'
);

-- 维表
CREATE TABLE side1 (
    id INT,
    name STRING,
    cww float -- , primary key (id,name) NOT ENFORCED -- 这里的pk，并不会作为查询redis的主键，所以作为维表可不写。是通过select中的join条件作为主键
) WITH (
    'connector' = 'redis-x' --必填
,
    'url' = 'IP:6379' --必填，格式ip:port[,ip:port]
,
    'table-name' = 'demo' --必填
,
    'password' = '****2' -- 密码 无默认，非必填项
,
    'redis-type' = '3' -- redis模式（1 单机，2 哨兵， 3 集群），默认：1
    --   ,'master-name' = 'lala' -- 主节点名称（哨兵模式下为必填项）
,
    'database' = '1' -- redis 的数据库地址，默认：0
,
    'timeout' = '10000' -- 连接超时时间，默认：10000毫秒
,
    'max.total' = '3' -- 最大连接数 ，默认：8
,
    'max.idle' = '3' -- 最大空闲连接数，默认：8
,
    'min.idle' = '0' -- 最小空闲连接数 ，默认：0
,
    'sink.parallelism' = '1' -- sink并行度
,
    'lookup.cache-type' = 'LRU' -- 维表缓存类型(NONE、LRU、ALL)，默认LRU
,
    'lookup.cache-period' = '4600000' -- ALL维表每隔多久加载一次数据，默认3600000毫秒
,
    'lookup.cache.max-rows' = '20000' -- lru维表缓存数据的条数，默认10000条
,
    'lookup.cache.ttl' = '700000' -- lru维表缓存数据的时间，默认60000毫秒
,
    'lookup.fetch-size' = '2000' -- ALL维表每次从数据库加载的条数，默认1000条
,
    'lookup.async-timeout' = '30000' -- lru维表缓访问超时时间，默认10000毫秒，暂时没用到
,
    'lookup.parallelism' = '1' -- 维表并行度，默认nul
,
    'type' = 'hash',
    'mode' = 'hset'
);

-- 结果表
CREATE TABLE sink1 (
    id int,
    head_code varchar,
    cww float,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'mysql-x',
    'url' = 'jdbc:mysql://IP:3306/dlink',
    'table-name' = 'product',
    'username' = 'root',
    'password' = '123456'
);

-- 多源头混合计算
INSERT INTO
    sink1
SELECT
    u.id,
    u.head_code,
    s.cww as cww
from
    source1 u
    left join side1 FOR SYSTEM_TIME AS OF u.PROCTIME AS s on u.head_code = s.name
    and u.id = s.id;
### **报错信息**

Caused by: java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.initCache(PreparedStmtProxy.java:206)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.<init>(PreparedStmtProxy.java:110)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.buildStmtProxy(JdbcOutputFormat.java:131)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.openInternal(JdbcOutputFormat.java:106)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.open(BaseRichOutputFormat.java:249)
	at com.dtstack.chunjun.sink.DtOutputFormatSinkFunction.open(DtOutputFormatSinkFunction.java:95)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.open(SinkOperator.java:63)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:433)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:545)
	at org.apache.flink.streaming.runtime.tasks.StreamTask$$Lambda$219/453384107.run(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:535)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:575)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:758)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:573)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.NullPointerException
		at org.apache.flink.table.runtime.operators.join.lookup.AsyncLookupJoinRunner.close(AsyncLookupJoinRunner.java:158)
		at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:41)
		at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:797)
		at org.apache.flink.streaming.runtime.tasks.StreamTask$$Lambda$298/1889373309.run(Unknown Source)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.runAndSuppressThrowable(StreamTask.java:776)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:691)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:595)
		... 3 more
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
### **数据库信息**
![1](https://user-images.githubusercontent.com/49744386/178926301-d06e1457-92b1-4a5e-a6d4-66fad5acadc7.png)

### **redis集群里面的数据****

![image](https://user-images.githubusercontent.com/49744386/178926460-2a4731cc-e8c9-4a64-9c37-46ab4b4fd3ee.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15656215623** [comment]
补充一下，我的emqx接受的数据是啥样的
![image](https://user-images.githubusercontent.com/49744386/178927365-3768655d-a01f-4397-b763-465762d3f21c.png)

**Comment by 15656215623** [comment]
问题已经解决了
缺少这个包 可以在chunjun源代码的依赖里面找到
![image](https://user-images.githubusercontent.com/49744386/178933420-85e9e627-807a-4b39-83b8-dd43dda96b83.png)
把这个放到flink的Lib下面
![image](https://user-images.githubusercontent.com/49744386/178933620-1ac23b72-6758-4282-90fe-0ae0ffec794b.png)
