### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to oracle.sql.CLOB

### ISSUE THREAD

**Issue by 20100507** [DTStack/chunjun#1068]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

```
2022-07-18 10:56:59.341 [Legacy Source Thread - Source: TableSourceScan(table=[[default_catalog, default_database, products]], fields=[ID, NAME, DESCRIPTION]) -> Calc(select=[CAST(ID) AS ID, NAME, DESCRIPTION]) -> SinkConversionToTuple2 -> Sink: SQL Client Stream Collect Sink (1/1)#0] INFO  c.dtstack.chunjun.connector.oracle.source.OracleInputFormat  - [OracleInputFormat] open successfully, 
inputSplit = JdbcInputSplit{mod=0, endLocation='null', startLocation='null', startLocationOfSplit='null', endLocationOfSplit='null'}, 
[JdbcConf]: 
{
  "semantic" : "at-least-once",
  "errorRecord" : 0,
  "checkFormat" : true,
  "parallelism" : 1,
  "executeDdlAble" : false,
  "pollingInterval" : 5000,
  "increment" : false,
  "flushIntervalMills" : 10000,
  "polling" : false,
  "querySql" : "SELECT \"ID\", \"NAME\", \"DESCRIPTION\" FROM \"PRODUCTS\" WHERE  1=1 ",
  "mode" : "INSERT",
  "password" : "******",
  "restoreColumnIndex" : -1,
  "connection" : [ {
    "table" : [ "PRODUCTS" ],
    "jdbcUrl" : [ "jdbc:oracle:thin:@172.24.1.135:1521:XE" ]
  } ],
  "table" : "PRODUCTS",
  "queryTimeOut" : 10,
  "fetchSize" : 2,
  "useMaxFunc" : false,
  "column" : [ {
    "name" : "ID",
    "type" : "DECIMAL(9, 0) NOT NULL",
    "index" : 0,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "NAME",
    "type" : "STRING",
    "index" : 1,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "DESCRIPTION",
    "type" : "STRING",
    "index" : 2,
    "notNull" : false,
    "part" : false
  } ],
  "errorPercentage" : -1,
  "fieldNameList" : [ ],
  "withNoLock" : false,
  "increColumnIndex" : -1,
  "allReplace" : false,
  "splitStrategy" : "range",
  "initReporter" : false,
  "jdbcUrl" : "jdbc:oracle:thin:@172.24.1.135:1521:XE",
  "connectTimeOut" : 0,
  "batchSize" : 1,
  "speedBytes" : 0,
  "rowSizeCalculatorType" : "objectSizeCalculator",
  "metricPluginName" : "prometheus",
  "username" : "flinkuser"
} 
2022-07-18 10:56:59.342 [Legacy Source Thread - Source: TableSourceScan(table=[[default_catalog, default_database, products]], fields=[ID, NAME, DESCRIPTION]) -> Calc(select=[CAST(ID) AS ID, NAME, DESCRIPTION]) -> SinkConversionToTuple2 -> Sink: SQL Client Stream Collect Sink (1/1)#0] ERROR c.d.chunjun.connector.oracle.converter.OracleRowConverter  - value [scooter] convent failed 
2022-07-18 10:56:59.392 [Legacy Source Thread - Source: TableSourceScan(table=[[default_catalog, default_database, products]], fields=[ID, NAME, DESCRIPTION]) -> Calc(select=[CAST(ID) AS ID, NAME, DESCRIPTION]) -> SinkConversionToTuple2 -> Sink: SQL Client Stream Collect Sink (1/1)#0] ERROR com.dtstack.chunjun.source.DtInputFormatSourceFunction  - Exception happened, start to close format
com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105)
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79)
	at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:140)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:199)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:241)
2022-07-18 10:56:59.392 [dirty-consumer-pool-1-thread-1] WARN  com.dtstack.chunjun.dirty.log.LogDirtyDataCollector  - 
====================Dirty Data=====================
DirtyDataEntry[jobId='60884e17f589b6f20c1a554f531f9172', jobName='default: select * from products', operatorName='Source: TableSourceScan(table=[[default_catalog, default_database, products]], f', dirtyContent='{"arity":3,"nullBitsSizeInBytes":8,"offset":0,"sizeInBytes":0}', errorMessage='com.dtstack.chunjun.throwable.ReadRecordException: 
java.lang.ClassCastException: java.lang.String cannot be cast to oracle.sql.CLOB
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:274)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:197)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:241)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to oracle.sql.CLOB
	at com.dtstack.chunjun.connector.oracle.converter.OracleRowConverter.lambda$createInternalConverter$cdd9fd22$11(OracleRowConverter.java:165)
	at com.dtstack.chunjun.converter.AbstractRowConverter.lambda$wrapIntoNullableInternalConverter$66e1293c$1(AbstractRowConverter.java:97)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcRowConverter.toInternal(JdbcRowConverter.java:94)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcRowConverter.toInternal(JdbcRowConverter.java:51)
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:252)
	... 6 more
', fieldName='null', createTime=2022-07-18 10:56:59.344]
```

### What you expected to happen

java.lang.ClassCastException: java.lang.String cannot be cast to oracle.sql.CLOB

### How to reproduce

java.lang.ClassCastException: java.lang.String cannot be cast to oracle.sql.CLOB

### Anything else

java.lang.ClassCastException: java.lang.String cannot be cast to oracle.sql.CLOB

### Version

1.12_release

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 20100507** [comment]
Oracle JDBC 创建映射表，varchar 类型，varchar 类型的数据量超过了代码中限定的值，代码中做了强制类型转换导致了类类型转换异常。

`            case CHAR:
                if (((CharType) type).getLength() > CLOB_LENGTH) {
                    // return val -> {
                    // oracle.sql.CLOB clob = (oracle.sql.CLOB) val;
                    // java.sql.Clob clob = (java.sql.Clob) val;
                    // return StringData.fromString(ConvertUtil.convertClob(clob));
                    //     val -> StringData.fromString(val.toString());
                    // };
                    return val -> StringData.fromString(val.toString());
                }
                return val -> StringData.fromString(val.toString());
            case VARCHAR:
                if (((VarCharType) type).getLength() > CLOB_LENGTH) {
                    // return val -> {
                    // oracle.sql.CLOB clob = (oracle.sql.CLOB) val;
                    // java.sql.Clob clob = (java.sql.Clob) val;
                    // return StringData.fromString(ConvertUtil.convertClob(clob));
                    //   return StringData.fromString(val.toString());
                    // };
                    return val -> StringData.fromString(val.toString());
                }`

**Comment by FlechazoW** [comment]
Ok, this is a bug.

**Comment by yanghuaiGit** [comment]
不需要注释代码 只需要在sql里varchar类型加上长度即可 varchar(255)

**Comment by FlechazoW** [comment]
This issue has been around for too long, so close it and reopen one if necessary.
