### ISSUE TITLE
mysql操作频繁情况下，报错java.sql.SQLException: No operations allowed after statement closed.

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

我的应用场景
   emqx与redis进行联合查询，然后把处理的数据更新到mysql；

一开始对数据库更新都没有问题，但是运行不到10分钟就会报错
![image](https://user-images.githubusercontent.com/49744386/181695573-b62f22de-e8d3-46ba-8caf-0a06fd161554.png)
报错信息如下
2022-07-29 14:18:59
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:118)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:80)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:233)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:224)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:215)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:666)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:89)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:446)
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor$$Lambda$104/964061023.apply(Unknown Source)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Connection maybe closed
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.processWriteException(JdbcOutputFormat.java:353)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:197)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:466)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:487)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat$$Lambda$1349/844692465.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:487)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat$$Lambda$1264/107466768.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No operations allowed after statement closed.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442)
	at com.mysql.jdbc.ServerPreparedStatement.checkClosed(ServerPreparedStatement.java:510)
	at com.mysql.jdbc.ServerPreparedStatement.setString(ServerPreparedStatement.java:1971)
	at com.dtstack.chunjun.connector.jdbc.statement.FieldNamedPreparedStatementImpl.setString(FieldNamedPreparedStatementImpl.java:207)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcRowConverter.lambda$createExternalConverter$a54efc5$8(JdbcRowConverter.java:201)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcRowConverter$$Lambda$1256/685383841.serialize(Unknown Source)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcRowConverter.lambda$wrapIntoNullableExternalConverter$10addbde$1(JdbcRowConverter.java:84)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcRowConverter$$Lambda$1257/697556710.serialize(Unknown Source)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcRowConverter.toExternal(JdbcRowConverter.java:113)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcRowConverter.toExternal(JdbcRowConverter.java:51)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.writeSingleRecordInternal(PreparedStmtProxy.java:200)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:194)
	... 14 more

百度的结果都说，这里和数据库的连接Connection是一个[Static]所以第一次对数据库操作没问题，当把Connection关闭后，第二次还想操作数据库时Connection肯定不存在了。
希望能完善这部分代码！

![image](https://user-images.githubusercontent.com/49744386/181695791-dfddaa61-5fba-4ba4-a96a-135a0a5932a4.png)

谢谢！！

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15656215623** [comment]
-- 源表 
CREATE TABLE source1 (
    Name varchar,
    --机头号
    Fields ROW<SSXR float,VSXCD float>,
    -- 线速度
    PROCTIME AS PROCTIME()
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://ip:1883',
    'topic' = 'amq/topic/#',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'OPC_102',
    'password' = 'Opc_2020',
    'format' = 'json'
);




-- 维表
CREATE TABLE side1 (
    id varchar,
    -- 102
    name varchar,
    -- key
    Spec varchar, 
    --规格
    InR varchar,
    --内径
    OutR varchar,
    --外径
    cww varchar,
    -- 重量
    length varchar,
    -- 长度
    F_Id varchar,
    --数据库id
    primary key (id,name) NOT ENFORCED 
    -- 这里的pk，并不会作为查询redis的主键，所以作为维表可不写。是通过select中的join条件作为主键
) WITH (
    'connector' = 'redis-x' --必填
,
    'url' = 'ip:6379' --必填，格式ip:port[,ip:port]
,
    'table-name' = 'gdjd' --必填
,
    'password' = 'Ahjuxin_2022' -- 密码 无默认，非必填项
,
    'redis-type' = '3' -- redis模式（1 单机，2 哨兵， 3 集群），默认：1
    --   ,'master-name' = 'lala' -- 主节点名称（哨兵模式下为必填项）
,
    'database' = '0' -- redis 的数据库地址，默认：0
,
    'timeout' = '10000' -- 连接超时时间，默认：10000毫秒
,
    'max.total' = '3' -- 最大连接数 ，默认：8
,
    'max.idle' = '3' -- 最大空闲连接数，默认：8
,
    'min.idle' = '0' -- 最小空闲连接数 ，默认：0
,
    'sink.parallelism' = '1' -- sink并行度
,
    'lookup.cache-type' = 'LRU' -- 维表缓存类型(NONE、LRU、ALL)，默认LRU
,
    'lookup.cache-period' = '120000' -- ALL维表每隔多久加载一次数据，默认3600000毫秒
,
    'lookup.cache.max-rows' = '20000' -- lru维表缓存数据的条数，默认10000条
,
    'lookup.cache.ttl' = '700000' -- lru维表缓存数据的时间，默认60000毫秒
,
    'lookup.fetch-size' = '2000' -- ALL维表每次从数据库加载的条数，默认1000条
,
    'lookup.async-timeout' = '30000' -- lru维表缓访问超时时间，默认10000毫秒，暂时没用到
,
    'lookup.parallelism' = '1' -- 维表并行度，默认nul
,
    'type' = 'hash',
    'mode' = 'hset'
);

-- 结果表
CREATE TABLE sink1 (
    F_Id varchar,
    head_code varchar,
    weight DECIMAL,
    meter DECIMAL,
    PRIMARY KEY (F_Id) NOT ENFORCED
) WITH (
    'connector' = 'mysql-x',
    'url' = 'jdbc:mysql://10.20.1.150:3306/jx_mes',
    'table-name' = 'jx_mes_product_online',
    'username' = 'root',
    'password' = 'Ahjuxin_2022'
);


--  多源头混合计算
INSERT INTO
    sink1
SELECT
    s.F_Id as F_Id,   -- F_Id
    s.name as head_code,      --机头号
    e.Fields.VSXCD as meter,   -- 长度
    --- CAST(s.Spec AS float) as weight  
   ((3.1415926*(CAST(s.Spec AS float)/2-0.002)*(CAST(s.Spec AS float)/2-0.002)*0.00889*e.Fields.VSXCD)*1.035)  as weight  
    --(3.1415926 * (CAST(s.Spec AS DECIMAL(4, 3))/ 2 - 0.002) * (CAST(s.Spec AS DECIMAL(4, 3)) / 2 - 0.002) * 0.00889) * 1.035  as weight  
     ---  重量
 from
    source1 e
    left join side1 FOR SYSTEM_TIME AS OF e.PROCTIME AS s on SUBSTRING(e.Name,7,4) = s.name and s.id='102';

**Comment by 15656215623** [comment]
我的redis 参数如下
![image](https://user-images.githubusercontent.com/49744386/181697521-22dae94f-38cc-40ad-a268-ab8e7eb6ad19.png)

**Comment by 15656215623** [comment]
我的emqx数据如下
{
  "Name": "MQB086NO04",
  "Tags": {
    "GroupName": "MQB086NO04"
  },
  "Fields": {
    "_Error": 0,
    "VXGS": 0.75,
    "VSXCD": 62596.31,
    "VDV": 0,
    "SSXR": 0,
    "SSXS": 50,
    "TTHR": 34.4,
    "SPFFJR": 0,
    "SPFFJS": 1000,
    "TGHR": 36.9,
    "SXHFJR": 0,
    "SXHFJS": 4000,
    "TLTJKR": 43.8,
    "TTHS": 460,
    "TGHS": 640,
    "PBL": 0
  },
  "Timestamp": "2022-07-29T06:27:26.6120904Z"
}
