### ISSUE TITLE
对mysql数据操作，运行大概2h以后，会报错 Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1117]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

对mysql数据库采取更新操作，1h没有问题；
但是运行到2h的时候，虽然任务还在，没有提示失败，但是失去了更新的功能；
flink日志错误信息如下
java.sql.BatchUpdateException: Deadlock found when trying to get lock; try restarting transaction
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.StatementImpl.handleExceptionForBatch(StatementImpl.java:1290) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1550) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1253) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[chunjun-connector-mysql.jar:?]
	at com.dtstack.chunjun.connector.jdbc.statement.FieldNamedPreparedStatementImpl.executeBatch(FieldNamedPreparedStatementImpl.java:131) ~[chunjun-connector-mysql.jar:?]
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.executeBatch(PreparedStmtProxy.java:251) ~[chunjun-connector-mysql.jar:?]
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeMultipleRecordsInternal(JdbcOutputFormat.java:222) [chunjun-connector-mysql.jar:?]
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:483) [blob_p-5affc38e48744344fc68a3adb3c5f6ac68e9244a-762bdcc44e6d594d5a4804c97bfc0f59:?]
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443) [blob_p-5affc38e48744344fc68a3adb3c5f6ac68e9244a-762bdcc44e6d594d5a4804c97bfc0f59:?]
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat$$Lambda$281/1770691363.run(Unknown Source) [blob_p-5affc38e48744344fc68a3adb3c5f6ac68e9244a-762bdcc44e6d594d5a4804c97bfc0f59:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:952) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104) ~[chunjun-connector-mysql.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1548) ~[chunjun-connector-mysql.jar:?]
	... 15 more
2022-08-02 07:00:05,976 WARN  com.dtstack.chunjun.connector.emqx.source.EmqxInputFormat    [] - connection lost and reconnect , e = Connection lost
2022-08-02 07:00:05,980 INFO  com.dtstack.chunjun.connector.emqx.util.MqttConnectUtil      [] - connect 1 times.
2022-08-02 07:00:06,305 INFO  com.dtstack.chunjun.connector.emqx.util.MqttConnectUtil      [] - emqx is connected = true 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
你可以根据这篇文章排查下死锁的具体原因

https://cloud.tencent.com/developer/article/1722416

**Comment by FlechazoW** [comment]
This issue has been around for too long, so close it and reopen one if necessary
