### ISSUE TITLE
[Bug] [PostgreSQL Source]  

### ISSUE THREAD

**Issue by baisui1981** [DTStack/chunjun#1123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

when process PostgreSQL Source as Flink Stream source,throws a exception as below, when review the code https://github.com/qlangtech/chunjun/blob/2251bcf9f70a3be38f228b1f52dfe8ae8aee9f2b/chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/source/PostgresqlInputFormat.java#L55-L62

the reason is that the same where cause `WHERE "id" > ? ORDER BY "id" ASC ` has been duplicated appended twice

``` shell
2022-08-08 14:40:06
com.dtstack.chunjun.throwable.ChunJunRuntimeException: error to execute sql = SELECT "id", "bytea_c", "small_c", "int_c", "big_c", "real_c", "double_precision", "numeric_c", "decimal_c", "boolean_c", "text_c", "char_c", "character_c", "character_varying_c", "timestamp3_c", "timestamp6_c", "date_c", "time_c", "default_numeric_c" FROM "full_types" WHERE "id" > ? ORDER BY "id" ASC AND "id" > ? ORDER BY "id" ASC, startLocation = 1, e = org.postgresql.util.PSQLException: 未设定参数值 2 的内容。
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:284)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:338)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.queryForPolling(JdbcInputFormat.java:691)
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.reachedEnd(JdbcInputFormat.java:259)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:137)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:269)

	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.reachedEnd(JdbcInputFormat.java:273)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:137)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:269)
	Suppressed: java.lang.RuntimeException: com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
		at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.close(BaseRichOutputFormat.java:358)
		at com.dtstack.chunjun.sink.DtOutputFormatSinkFunction.close(DtOutputFormatSinkFunction.java:127)
		at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:41)
		at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:861)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.runAndSuppressThrowable(StreamTask.java:840)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:753)
		at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cleanUpInvoke(SourceStreamTask.java:186)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:659)
		at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:620)
		at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
		at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
		at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105)
		at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79)
		at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:140)
		at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:475)
		at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:493)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:493)
		at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:449)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
Caused by: org.postgresql.util.PSQLException: 未设定参数值 2 的内容。
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:284)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:338)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.queryForPolling(JdbcInputFormat.java:691)
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.reachedEnd(JdbcInputFormat.java:259)
	... 4 more
```

### What you expected to happen

 throwing excpetion will not be occure

### How to reproduce

initialized the postgreSQL table `full_types`
```sql
CREATE TABLE full_types (
    id INTEGER NOT NULL,
    bytea_c BYTEA,
    small_c SMALLINT,
    int_c INTEGER,
    big_c BIGINT,
    real_c REAL,
    double_precision DOUBLE PRECISION,
    numeric_c NUMERIC(10, 5),
    decimal_c DECIMAL(10, 1),
    boolean_c BOOLEAN,
    text_c TEXT,
    char_c CHAR,
    character_c CHARACTER(3),
    character_varying_c CHARACTER VARYING(20),
    timestamp3_c TIMESTAMP(3),
    timestamp6_c TIMESTAMP(6),
    date_c DATE,
    time_c TIME(0),
    default_numeric_c NUMERIC,
    PRIMARY KEY (id)
);

ALTER TABLE full_types REPLICA IDENTITY FULL;

INSERT INTO full_types VALUES (
    1, '2', 32767, 65535, 2147483647, 5.5, 6.6, 123.12345, 404.4443, true,
    'Hello World', 'a', 'abc', 'abcd..xyz',  '2020-07-17 18:00:22.123', '2020-07-17 18:00:22.123456',
    '2020-07-17', '18:00:22', 500); 
```
Submit chunjob ,config as below
``` json
{
  "semantic" : "at-least-once",
  "errorRecord" : 0,
  "checkFormat" : true,
  "parallelism" : 1,
  "executeDdlAble" : false,
  "fullColumn" : [ "id", "bytea_c", "small_c", "int_c", "big_c", "real_c", "double_precision", "numeric_c", "decimal_c", "boolean_c", "text_c", "char_c", "character_c", "character_varying_c", "timestamp3_c", "timestamp6_c", "date_c", "time_c", "default_numeric_c" ],
  "pollingInterval" : 5000,
  "increment" : true,
  "flushIntervalMills" : 10000,
  "polling" : true,
  "querySql" : "SELECT \"id\", \"bytea_c\", \"small_c\", \"int_c\", \"big_c\", \"real_c\", \"double_precision\", \"numeric_c\", \"decimal_c\", \"boolean_c\", \"text_c\", \"char_c\", \"character_c\", \"character_varying_c\", \"timestamp3_c\", \"timestamp6_c\", \"date_c\", \"time_c\", \"default_numeric_c\" FROM \"full_types\" WHERE \"id\" > ? ORDER BY \"id\" ASC AND \"id\" > ? ORDER BY \"id\" ASC",
  "mode" : "INSERT",
  "password" : "******",
  "increColumn" : "id",
  "metricPluginRoot" : "null/metrics",
  "restoreColumn" : "id",
  "restoreColumnIndex" : 0,
  "connection" : [ {
    "table" : [ "full_types" ],
    "jdbcUrl" : [ "jdbc:postgresql://192.168.28.201:5432/tis?ssl=false&stringtype=unspecified&charSet=utf8" ]
  } ],
  "splitPk" : "id",
  "table" : "full_types",
  "queryTimeOut" : 1000,
  "restoreColumnType" : "INT",
  "fetchSize" : 1024,
  "useMaxFunc" : false,
  "column" : [ {
    "name" : "id",
    "type" : "INT",
    "index" : 0,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "bytea_c",
    "type" : "BYTEA",
    "index" : 1,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "small_c",
    "type" : "SMALLINT",
    "index" : 2,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "int_c",
    "type" : "INT",
    "index" : 3,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "big_c",
    "type" : "BIGINT",
    "index" : 4,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "real_c",
    "type" : "FLOAT",
    "index" : 5,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "double_precision",
    "type" : "DOUBLE PRECISION",
    "index" : 6,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "numeric_c",
    "type" : "DECIMAL",
    "index" : 7,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "decimal_c",
    "type" : "DECIMAL",
    "index" : 8,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "boolean_c",
    "type" : "BOOL",
    "index" : 9,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "text_c",
    "type" : "VARCHAR",
    "index" : 10,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "char_c",
    "type" : "VARCHAR",
    "index" : 11,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "character_c",
    "type" : "VARCHAR",
    "index" : 12,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "character_varying_c",
    "type" : "VARCHAR",
    "index" : 13,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "timestamp3_c",
    "type" : "TIMESTAMP",
    "index" : 14,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "timestamp6_c",
    "type" : "TIMESTAMP",
    "index" : 15,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "date_c",
    "type" : "DATE",
    "index" : 16,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "time_c",
    "type" : "TIME",
    "index" : 17,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "default_numeric_c",
    "type" : "DECIMAL",
    "index" : 18,
    "notNull" : false,
    "part" : false
  } ],
  "errorPercentage" : -1,
  "fieldNameList" : [ ],
  "withNoLock" : false,
  "increColumnIndex" : 0,
  "allReplace" : false,
  "splitStrategy" : "range",
  "initReporter" : true,
  "jdbcUrl" : "jdbc:postgresql://192.168.28.201:5432/tis?ssl=false&stringtype=unspecified&charSet=utf8",
  "connectTimeOut" : 600,
  "batchSize" : 1,
  "speedBytes" : 0,
  "rowSizeCalculatorType" : "objectSizeCalculator",
  "metricPluginName" : "prometheus",
  "properties" : { },
  "increColumnType" : "INT",
  "username" : "postgres"
} 
```

### Anything else

I have reviewd the code com.dtstack.chunjun.connector.postgresql.source.PostgresqlInputFormat extend from `JdbcInputFormat`.

by the time execute the method `JdbcInputFormat.executeQuery()` from Flink job invocation, the same where cause `"id" > ? ORDER BY "id" ASC` has been append twice,

* First append: at the child class method `PostgresqlInputFormat.queryPollingWithOutStartLocation()`
* second append: at the parent class method `JdbcInputFormat.executeQuery()`

### Version

1.12_release

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KinoMin** [comment]
I did not reproduce the problem. Could you please show me the content of your json file?
