### ISSUE TITLE
[Feature][Hive] Hive/Hdfs Sink support 'smallint' type.

### ISSUE THREAD

**Issue by FlechazoW** [DTStack/chunjun#1129]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

 mysql to hive数据同步不支持【smallint】，但是文档显示支持。

报错日志：

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Unsupported type: [SMALLINT]
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Unsupported type: [SMALLINT]
at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:224)
at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)
at com.dtstack.engine.flink.FlinkClient.submitJobWithJar(FlinkClient.java:789)
at com.dtstack.engine.flink.FlinkClient.submitSyncJob(FlinkClient.java:731)
at com.dtstack.engine.flink.FlinkClient.lambda$processSubmitJobWithType$3(FlinkClient.java:478)
at com.dtstack.engine.base.util.SecurityUtils.login(SecurityUtils.java:80)
at com.dtstack.engine.base.util.SecurityUtils.login(SecurityUtils.java:68)
at com.dtstack.engine.flink.FlinkClient.processSubmitJobWithType(FlinkClient.java:465)
at com.dtstack.engine.common.client.AbstractClient.submitJob(AbstractClient.java:48)
at com.dtstack.engine.common.client.ClientProxy$2.execute(ClientProxy.java:89)
at com.dtstack.engine.common.client.ClientProxy$2.execute(ClientProxy.java:85)
at com.dtstack.engine.common.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:13)
at com.dtstack.engine.common.client.ClientProxy.lambda$submitJob$1(ClientProxy.java:85)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.dtstack.flinkx.throwable.UnsupportedTypeException: Unsupported type: [SMALLINT]
at com.dtstack.flinkx.connector.hdfs.converter.HdfsOrcColumnConverter.createInternalConverter(HdfsOrcColumnConverter.java:160)
at com.dtstack.flinkx.connector.hdfs.converter.HdfsOrcColumnConverter.<init>(HdfsOrcColumnConverter.java:69)
at com.dtstack.flinkx.connector.hdfs.util.HdfsUtil.createRowConverter(HdfsUtil.java:342)
at com.dtstack.flinkx.connector.hdfs.sink.HdfsSinkFactory.createSink(HdfsSinkFactory.java:56)
at com.dtstack.flinkx.Main.exeSyncJob(Main.java:239)
at com.dtstack.flinkx.Main.main(Main.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
... 19 more

### Use case

hive / hdfs 同步 smallint 数据成功。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
Already support. So close it.
