### ISSUE TITLE
[Bug] [Connector] sqlserver cdc connector starting throw NullPointerException in standalone mode

### ISSUE THREAD

**Issue by frank451209123** [DTStack/chunjun#1212]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

**系统环境:** 
centos 7.9  flink 1.12.7、sqlserver2016、postgresql 13
**执行的job sql语句：**
CREATE TABLE source
(
   id bigint NOT NULL,
	parent_id bigint NOT NULL,
	project_no varchar(50) NOT NULL,
	sales_order varchar(50) NOT NULL,
	plant_code varchar(50) NULL,
	product_line varchar(50) NULL,
	sales_order_item varchar(50) NOT NULL,
	bay_id varchar(50) NULL,
	order_no varchar(50) NOT NULL,
	order_status int NULL,
	order_level int NOT NULL,
	sap_order_status varchar(50) NULL,
	material_no varchar(50) NOT NULL,
	material_descr varchar(255) NULL,
	final_material varchar(50) NULL,
	init_production_center varchar(50) NULL,
	final_production_center varchar(50) NULL,
	module_code varchar(50) NULL,
	material_no_fellow varchar(50) NULL,
	order_no_fellow varchar(50) NULL,
	item_component_list varchar(50) NULL,
	reservation varchar(50) NULL,
	reservation_item varchar(50) NULL,
	material_picking1_times int NULL,
	material_picking2_times int NULL,
	first_date timestamp NULL,
	basic_start_time timestamp NULL,
	basic_finish_time timestamp NULL,
	product_start_time timestamp NULL,
	mes_plan_start_time timestamp NULL,
	mes_plan_end_time timestamp NULL,
	mes_task_exec_time timestamp NULL,
	mes_plan_u_time timestamp NULL,
	is_deleted int NULL,
	is_modify int NULL,
	create_user varchar(50)  NULL,
	update_user varchar(50)  NULL,
	create_time timestamp NULL,
	update_time timestamp NOT NULL,
	PRIMARY KEY (id) NOT ENFORCED
) WITH (
      'connector' = 'sqlservercdc-x'
      ,'username' = 'sa'
      ,'password' = 'fzdP@ssw0rd'
      ,'cat' = 'insert,delete,update'
      ,'url' = 'jdbc:sqlserver://192.168.8.224:1433;databaseName=siemens'
      ,'table' = 'dbo.ETO_PDM_Header'
      ,'timestamp-format.standard' = 'SQL'
      ,'database' = 'siemens'
      ,'poll-interval' = '1000'
      );

CREATE TABLE sink
(
   id numeric NOT NULL,
	parent_id numeric NOT NULL,
	project_no varchar(50) NOT NULL,
	sales_order varchar(50) NOT NULL,
	plant_code varchar(50) NULL,
	product_line varchar(50) NULL,
	sales_order_item varchar(50) NOT NULL,
	bay_id varchar(50) NULL,
	order_no varchar(50) NOT NULL,
	order_status int NULL,
	order_level int NOT NULL,
	sap_order_status varchar(50) NULL,
	material_no varchar(50) NOT NULL,
	material_descr varchar(255) NULL,
	final_material varchar(50) NULL,
	init_production_center varchar(50) NULL,
	final_production_center varchar(50) NULL,
	module_code varchar(50) NULL,
	material_no_fellow varchar(50) NULL,
	order_no_fellow varchar(50) NULL,
	item_component_list varchar(50) NULL,
	reservation varchar(50) NULL,
	reservation_item varchar(50) NULL,
	material_picking1_times int NULL,
	material_picking2_times int NULL,
	first_date timestamp NULL,
	basic_start_time timestamp NULL,
	basic_finish_time timestamp NULL,
	product_start_time timestamp NULL,
	mes_plan_start_time timestamp NULL,
	mes_plan_end_time timestamp NULL,
	mes_task_exec_time timestamp NULL,
	mes_plan_u_time timestamp NULL,
	is_deleted int NULL,
	is_modify int NULL,
	create_user varchar(50) NULL,
	update_user varchar(50) NULL,
	create_time timestamp NULL,
	update_time timestamp NULL,
	PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'postgresql-x',
    'url' = 'jdbc:postgresql://192.168.0.116:52345/postgres',
    'table-name' = 'siemens2_ETO_PDM_Header',
    'username' = 'postgres',
    'password' = 'P@stgres123',
    'sink.buffer-flush.max-rows' = '1024',
    'sink.buffer-flush.interval' = '1000',
    'sink.all-replace' = 'true',
    'sink.parallelism' = '1'
);

insert into sink
select *
from source u;

**启动日志信息见下：**
CHUNJUN_HOME is auto set  /home/chunjun/chunjun-dist
FLINK_HOME is /home/flink-1.12.7
HADOOP_HOME is /home/hadoop/hadoop-3.1.3
ChunJun starting ...
start command: /usr/local/tools/java-se-8u40-ri/bin/java -cp /home/chunjun/chunjun-dist/../lib/* com.dtstack.chunjun.client.Launcher -job sqlserver_cdc_pg.sql -mode standalone -jobType sql -chunjunDistDir /home/chunjun/chunjun-dist -flinkConfDir /home/flink-1.12.7/conf -flinkLibDir /home/flink-1.12.7/lib -hadoopConfDir /home/hadoop/hadoop-3.1.3/etc/hadoop
log4j:ERROR Could not find value for key log4j.appender.logfile
log4j:ERROR Could not instantiate appender named "logfile".
2022-09-02 11:51:10,104 - 0    INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: jobmanager.rpc.address, localhost
2022-09-02 11:51:10,106 - 2    INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: jobmanager.rpc.port, 6123
2022-09-02 11:51:10,106 - 2    INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: jobmanager.memory.process.size, 1600m
2022-09-02 11:51:10,106 - 2    INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: taskmanager.memory.process.size, 1728m
2022-09-02 11:51:10,106 - 2    INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: taskmanager.numberOfTaskSlots, 4
2022-09-02 11:51:10,107 - 3    INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: parallelism.default, 1
2022-09-02 11:51:10,107 - 3    INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: jobmanager.execution.failover-strategy, region
2022-09-02 11:51:10,170 - 66   INFO  [main] org.apache.flink.configuration.Configuration:Config uses fallback configuration key 'jobmanager.rpc.address' instead of key 'rest.address'
2022-09-02 11:51:10,435 - 331  INFO  [main] com.dtstack.chunjun.Main:------------program params-------------------------
2022-09-02 11:51:10,436 - 332  INFO  [main] com.dtstack.chunjun.Main:-flinkLibDir
2022-09-02 11:51:10,436 - 332  INFO  [main] com.dtstack.chunjun.Main:/home/flink-1.12.7/lib
2022-09-02 11:51:10,437 - 333  INFO  [main] com.dtstack.chunjun.Main:-p
2022-09-02 11:51:10,437 - 333  INFO  [main] com.dtstack.chunjun.Main:
2022-09-02 11:51:10,437 - 333  INFO  [main] com.dtstack.chunjun.Main:-job
2022-09-02 11:51:10,437 - 333  INFO  [main] com.dtstack.chunjun.Main:CREATE+TABLE+source%0A%28%0A+++id+bigint+NOT+NULL%2C%0A%09parent_id+bigint+NOT+NULL%2C%0A%09project_no+varchar%2850%29+NOT+NULL%2C%0A%09sales_order+varchar%2850%29+NOT+NULL%2C%0A%09plant_code+varchar%2850%29+NULL%2C%0A%09product_line+varchar%2850%29+NULL%2C%0A%09sales_order_item+varchar%2850%29+NOT+NULL%2C%0A%09bay_id+varchar%2850%29+NULL%2C%0A%09order_no+varchar%2850%29+NOT+NULL%2C%0A%09order_status+int+NULL%2C%0A%09order_level+int+NOT+NULL%2C%0A%09sap_order_status+varchar%2850%29+NULL%2C%0A%09material_no+varchar%2850%29+NOT+NULL%2C%0A%09material_descr+varchar%28255%29+NULL%2C%0A%09final_material+varchar%2850%29+NULL%2C%0A%09init_production_center+varchar%2850%29+NULL%2C%0A%09final_production_center+varchar%2850%29+NULL%2C%0A%09module_code+varchar%2850%29+NULL%2C%0A%09material_no_fellow+varchar%2850%29+NULL%2C%0A%09order_no_fellow+varchar%2850%29+NULL%2C%0A%09item_component_list+varchar%2850%29+NULL%2C%0A%09reservation+varchar%2850%29+NULL%2C%0A%09reservation_item+varchar%2850%29+NULL%2C%0A%09material_picking1_times+int+NULL%2C%0A%09material_picking2_times+int+NULL%2C%0A%09first_date+timestamp+NULL%2C%0A%09basic_start_time+timestamp+NULL%2C%0A%09basic_finish_time+timestamp+NULL%2C%0A%09product_start_time+timestamp+NULL%2C%0A%09mes_plan_start_time+timestamp+NULL%2C%0A%09mes_plan_end_time+timestamp+NULL%2C%0A%09mes_task_exec_time+timestamp+NULL%2C%0A%09mes_plan_u_time+timestamp+NULL%2C%0A%09is_deleted+int+NULL%2C%0A%09is_modify+int+NULL%2C%0A%09create_user+varchar%2850%29++NULL%2C%0A%09update_user+varchar%2850%29++NULL%2C%0A%09create_time+timestamp+NULL%2C%0A%09update_time+timestamp+NOT+NULL%2C%0A%09PRIMARY+KEY+%28id%29+NOT+ENFORCED+%0A%29+WITH+%28%0A++++++%27connector%27+%3D+%27sqlservercdc-x%27%0A++++++%2C%27username%27+%3D+%27sa%27%0A++++++%2C%27password%27+%3D+%27fzdP%40ssw0rd%27%0A++++++%2C%27cat%27+%3D+%27insert%2Cdelete%2Cupdate%27%0A++++++%2C%27url%27+%3D+%27jdbc%3Asqlserver%3A%2F%2F192.168.8.224%3A1433%3BdatabaseName%3Dsiemens%27%0A++++++%2C%27table%27+%3D+%27dbo.ETO_PDM_Header%27%0A++++++%2C%27timestamp-format.standard%27+%3D+%27SQL%27%0A++++++%2C%27database%27+%3D+%27siemens%27%0A++++++%2C%27poll-interval%27+%3D+%271000%27%0A++++++%29%3B%0A%0ACREATE+TABLE+sink%0A%28%0A+++id+numeric+NOT+NULL%2C%0A%09parent_id+numeric+NOT+NULL%2C%0A%09project_no+varchar%2850%29+NOT+NULL%2C%0A%09sales_order+varchar%2850%29+NOT+NULL%2C%0A%09plant_code+varchar%2850%29+NULL%2C%0A%09product_line+varchar%2850%29+NULL%2C%0A%09sales_order_item+varchar%2850%29+NOT+NULL%2C%0A%09bay_id+varchar%2850%29+NULL%2C%0A%09order_no+varchar%2850%29+NOT+NULL%2C%0A%09order_status+int+NULL%2C%0A%09order_level+int+NOT+NULL%2C%0A%09sap_order_status+varchar%2850%29+NULL%2C%0A%09material_no+varchar%2850%29+NOT+NULL%2C%0A%09material_descr+varchar%28255%29+NULL%2C%0A%09final_material+varchar%2850%29+NULL%2C%0A%09init_production_center+varchar%2850%29+NULL%2C%0A%09final_production_center+varchar%2850%29+NULL%2C%0A%09module_code+varchar%2850%29+NULL%2C%0A%09material_no_fellow+varchar%2850%29+NULL%2C%0A%09order_no_fellow+varchar%2850%29+NULL%2C%0A%09item_component_list+varchar%2850%29+NULL%2C%0A%09reservation+varchar%2850%29+NULL%2C%0A%09reservation_item+varchar%2850%29+NULL%2C%0A%09material_picking1_times+int+NULL%2C%0A%09material_picking2_times+int+NULL%2C%0A%09first_date+timestamp+NULL%2C%0A%09basic_start_time+timestamp+NULL%2C%0A%09basic_finish_time+timestamp+NULL%2C%0A%09product_start_time+timestamp+NULL%2C%0A%09mes_plan_start_time+timestamp+NULL%2C%0A%09mes_plan_end_time+timestamp+NULL%2C%0A%09mes_task_exec_time+timestamp+NULL%2C%0A%09mes_plan_u_time+timestamp+NULL%2C%0A%09is_deleted+int+NULL%2C%0A%09is_modify+int+NULL%2C%0A%09create_user+varchar%2850%29+NULL%2C%0A%09update_user+varchar%2850%29+NULL%2C%0A%09create_time+timestamp+NULL%2C%0A%09update_time+timestamp+NULL%2C%0A%09PRIMARY+KEY+%28id%29+NOT+ENFORCED+%0A%29+WITH+%28%0A++++%27connector%27+%3D+%27postgresql-x%27%2C%0A++++%27url%27+%3D+%27jdbc%3Apostgresql%3A%2F%2F192.168.0.116%3A52345%2Fpostgres%27%2C%0A++++%27table-name%27+%3D+%27siemens2_ETO_PDM_Header%27%2C%0A++++%27username%27+%3D+%27postgres%27%2C%0A++++%27password%27+%3D+%27P%40stgres123%27%2C%0A++++%27sink.buffer-flush.max-rows%27+%3D+%271024%27%2C+%0A++++%27sink.buffer-flush.interval%27+%3D+%271000%27%2C+%0A++++%27sink.all-replace%27+%3D+%27true%27%2C+++++++++++++++++++++++%0A++++%27sink.parallelism%27+%3D+%271%27%0A%29%3B%0A%0Ainsert+into+sink%0Aselect+*%0Afrom+source+u%3B%0A%0A%0A
2022-09-02 11:51:10,438 - 334  INFO  [main] com.dtstack.chunjun.Main:-jobName
2022-09-02 11:51:10,438 - 334  INFO  [main] com.dtstack.chunjun.Main:Flink_Job
2022-09-02 11:51:10,438 - 334  INFO  [main] com.dtstack.chunjun.Main:-chunjunDistDir
2022-09-02 11:51:10,438 - 334  INFO  [main] com.dtstack.chunjun.Main:/home/chunjun/chunjun-dist
2022-09-02 11:51:10,438 - 334  INFO  [main] com.dtstack.chunjun.Main:-jobType
2022-09-02 11:51:10,439 - 335  INFO  [main] com.dtstack.chunjun.Main:sql
2022-09-02 11:51:10,439 - 335  INFO  [main] com.dtstack.chunjun.Main:-hadoopConfDir
2022-09-02 11:51:10,439 - 335  INFO  [main] com.dtstack.chunjun.Main:/home/hadoop/hadoop-3.1.3/etc/hadoop
2022-09-02 11:51:10,439 - 335  INFO  [main] com.dtstack.chunjun.Main:-confProp
2022-09-02 11:51:10,439 - 335  INFO  [main] com.dtstack.chunjun.Main:{}
2022-09-02 11:51:10,440 - 336  INFO  [main] com.dtstack.chunjun.Main:-pluginLoadMode
2022-09-02 11:51:10,440 - 336  INFO  [main] com.dtstack.chunjun.Main:shipfile
2022-09-02 11:51:10,440 - 336  INFO  [main] com.dtstack.chunjun.Main:-mode
2022-09-02 11:51:10,440 - 336  INFO  [main] com.dtstack.chunjun.Main:standalone
2022-09-02 11:51:10,440 - 336  INFO  [main] com.dtstack.chunjun.Main:-flinkConfDir
2022-09-02 11:51:10,440 - 336  INFO  [main] com.dtstack.chunjun.Main:/home/flink-1.12.7/conf
2022-09-02 11:51:10,441 - 337  INFO  [main] com.dtstack.chunjun.Main:-------------------------------------------
2022-09-02 11:51:10,446 - 342  INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: jobmanager.rpc.address, localhost
2022-09-02 11:51:10,446 - 342  INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: jobmanager.rpc.port, 6123
2022-09-02 11:51:10,447 - 343  INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: jobmanager.memory.process.size, 1600m
2022-09-02 11:51:10,447 - 343  INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: taskmanager.memory.process.size, 1728m
2022-09-02 11:51:10,447 - 343  INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: taskmanager.numberOfTaskSlots, 4
2022-09-02 11:51:10,448 - 344  INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: parallelism.default, 1
2022-09-02 11:51:10,448 - 344  INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: jobmanager.execution.failover-strategy, region
2022-09-02 11:51:11,821 - 1717 INFO  [main] com.dtstack.chunjun.Main:Register to table configuration:{table.dynamic-table-options.enabled=true, pipeline.name=Flink_Job}
2022-09-02 11:51:11,850 - 1746 INFO  [main] com.dtstack.chunjun.util.PluginUtil:ChunJun executionMode: standalone
2022-09-02 11:51:11,850 - 1746 INFO  [main] com.dtstack.chunjun.util.PluginUtil:ChunJun reset pipeline.jars: [file:/home/chunjun/chunjun-dist/dirty-data-collector/log/chunjun-dirty-log.jar]
2022-09-02 11:51:12,196 - 2092 INFO  [main] com.dtstack.chunjun.util.PluginUtil:ChunJun executionMode: standalone
2022-09-02 11:51:12,196 - 2092 INFO  [main] com.dtstack.chunjun.util.PluginUtil:ChunJun reset pipeline.jars: [file:/home/chunjun/chunjun-dist/dirty-data-collector/log/chunjun-dirty-log.jar, file:/home/chunjun/chunjun-dist/connector/sqlservercdc/chunjun-connector-sqlservercdc.jar]
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: com.dtstack.chunjun.throwable.ChunJunSqlParseException:
----------sql start---------
1>
2>
3>    insert into sink
4>    select *
5>    from source u

----------sql end---------

null
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:366)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:219)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)
	at com.dtstack.chunjun.client.util.JobGraphUtil.buildJobGraph(JobGraphUtil.java:62)
	at com.dtstack.chunjun.client.standalone.StandaloneClusterClientHelper.submit(StandaloneClusterClientHelper.java:61)
	at com.dtstack.chunjun.client.Launcher.main(Launcher.java:119)
Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: com.dtstack.chunjun.throwable.ChunJunSqlParseException:
----------sql start---------
1>
2>
3>    insert into sink
4>    select *
5>    from source u

----------sql end---------

null
	at com.dtstack.chunjun.Main.exeSqlJob(Main.java:160)
	at com.dtstack.chunjun.Main.main(Main.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:349)
	... 7 more
Caused by: com.dtstack.chunjun.throwable.ChunJunSqlParseException:
----------sql start---------
1>
2>
3>    insert into sink
4>    select *
5>    from source u

----------sql end---------

null
	at com.dtstack.chunjun.sql.parser.SqlParser.lambda$parseSql$1(SqlParser.java:72)
	at com.dtstack.chunjun.sql.parser.SqlParser$$Lambda$248/795594631.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.dtstack.chunjun.sql.parser.SqlParser.parseSql(SqlParser.java:66)
	at com.dtstack.chunjun.Main.exeSqlJob(Main.java:151)
	... 13 more
Caused by: java.lang.NullPointerException
	at com.dtstack.chunjun.connector.sqlservercdc.inputFormat.SqlServerCdcInputFormatBuilder.setSqlServerCdcConf(SqlServerCdcInputFormatBuilder.java:71)
	at com.dtstack.chunjun.connector.sqlservercdc.source.SqlServerCdcDynamicTableSource.getScanRuntimeProvider(SqlServerCdcDynamicTableSource.java:63)
	at org.apache.flink.table.planner.sources.DynamicSourceUtils.validateScanSource(DynamicSourceUtils.java:254)
	at org.apache.flink.table.planner.sources.DynamicSourceUtils.prepareDynamicSource(DynamicSourceUtils.java:71)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:101)
	at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:165)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:157)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:902)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:871)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:250)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:564)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:248)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:77)
	at org.apache.flink.table.api.internal.StatementSetImpl.addInsertSql(StatementSetImpl.java:50)
	at com.dtstack.chunjun.sql.parser.InsertStmtParser.execStmt(InsertStmtParser.java:47)
	at com.dtstack.chunjun.sql.parser.AbstractStmtParser.handleStmt(AbstractStmtParser.java:50)
	at com.dtstack.chunjun.sql.parser.AbstractStmtParser.handleStmt(AbstractStmtParser.java:52)
	at com.dtstack.chunjun.sql.parser.AbstractStmtParser.handleStmt(AbstractStmtParser.java:52)
	at com.dtstack.chunjun.sql.parser.SqlParser.lambda$parseSql$1(SqlParser.java:69)
	... 25 more

### What you expected to happen

throwing NullPointerException without any other message

### How to reproduce

sh bin/chunjun-standalone.sh -job sqlserver_cdc_pg.sql

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
PR merged.
