### ISSUE TITLE
[Bug] [Kudu] Unsupported type: [TIMESTAMP_WITHOUT_TIME_ZONE]

### ISSUE THREAD

**Issue by JaryZhen** [DTStack/chunjun#1256]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

java.lang.RuntimeException: com.dtstack.chunjun.throwable.ChunJunRuntimeException: com.dtstack.chunjun.throwable.UnsupportedTypeException: Unsupported type: [TIMESTAMP_WITHOUT_TIME_ZONE]

	at com.dtstack.chunjun.client.LauncherTest.testYarn(LauncherTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: com.dtstack.chunjun.throwable.UnsupportedTypeException: Unsupported type: [TIMESTAMP_WITHOUT_TIME_ZONE]
	at com.dtstack.chunjun.Main.parseCheck(Main.java:153)
	at com.dtstack.chunjun.Main.main(Main.java:125)
	at com.dtstack.chunjun.client.local.LocalClusterClientHelper.submit(LocalClusterClientHelper.java:35)
	at com.dtstack.chunjun.client.Launcher.main(Launcher.java:120)
	at com.dtstack.chunjun.client.LauncherTest.testYarn(LauncherTest.java:93)
	... 27 more
Caused by: com.dtstack.chunjun.throwable.UnsupportedTypeException: Unsupported type: [TIMESTAMP_WITHOUT_TIME_ZONE]
	at com.dtstack.chunjun.connector.kudu.converter.KuduRawTypeConverter.apply(KuduRawTypeConverter.java:75)
	at com.dtstack.chunjun.util.TableUtil.createTableSchema(TableUtil.java:185)
	at com.dtstack.chunjun.util.TableUtil.createRowType(TableUtil.java:170)
	at com.dtstack.chunjun.connector.kudu.table.KuduDynamicTableSink.getSinkRuntimeProvider(KuduDynamicTableSink.java:90)
	at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalSink.createSinkTransformation(CommonPhysicalSink.scala:78)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.scala:109)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.scala:43)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNode.translateToPlan(ExecNode.scala:59)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNode.translateToPlan$(ExecNode.scala:57)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecSink.translateToPlan(StreamExecSink.scala:43)
	at org.apache.flink.table.planner.delegation.StreamPlanner.$anonfun$translateToPlan$1(StreamPlanner.scala:66)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.flink.table.planner.delegation.StreamPlanner.translateToPlan(StreamPlanner.scala:65)
	at org.apache.flink.table.planner.delegation.StreamPlanner.explain(StreamPlanner.scala:103)
	at org.apache.flink.table.planner.delegation.StreamPlanner.explain(StreamPlanner.scala:42)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.explainInternal(TableEnvironmentImpl.java:630)
	at org.apache.flink.table.api.internal.StatementSetImpl.explain(StatementSetImpl.java:92)
	at com.dtstack.chunjun.Main.parseCheck(Main.java:147)
	... 31 more

### What you expected to happen

none

### How to reproduce

CREATE TABLE source_ods_fact_user_ippv
(
    f_sequence   INT,
    f_random     INT,
    f_random_str STRING,
    tss          TIMESTAMP
) WITH (
      'connector' = 'kafka-x',
      'topic' = 'xxnk',
      'properties.bootstrap.servers' = 'xxx',
      'properties.group.id' = 'luna_g1',
      'scan.startup.mode' = 'latest-offset',
      'format' = 'json' --,'json.timestamp-format.standard' = 'SQL'
      );
--------
create table iot_product
(
    f_sequence   INT,
    f_random     INT,
    f_random_str STRING,
    tss          TIMESTAMP
) WITH (
      'connector' = 'kudu-x',
      'masters' = 'xxx',
      'table-name' = 'xxx',
      'sink.parallelism' = '2'
      );
------
INSERT INTO iot_product
select *
from source_ods_fact_user_ippv;

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by meng1222** [comment]
This problem should be caused by this line of code：[link](https://github.com/DTStack/chunjun/blob/c455e77385afadfaaddd8cbe45d172246eb2658c/chunjun-connectors/chunjun-connector-kudu/src/main/java/com/dtstack/chunjun/connector/kudu/table/KuduDynamicTableSink.java#L77)
