### ISSUE TITLE
[Question][chunjun-connection-jdbc-base] In YarnSession mode, JDBC reads doris error

### ISSUE THREAD

**Issue by KinoMin** [DTStack/chunjun#1297]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

First, my table structure is as follows
```sql
CREATE TABLE `ispl_fcst_goods_sales_daily` (
  `tenant_id` bigint(20) NOT NULL ,
  `store_id` varchar(20) NOT NULL ,
  `item_id` varchar(50) NOT NULL,
  `sale_date` date NOT NULL,
  `account_date` date NOT NULL,
  `sale_qty` decimal64(12, 4) NOT NULL DEFAULT "0" ,
  `sale_amt` decimal64(12, 4) NOT NULL DEFAULT "0",
  `retail_discount` decimal64(12, 4) NOT NULL DEFAULT "0" ,
  `ec_qty` decimal64(12, 4) NOT NULL DEFAULT "0" ,
  `ec_amt` decimal64(12, 4) NOT NULL DEFAULT "0" ,
  `ec_discount` decimal64(12, 4) NOT NULL DEFAULT "0" ,
  `total_qty` decimal64(12, 4) NOT NULL DEFAULT "0" ,
  `total_amt` decimal64(12, 4) NOT NULL DEFAULT "0" ,
  `total_discount` decimal64(12, 4) NOT NULL DEFAULT "0" ,
  `etl_time` datetime NULL COMMENT "",
  INDEX i_ispl_fcst_goods_sales_daily (`store_id`) USING BITMAP,
  INDEX i_ispl_fcst_goods_sales_daily_2 (`sale_date`) USING BITMAP
) ENGINE=OLAP 
PRIMARY KEY(`tenant_id`, `store_id`, `item_id`, `sale_date`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`tenant_id`, `store_id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```

My chunjun json is as follows
```json
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "password" : "**",
          "startLocation" : "",
          "increColumn" : "",
          "column" : [ {
            "format" : "",
            "name" : "tenant_id",
            "type" : "BIGINT",
            "key" : "tenant_id"
          }, {
            "format" : "",
            "name" : "store_id",
            "type" : "VARCHAR",
            "key" : "store_id"
          }, {
            "format" : "",
            "name" : "item_id",
            "type" : "VARCHAR",
            "key" : "item_id"
          }, {
            "format" : "",
            "name" : "sale_date",
            "type" : "DATE",
            "key" : "sale_date"
          }, {
            "format" : "",
            "name" : "account_date",
            "type" : "DATE",
            "key" : "account_date"
          }, {
            "format" : "",
            "name" : "sale_qty",
            "type" : "DECIMAL",
            "key" : "sale_qty"
          }, {
            "format" : "",
            "name" : "sale_amt",
            "type" : "DECIMAL",
            "key" : "sale_amt"
          }, {
            "format" : "",
            "name" : "retail_discount",
            "type" : "DECIMAL",
            "key" : "retail_discount"
          }, {
            "format" : "",
            "name" : "ec_qty",
            "type" : "DECIMAL",
            "key" : "ec_qty"
          }, {
            "format" : "",
            "name" : "ec_amt",
            "type" : "DECIMAL",
            "key" : "ec_amt"
          }, {
            "format" : "",
            "name" : "ec_discount",
            "type" : "DECIMAL",
            "key" : "ec_discount"
          }, {
            "format" : "",
            "name" : "total_qty",
            "type" : "DECIMAL",
            "key" : "total_qty"
          }, {
            "format" : "",
            "name" : "total_amt",
            "type" : "DECIMAL",
            "key" : "total_amt"
          }, {
            "format" : "",
            "name" : "total_discount",
            "type" : "DECIMAL",
            "key" : "total_discount"
          }, {
            "format" : "",
            "name" : "etl_time",
            "type" : "DATETIME",
            "key" : "etl_time"
          } ],
          "connection" : [ {
            "password" : "**",
            "jdbcUrl" : [ "jdbc:mysql://localhost:1234/kinodb1" ],
            "table" : [ "ispl_fcst_goods_sales_daily" ],
            "username" : "kino"
          } ],
          "username" : "kino"
        },
        "name" : "mysqlreader"
      },
      "writer" : {
        "parameter" : {
          "postSql" : [ ],
          "mode" : "update",
          "password" : "**",
          "column" : [ {
            "name" : "tenant_id",
            "format" : "",
            "isPart" : false,
            "type" : "BIGINT",
            "key" : "tenant_id"
          }, {
            "name" : "store_id",
            "format" : "",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "store_id"
          }, {
            "name" : "item_id",
            "format" : "",
            "isPart" : false,
            "type" : "VARCHAR",
            "key" : "item_id"
          }, {
            "name" : "sale_date",
            "format" : "",
            "isPart" : false,
            "type" : "DATE",
            "key" : "sale_date"
          }, {
            "name" : "account_date",
            "format" : "",
            "isPart" : false,
            "type" : "DATE",
            "key" : "account_date"
          }, {
            "name" : "sale_qty",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "sale_qty"
          }, {
            "name" : "sale_amt",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "sale_amt"
          }, {
            "name" : "retail_discount",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "retail_discount"
          }, {
            "name" : "ec_qty",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "ec_qty"
          }, {
            "name" : "ec_amt",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "ec_amt"
          }, {
            "name" : "ec_discount",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "ec_discount"
          }, {
            "name" : "total_qty",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "total_qty"
          }, {
            "name" : "total_amt",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "total_amt"
          }, {
            "name" : "total_discount",
            "format" : "",
            "isPart" : false,
            "type" : "DECIMAL",
            "key" : "total_discount"
          }, {
            "name" : "etl_time",
            "format" : "",
            "isPart" : false,
            "type" : "DATETIME",
            "key" : "etl_time"
          } ],
          "connection" : [ {
            "jdbcUrl" : "jdbc:mysql://localhost:3306/kinodb2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&&maxReconnects=5&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai",
            "table" : [ "ispl_fcst_goods_sales_daily" ]
          } ],
          "writeMode" : "update",
          "sourceIds" : [ null ],
          "preSql" : [ ],
          "username" : "kino"
        },
        "name" : "mysqlwriter"
      }
    } ],
    "setting" : {
      "restore" : {
        "isRestore" : false,
        "isStream" : false
      },
      "speed" : {
        "readerChannel" : 1,
        "writerChannel" : 1,
        "bytes" : -1048576,
        "channel" : 1
      }
    }
  }
}
```
I try to debug the program
```java
com.dtstack.chunjun.converter.AbstractRowConverter.java: 90 
protected IDeserializationConverter wrapIntoNullableInternalConverter(
            IDeserializationConverter IDeserializationConverter) {
        return val -> {
            if (val == null) {
                return null;
            } else {
                try {
                    String name = val.getClass().getName();
                    // print datatype
                    LOG.info("val: " + val + ", datatype: " + name);
                    return IDeserializationConverter.deserialize(val);
                } catch (Exception e) {
                    LOG.error("value [{}] convent failed ", val);
                    throw e;
                }
            }
        };
    }
```
result
```bash
2022-10-10 23:59:57,398 INFO  com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter [] - val: 177, datatype: java.lang.Long
2022-10-10 23:59:57,399 INFO  com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter [] - val: 1207, datatype: java.lang.String
2022-10-10 23:59:57,399 INFO  com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter [] - val: 1000, datatype: java.lang.String
2022-10-10 23:59:57,399 ERROR com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter [] - value [1000] convent failed 
....
com.dtstack.chunjun.throwable.ReadRecordException: 
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:298)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:198)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:68)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.lambda$createInternalConverter$cdd9fd22$3(JdbcColumnConverter.java:140)
	at com.dtstack.chunjun.converter.AbstractRowConverter.lambda$wrapIntoNullableInternalConverter$66e1293c$1(AbstractRowConverter.java:100)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.toInternal(JdbcColumnConverter.java:114)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.toInternal(JdbcColumnConverter.java:56)
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:285)
	... 6 more

JdbcColumnConverter.java:140
case INTEGER:
                return val -> new BigDecimalColumn((Integer) val);
```
question：
1. Why the data type is string, will return `val -> new BigDecimalColumn((Integer) val);` instead of return `val -> new StringColumn(val.toString());`?
2. Why don't I get exceptions in local mode, but only in YarnSession mode？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
Can you provide one of MySQL's data so I can re-current this issue?

**Comment by KinoMin** [comment]
> Can you provide one of MySQL's data so I can re-current this issue?

Thanks for the reply, I debugged and found that it may not be the problem of chunjun, but the metadata of my database, because item_id is changed from int to varchar, and the data type obtained by resultSet.getMetaData() in the code is still int type instead of string type.

**Comment by KinoMin** [comment]
> Can you provide one of MySQL's data so I can re-current this issue?

But I don't understand why there is no problem in chunjun local mode, and the item_id type obtained under YarnSession is int.
