### ISSUE TITLE
local模式下启动失败

### ISSUE THREAD

**Issue by cdma-git** [DTStack/chunjun#1356]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

**在以local模式运行脚本的时候，报错如下**

```
Exception in thread "main" com.dtstack.chunjun.throwable.NoRestartException: Load restore plugins failed!
	at com.dtstack.chunjun.util.DataSyncFactoryUtil.discoverDdlHandler(DataSyncFactoryUtil.java:172)
	at com.dtstack.chunjun.Main.exeSyncJob(Main.java:192)
	at com.dtstack.chunjun.Main.main(Main.java:116)
	at com.dtstack.chunjun.client.local.LocalClusterClientHelper.submit(LocalClusterClientHelper.java:35)
	at com.dtstack.chunjun.client.Launcher.main(Launcher.java:119)
Caused by: java.lang.NullPointerException
	at com.dtstack.chunjun.util.DataSyncFactoryUtil.discoverDdlHandler(DataSyncFactoryUtil.java:158)
	... 4 more
```

**启动命令**

```
sh bin/chunjun-local.sh -job chunjun-examples/json/stream/stream.json
```

**启动错误日志和脚本详见**

![微信截图_20221027101652](https://user-images.githubusercontent.com/64626797/198175287-087292c5-1bea-4039-8cf2-37ccb919db47.png)
[执行脚本和文件.zip](https://github.com/DTStack/chunjun/files/9875162/default.zip)

> 期望大佬给看下

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cdma-git** [comment]
在git上下载最新的release版本包之后，问题得以解决
