### ISSUE TITLE
[Question] oraclecdc到MySQL，已经获取到数据了，还提示表不存在

### ISSUE THREAD

**Issue by hemingqing** [DTStack/chunjun#1481]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

json文件配置如下：
```
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@192.168.10.189:1521:helowin",
            "username": "system",
            "password": "system",
            "supportAutoAddLog": false,
            "table": ["TEST.T_CDC_TEST3"],
            "cat": "UPDATE,INSERT,DELETE",
            "split":true,
            "readPosition": "CURRENT",
            "queryTimeout": 3000
          },
          "name": "oraclelogminerreader"
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "root",
            "password": "",
            "connection": [
              {
                "jdbcUrl": "jdbc:mysql://192.168.10.128:3306/aaa?useSSL=false&allowPublicKeyRetrieval=true",
                "table": [
                  "t_cdc_test"
                ]
              }
            ],
            "writeMode": "insert",
            "column": [
              {
                "name": "id",
                "type": "int"
              },
              {
                "name": "task_name",
                "type": "string"
              },
              {
                "name": "task_info",
                "type": "string"
              },
              {
                "name": "collect_table",
                "type": "string"
              }
            ]
          }
        }
      }
    ],
     "setting": {
      "errorLimit": {
        "record": 100
      },
      "speed": {
        "bytes": 0,
        "channel": 1,
        "readerChannel": 1,
        "writerChannel": 1
      }
    }
  }
}
```
![微信图片_20230110104416](https://user-images.githubusercontent.com/122013759/211450302-a4d5f48f-1f59-4f2f-ba1c-7ef9f17b44d7.png)
![微信图片_20230110104608](https://user-images.githubusercontent.com/122013759/211450311-29b369a5-5036-4354-94ac-db68393b8f18.png)
![微信图片_20230110104613](https://user-images.githubusercontent.com/122013759/211450313-ddc4cdf3-c6eb-48a0-8661-21735aa2bf22.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yinshaohua77** [comment]
没有namemapping


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by waryars** [comment]
有解决了吗？我加了nameMapping问题仍然还没解决呢~

**Comment by waryars** [comment]
> 有解决了吗？我加了nameMapping问题仍然还没解决呢~

报这个错：


shade.core.com.google.common.util.concurrent.UncheckedExecutionException: com.dtstack.chunjun.throwable.ChunJunRuntimeException: error to get meta from [ROMA_LOGMINER.TEST_LOGMR]
	at shade.core.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at shade.core.com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at shade.core.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.getOrCreateFieldNamedPstmt(PreparedStmtProxy.java:154)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.convertToExternal(PreparedStmtProxy.java:125)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeMultipleRecordsInternal(JdbcOutputFormat.java:161)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:496)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: error to get meta from [ROMA_LOGMINER.TEST_LOGMR]
	at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:192)
	at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:137)
	at com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.getColumnMeta(DynamicPreparedStmt.java:176)
	at com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.buildStmt(DynamicPreparedStmt.java:81)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.lambda$getOrCreateFieldNamedPstmt$0(PreparedStmtProxy.java:158)
	at shade.core.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at shade.core.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at shade.core.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at shade.core.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at shade.core.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 14 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'roma_logminer.test_logmr' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:174)
	... 23 more
2023-10-12 16:07:28,814 - 95899 ERROR [timer-data-write-thread-pool-1-thread-1] com.dtstack.chunjun.sink.format.BaseRichOutputFormat:Writing records failed. com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105)
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79)
	at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:140)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:482)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:500)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:500)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by waryars** [comment]
> > 有解决了吗？我加了nameMapping问题仍然还没解决呢~
> 
> 报这个错：
> 
> shade.core.com.google.common.util.concurrent.UncheckedExecutionException: com.dtstack.chunjun.throwable.ChunJunRuntimeException: error to get meta from [ROMA_LOGMINER.TEST_LOGMR] at shade.core.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050) at shade.core.com.google.common.cache.LocalCache.get(LocalCache.java:3952) at shade.core.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871) at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.getOrCreateFieldNamedPstmt(PreparedStmtProxy.java:154) at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.convertToExternal(PreparedStmtProxy.java:125) at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeMultipleRecordsInternal(JdbcOutputFormat.java:161) at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:496) at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:456) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: error to get meta from [ROMA_LOGMINER.TEST_LOGMR] at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:192) at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:137) at com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.getColumnMeta(DynamicPreparedStmt.java:176) at com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.buildStmt(DynamicPreparedStmt.java:81) at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.lambda$getOrCreateFieldNamedPstmt$0(PreparedStmtProxy.java:158) at shade.core.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876) at shade.core.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528) at shade.core.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277) at shade.core.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154) at shade.core.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) ... 14 more Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'roma_logminer.test_logmr' doesn't exist at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) at com.mysql.jdbc.Util.getInstance(Util.java:408) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440) at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381) at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:174) ... 23 more 2023-10-12 16:07:28,814 - 95899 ERROR [timer-data-write-thread-pool-1-thread-1] com.dtstack.chunjun.sink.format.BaseRichOutputFormat:Writing records failed. com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0] at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105) at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79) at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:140) at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:482) at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:500) at java.util.ArrayList.forEach(ArrayList.java:1257) at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:500) at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:456) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by yinshaohua77** [comment]
namemapping写法yaozhuyi



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
