### ISSUE TITLE
chunjun-dist 1.12.8 运行 YarnSession 模式报错

### ISSUE THREAD

**Issue by heartk** [DTStack/chunjun#1549]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

按照 https://dtstack.github.io/chunjun/documents/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B 文档， 运行
```
yarn-seesion -t $CHUNJUN_HOME -d
```

### 报错

```
2023-03-10 14:43:11,718 INFO  org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl [] - Interrupted while waiting for queue
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_311]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_311]
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) ~[?:1.8.0_311]
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:287) [flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
2023-03-10 14:43:11,720 ERROR org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager [] - Fatal error occurred in ResourceManager.
org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Could not start the ResourceManager akka.tcp://flink@hadoop3:33856/user/rpc/resourcemanager_0
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:235) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.rpc.RpcEndpoint.internalCallOnStart(RpcEndpoint.java:181) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor$StoppedState.start(AkkaRpcActor.java:605) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleControlMessage(AkkaRpcActor.java:180) ~[chunjun-ddl-mysql.jar:?]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26) [chunjun-ddl-mysql.jar:?]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21) [chunjun-ddl-mysql.jar:?]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [chunjun-ddl-mysql.jar:?]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [chunjun-ddl-mysql.jar:?]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21) [chunjun-ddl-mysql.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [chunjun-ddl-mysql.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [chunjun-ddl-mysql.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:517) [chunjun-ddl-mysql.jar:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:515) [chunjun-ddl-mysql.jar:?]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225) [chunjun-ddl-mysql.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592) [chunjun-ddl-mysql.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:561) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:225) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [chunjun-ddl-mysql.jar:?]
**Caused by**: org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Cannot initialize resource provider.
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:124) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:247) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:231) ~[chunjun-ddl-mysql.jar:?]
	... 22 more
Caused by: org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Could not start resource manager client.
	at org.apache.flink.yarn.YarnResourceManagerDriver.initializeInternal(YarnResourceManagerDriver.java:181) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.active.AbstractResourceManagerDriver.initialize(AbstractResourceManagerDriver.java:81) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:122) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:247) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:231) ~[chunjun-ddl-mysql.jar:?]
	... 22 more
**Caused by**: java.lang.ClassCastException: org.apache.hadoop.yarn.proto.YarnServiceProtos$RegisterApplicationMasterRequestProto cannot be cast to com.google.protobuf.Message
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:226) ~[chunjun-connector-iceberg.jar:?]
	at com.sun.proxy.$Proxy36.registerApplicationMaster(Unknown Source) ~[?:?]
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationMasterProtocolPBClientImpl.registerApplicationMaster(ApplicationMasterProtocolPBClientImpl.java:107) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191) ~[chunjun-connector-iceberg.jar:?]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[chunjun-connector-iceberg.jar:?]
	at com.sun.proxy.$Proxy37.registerApplicationMaster(Unknown Source) ~[?:?]
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.registerApplicationMaster(AMRMClientImpl.java:223) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.registerApplicationMaster(AMRMClientImpl.java:214) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl.registerApplicationMaster(AMRMClientAsyncImpl.java:139) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at org.apache.flink.yarn.YarnResourceManagerDriver.registerApplicationMaster(YarnResourceManagerDriver.java:495) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.yarn.YarnResourceManagerDriver.initializeInternal(YarnResourceManagerDriver.java:172) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.active.AbstractResourceManagerDriver.initialize(AbstractResourceManagerDriver.java:81) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:122) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:247) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:231) ~[chunjun-ddl-mysql.jar:?]
	... 22 more
2023-03-10 14:43:11,733 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Fatal error occurred in the cluster entrypoint.
org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Could not start the ResourceManager akka.tcp://flink@hadoop3:33856/user/rpc/resourcemanager_0
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:235) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.rpc.RpcEndpoint.internalCallOnStart(RpcEndpoint.java:181) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor$StoppedState.start(AkkaRpcActor.java:605) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleControlMessage(AkkaRpcActor.java:180) ~[chunjun-ddl-mysql.jar:?]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26) [chunjun-ddl-mysql.jar:?]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21) [chunjun-ddl-mysql.jar:?]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [chunjun-ddl-mysql.jar:?]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [chunjun-ddl-mysql.jar:?]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21) [chunjun-ddl-mysql.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [chunjun-ddl-mysql.jar:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [chunjun-ddl-mysql.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:517) [chunjun-ddl-mysql.jar:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:515) [chunjun-ddl-mysql.jar:?]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225) [chunjun-ddl-mysql.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592) [chunjun-ddl-mysql.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:561) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:225) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [chunjun-ddl-mysql.jar:?]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [chunjun-ddl-mysql.jar:?]
Caused by: org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Cannot initialize resource provider.
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:124) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:247) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:231) ~[chunjun-ddl-mysql.jar:?]
	... 22 more
Caused by: org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Could not start resource manager client.
	at org.apache.flink.yarn.YarnResourceManagerDriver.initializeInternal(YarnResourceManagerDriver.java:181) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.active.AbstractResourceManagerDriver.initialize(AbstractResourceManagerDriver.java:81) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:122) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:247) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:231) ~[chunjun-ddl-mysql.jar:?]
	... 22 more
Caused by: java.lang.ClassCastException: org.apache.hadoop.yarn.proto.YarnServiceProtos$RegisterApplicationMasterRequestProto cannot be cast to com.google.protobuf.Message
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:226) ~[chunjun-connector-iceberg.jar:?]
	at com.sun.proxy.$Proxy36.registerApplicationMaster(Unknown Source) ~[?:?]
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationMasterProtocolPBClientImpl.registerApplicationMaster(ApplicationMasterProtocolPBClientImpl.java:107) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191) ~[chunjun-connector-iceberg.jar:?]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[chunjun-connector-iceberg.jar:?]
	at com.sun.proxy.$Proxy37.registerApplicationMaster(Unknown Source) ~[?:?]
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.registerApplicationMaster(AMRMClientImpl.java:223) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.registerApplicationMaster(AMRMClientImpl.java:214) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl.registerApplicationMaster(AMRMClientAsyncImpl.java:139) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at org.apache.flink.yarn.YarnResourceManagerDriver.registerApplicationMaster(YarnResourceManagerDriver.java:495) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.yarn.YarnResourceManagerDriver.initializeInternal(YarnResourceManagerDriver.java:172) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.active.AbstractResourceManagerDriver.initialize(AbstractResourceManagerDriver.java:81) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:122) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:247) ~[chunjun-ddl-mysql.jar:?]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:231) ~[chunjun-ddl-mysql.jar:?]
	... 22 more
```

### What you expected to happen

期望运行成功~

### How to reproduce
Scala 2.11.12
Hadoop **2.7.5**
Flink **1.12.7**-2.11
Zookeeper **3.6.3**
chunjun-dist **1.12.8**

### 分别部署在hadoop1 hadoop2 hadoop3三台服务其上  
![image](https://user-images.githubusercontent.com/8119613/224244294-2299d183-73ce-43de-af02-5553a0abb61e.png)

### zookeeper 状态正常
![image](https://user-images.githubusercontent.com/8119613/224245575-f637b4b8-aebb-4e49-b0d9-4ce1adcbf536.png)

### 环境变量
![image](https://user-images.githubusercontent.com/8119613/224245659-6808600f-bb59-4d6f-a0b9-2242b7158b48.png)

### flink lib 目录
![image](https://user-images.githubusercontent.com/8119613/224244663-e28e8f59-6b74-4e57-b6a0-130c5b140aa3.png)

### $CHUNJUN_HOME 目录
![image](https://user-images.githubusercontent.com/8119613/224244834-230f6b66-f858-4e13-8d13-a8221fd6d2a7.png)

### 不使用 chunjun 直接运行 `yarn-seesion -t` 正常， 运行报错
```
yarn-seesion -t $CHUNJUN_HOME -d
```

### Version

**1.12_release** - 1.12.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChestnutQiang** [comment]
将 flink-shaded-hadoop-2-uber-2.7.5-10.0.jar 这个包从 lib 里面移除去就可以了。这是因为 flink 1.12 已经不需要 hadoop 的 shaded 包了。

**Comment by heartk** [comment]
> 将 flink-shaded-hadoop-2-uber-2.7.5-10.0.jar 这个包从 lib 里面移除去就可以了。这是因为 flink 1.12 已经不需要 hadoop 的 shaded 包了。

非常感谢，已经解决
