### ISSUE TITLE
[Question][chunjun-examples] 执行chunjun-examples/json/stream/stream.json 错误

### ISSUE THREAD

**Issue by liuzx8888** [DTStack/chunjun#1652]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

版本：master 编译
报错一：源代码 LocalTest
![image](https://user-images.githubusercontent.com/10862577/236236542-4353f311-c8fb-4e69-a9e7-a63c1d18b7db.png)

```
2023-05-04 22:14:12,720 INFO  com.dtstack.chunjun.Main - ------------program params-------------------------
2023-05-04 22:14:12,734 INFO  com.dtstack.chunjun.Main - -mode
2023-05-04 22:14:12,734 INFO  com.dtstack.chunjun.Main - localTest
2023-05-04 22:14:12,735 INFO  com.dtstack.chunjun.Main - -jobType
2023-05-04 22:14:12,735 INFO  com.dtstack.chunjun.Main - sync
2023-05-04 22:14:12,735 INFO  com.dtstack.chunjun.Main - -job
2023-05-04 22:14:12,735 INFO  com.dtstack.chunjun.Main - %7B%0A++%22job%22%3A+%7B%0A++++%22content%22%3A+%5B%0A++++++%7B%0A++++++++%22reader%22%3A+%7B%0A++++++++++%22parameter%22%3A+%7B%0A++++++++++++%22column%22%3A+%5B%0A++++++++++++++%7B%0A++++++++++++++++%22name%22%3A+%22id%22%2C%0A++++++++++++++++%22type%22%3A+%22int%22%0A++++++++++++++%7D%2C%0A++++++++++++++%7B%0A++++++++++++++++%22name%22%3A+%22name%22%2C%0A++++++++++++++++%22type%22%3A+%22string%22%0A++++++++++++++%7D%2C%0A++++++++++++++%7B%0A++++++++++++++++%22name%22%3A+%22content%22%2C%0A++++++++++++++++%22type%22%3A+%22string%22%0A++++++++++++++%7D%0A++++++++++++%5D%2C%0A++++++++++++%22sliceRecordCount%22%3A+%5B%0A++++++++++++++%2230%22%0A++++++++++++%5D%2C%0A++++++++++++%22permitsPerSecond%22%3A+1%0A++++++++++%7D%2C%0A++++++++++%22table%22%3A+%7B%0A++++++++++++%22tableName%22%3A+%22sourceTable%22%0A++++++++++%7D%2C%0A++++++++++%22name%22%3A+%22streamreader%22%0A++++++++%7D%2C%0A++++++++%22writer%22%3A+%7B%0A++++++++++%22parameter%22%3A+%7B%0A++++++++++++%22column%22%3A+%5B%0A++++++++++++++%7B%0A++++++++++++++++%22name%22%3A+%22id%22%2C%0A++++++++++++++++%22type%22%3A+%22int%22%0A++++++++++++++%7D%2C%0A++++++++++++++%7B%0A++++++++++++++++%22name%22%3A+%22name%22%2C%0A++++++++++++++++%22type%22%3A+%22string%22%0A++++++++++++++%7D%0A++++++++++++%5D%2C%0A++++++++++++%22print%22%3A+true%0A++++++++++%7D%2C%0A++++++++++%22table%22%3A+%7B%0A++++++++++++%22tableName%22%3A+%22sinkTable%22%0A++++++++++%7D%2C%0A++++++++++%22name%22%3A+%22streamwriter%22%0A++++++++%7D%2C%0A++++++++%22transformer%22%3A+%7B%0A++++++++++%22transformSql%22%3A+%22select+id%2Cname+from+sourceTable+where+CHAR_LENGTH%28name%29+%3C+50+and+CHAR_LENGTH%28content%29+%3C+50%22%0A++++++++%7D%0A++++++%7D%0A++++%5D%2C%0A++++%22setting%22%3A+%7B%0A++++++%22errorLimit%22%3A+%7B%0A++++++++%22record%22%3A+100%0A++++++%7D%2C%0A++++++%22speed%22%3A+%7B%0A++++++++%22bytes%22%3A+0%2C%0A++++++++%22channel%22%3A+1%2C%0A++++++++%22readerChannel%22%3A+1%2C%0A++++++++%22writerChannel%22%3A+1%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D%0A
2023-05-04 22:14:12,735 INFO  com.dtstack.chunjun.Main - {
  "disableGenericTypes": "true"
}
2023-05-04 22:14:12,735 INFO  com.dtstack.chunjun.Main - -------------------------------------------
2023-05-04 22:14:16,113 INFO  com.dtstack.chunjun.Main - Register to table configuration:{table.dynamic-table-options.enabled=true, pipeline.name=Flink_Job}
2023-05-04 22:14:16,192 INFO  com.dtstack.chunjun.util.PluginUtil - ChunJun executionMode: localTest
2023-05-04 22:14:16,192 INFO  com.dtstack.chunjun.util.PluginUtil - ChunJun reset pipeline.jars: []
2023-05-04 22:14:16,201 INFO  com.dtstack.chunjun.classloader.ClassLoaderManager - jarUrl: create ClassLoad successful...
Exception in thread "main" org.apache.flink.table.api.ValidationException: Schema must not contain duplicate column names. Found duplicates: [id, name, content]
	at org.apache.flink.table.catalog.DefaultSchemaResolver.validateDuplicateColumns(DefaultSchemaResolver.java:174)
	at org.apache.flink.table.catalog.DefaultSchemaResolver.resolveColumns(DefaultSchemaResolver.java:98)
	at org.apache.flink.table.catalog.DefaultSchemaResolver.resolve(DefaultSchemaResolver.java:81)
	at org.apache.flink.table.api.Schema.resolve(Schema.java:121)
	at org.apache.flink.table.catalog.CatalogManager.resolveCatalogTable(CatalogManager.java:922)
	at org.apache.flink.table.api.bridge.internal.AbstractStreamTableEnvironmentImpl.fromStreamInternal(AbstractStreamTableEnvironmentImpl.java:145)
	at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.fromDataStream(StreamTableEnvironmentImpl.java:188)
	at com.dtstack.chunjun.Main.syncStreamToTable(Main.java:261)
	at com.dtstack.chunjun.Main.exeSyncJob(Main.java:226)
	at com.dtstack.chunjun.Main.main(Main.java:138)
	at com.dtstack.chunjun.local.test.LocalTest.main(LocalTest.java:173)
Disconnected from the target VM, address: '127.0.0.1:50105', transport: 'socket'
```
报错二：yarn-perjob  模式：
sh ./bin/chunjun-yarn-perjob.sh -job chunjun-examples/json/stream/stream.json
```
Exception in thread "main" org.apache.flink.client.deployment.ClusterDeploymentException: Could not deploy Yarn job cluster.
	at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:504)
	at com.dtstack.chunjun.client.yarn.YarnPerJobClusterClientHelper.submit(YarnPerJobClusterClientHelper.java:89)
	at com.dtstack.chunjun.client.Launcher.main(Launcher.java:87)
Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Schema must not contain duplicate column names. Found duplicates: [id, name, content]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)
	at org.apache.flink.yarn.YarnClusterDescriptor.deployInternal(YarnClusterDescriptor.java:598)
	at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:497)
	... 2 more
Caused by: org.apache.flink.table.api.ValidationException: Schema must not contain duplicate column names. Found duplicates: [id, name, content]
	at org.apache.flink.table.catalog.DefaultSchemaResolver.validateDuplicateColumns(DefaultSchemaResolver.java:174)
	at org.apache.flink.table.catalog.DefaultSchemaResolver.resolveColumns(DefaultSchemaResolver.java:98)
	at org.apache.flink.table.catalog.DefaultSchemaResolver.resolve(DefaultSchemaResolver.java:81)
	at org.apache.flink.table.api.Schema.resolve(Schema.java:121)
	at org.apache.flink.table.catalog.CatalogManager.resolveCatalogTable(CatalogManager.java:922)
	at org.apache.flink.table.api.bridge.internal.AbstractStreamTableEnvironmentImpl.fromStreamInternal(AbstractStreamTableEnvironmentImpl.java:145)
	at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.fromDataStream(StreamTableEnvironmentImpl.java:188)
	at com.dtstack.chunjun.Main.syncStreamToTable(Main.java:261)
	at com.dtstack.chunjun.Main.exeSyncJob(Main.java:226)
	at com.dtstack.chunjun.Main.main(Main.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 8 more

```

报错三：local 模式
sh bin/chunjun-local.sh  -job chunjun-examples/json/stream/stream.json
```
2023-05-04 22:25:42,610 INFO  com.dtstack.chunjun.Main - -------------------------------------------
2023-05-04 22:25:42,712 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.memory.process.size, 1024m
2023-05-04 22:25:42,712 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.bind-host, 0.0.0.0
2023-05-04 22:25:42,713 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.bind-host, 0.0.0.0
2023-05-04 22:25:42,713 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.host, 192.168.1.180
2023-05-04 22:25:42,713 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: parallelism.default, 1
2023-05-04 22:25:42,713 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.execution.failover-strategy, region
2023-05-04 22:25:42,713 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.rpc.address, 192.168.1.180
2023-05-04 22:25:42,714 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.numberOfTaskSlots, 1
2023-05-04 22:25:42,714 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: rest.address, localhost
2023-05-04 22:25:42,714 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.memory.process.size, 1024m
2023-05-04 22:25:42,714 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.rpc.port, 6123
2023-05-04 22:25:42,714 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: rest.bind-address, 0.0.0.0
Exception in thread "main" org.apache.flink.table.api.TableException: Could not instantiate the executor. Make sure a planner module is on the classpath
	at org.apache.flink.table.api.bridge.internal.AbstractStreamTableEnvironmentImpl.lookupExecutor(AbstractStreamTableEnvironmentImpl.java:109)
	at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.create(StreamTableEnvironmentImpl.java:101)
	at org.apache.flink.table.api.bridge.java.StreamTableEnvironment.create(StreamTableEnvironment.java:122)
	at org.apache.flink.table.api.bridge.java.StreamTableEnvironment.create(StreamTableEnvironment.java:94)
	at com.dtstack.chunjun.environment.EnvFactory.createStreamTableEnvironment(EnvFactory.java:86)
	at com.dtstack.chunjun.Main.main(Main.java:129)
	at com.dtstack.chunjun.client.local.LocalClusterClientHelper.submit(LocalClusterClientHelper.java:30)
	at com.dtstack.chunjun.client.Launcher.main(Launcher.java:87)
Caused by: org.apache.flink.table.api.ValidationException: Could not find any factories that implement 'org.apache.flink.table.delegation.ExecutorFactory' in the classpath.
	at org.apache.flink.table.factories.FactoryUtil.discoverFactory(FactoryUtil.java:533)
	at org.apache.flink.table.api.bridge.internal.AbstractStreamTableEnvironmentImpl.lookupExecutor(AbstractStreamTableEnvironmentImpl.java:106)
	... 7 more
[root@hadoop1 chunjun]# sh bin/chunjun-standalone.sh -job chunjun-examples/json/stream/stream.json

```

报错四：standalone 模式
sh bin/chunjun-standalone.sh -job chunjun-examples/json/stream/stream.json
```
2023-05-04 22:27:57,471 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.memory.process.size, 1024m
2023-05-04 22:27:57,472 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.bind-host, 0.0.0.0
2023-05-04 22:27:57,472 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.bind-host, 0.0.0.0
2023-05-04 22:27:57,472 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.host, 192.168.1.180
2023-05-04 22:27:57,472 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: parallelism.default, 1
2023-05-04 22:27:57,473 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.execution.failover-strategy, region
2023-05-04 22:27:57,473 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.rpc.address, 192.168.1.180
2023-05-04 22:27:57,473 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.numberOfTaskSlots, 1
2023-05-04 22:27:57,473 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: rest.address, localhost
2023-05-04 22:27:57,474 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.memory.process.size, 1024m
2023-05-04 22:27:57,474 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.rpc.port, 6123
2023-05-04 22:27:57,474 INFO  org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: rest.bind-address, 0.0.0.0
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Could not instantiate the executor. Make sure a planner module is on the classpath
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)
	at com.dtstack.chunjun.client.util.JobGraphUtil.buildJobGraph(JobGraphUtil.java:61)
	at com.dtstack.chunjun.client.standalone.StandaloneClusterClientHelper.submit(StandaloneClusterClientHelper.java:53)
	at com.dtstack.chunjun.client.Launcher.main(Launcher.java:87)
Caused by: org.apache.flink.table.api.TableException: Could not instantiate the executor. Make sure a planner module is on the classpath
	at org.apache.flink.table.api.bridge.internal.AbstractStreamTableEnvironmentImpl.lookupExecutor(AbstractStreamTableEnvironmentImpl.java:109)
	at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.create(StreamTableEnvironmentImpl.java:101)
	at org.apache.flink.table.api.bridge.java.StreamTableEnvironment.create(StreamTableEnvironment.java:122)
	at org.apache.flink.table.api.bridge.java.StreamTableEnvironment.create(StreamTableEnvironment.java:94)
	at com.dtstack.chunjun.environment.EnvFactory.createStreamTableEnvironment(EnvFactory.java:86)
	at com.dtstack.chunjun.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 7 more
Caused by: org.apache.flink.table.api.ValidationException: Could not find any factories that implement 'org.apache.flink.table.delegation.ExecutorFactory' in the classpath.
	at org.apache.flink.table.factories.FactoryUtil.discoverFactory(FactoryUtil.java:533)
	at org.apache.flink.table.api.bridge.internal.AbstractStreamTableEnvironmentImpl.lookupExecutor(AbstractStreamTableEnvironmentImpl.java:106)
	... 17 more
```

怎么能解决这些错误，chunjun新手

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ll076110** [comment]
standalone模式需要把chunjun-dist和flink-shaded-hadoop-uber包放入flink lib目录里

**Comment by liuzx8888** [comment]
@ll076110  感谢 确实解决了

**Comment by tangdelong** [comment]
@liuzx8888   是怎么解决的。我使用master分支中build.sh进行的打包。打包后解压把chunjun-dist放到了flink/lib下，使用./chunjun-standalone.sh 启动就你说的这个错。

**Comment by tangdelong** [comment]
@ll076110 我使用master分支中build.sh进行的打包。打包后解压把chunjun-dist和下载的flink-shaded-hadoop-3-uber-3.1.1.7.2.9.0-173-9.0.jar 放到了flink/lib下，使用./chunjun-standalone.sh 启动就报楼主说的错误。

**Comment by 715484127** [comment]
local模式报错需要修改chunjun-core的pom文件
<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-table-planner_${scala.binary.version}</artifactId>
			<version>${flink.version}</version>
			<scope>provided</scope>
		</dependency>

加上<scope>provided</scope>   我自己测试是可以运行的
