### ISSUE TITLE
[Bug] [chunjun-connector-jdbc-base] 执行clickhousereader的时候出现空指针

### ISSUE THREAD

**Issue by suckTypeWorker** [DTStack/chunjun#1654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

执行clickhouse->mongodb时,在执行clickhousereader的时候出现如下问题:
```log
2023-05-06 09:28:17,540 - 4058 ERROR [Legacy Source Thread - Source: clickhousesourcefactory -> Sink: mongodbsinkfactory (1/1)#0] com.dtstack.chunjun.source.DtInputFormatSourceFunction:Exception happened, start to close format
java.lang.NullPointerException
	at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.executeQuery(JdbcInputFormat.java:680)
	at com.dtstack.chunjun.connector.clickhouse.source.ClickhouseInputFormat.openInternal(ClickhouseInputFormat.java:55)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.open(BaseRichInputFormat.java:162)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:126)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)
```

### What you expected to happen

应该正常执行结束后输出执行信息

### How to reproduce

chunjun版本为1.12.7
mongodb选择可以正常使用的即可;
clickhouse使用yum安装, 版本为yum自动选择的,sudo yum install clickhouse-server clickhouse-client;
json内容如下:
```json
{
    "job": {
        "content": [
            {
                "reader": {
                    "parameter": {
                        "customSql": "",
                        "startLocation": "0",
                        "polling": true,
                        "increColumn": "",
                        "column": [
                            {
                                "name": "_ID",
                                "type": "String"
                            },
                            {
                                "name": "NAME",
                                "type": "String"
                            },
                            {
                                "name": "TYPE",
                                "type": "String"
                            },
                            {
                                "name": "CREATE_TIME",
                                "type": "DateTime",
                                "format": "yyyy-MM-dd hh:mm:ss"
                            }
                        ],
                        "connection": [
                            {
                                "jdbcUrl": [
                                    "jdbc:clickhouse://192.168.1.xx:8123/mid_data"
                                ],
                                "schema": "mid_data",
                                "type": 1,
                                "table": [
                                    "zt_md_project"
                                ]
                            }
                        ],
                        "username": "default",
                        "password": "root"
                    },
                    "name": "clickhousereader"
                },
                "writer": {
                    "name": "mongodbwriter",
                    "parameter": {
                        "username": "recadmin",
                        "password": "root",
                        "database": "receiver",
                        "hostPorts": "192.168.1.xx:27017",
                        "batchSize": 1,
                        "column": [
                            {
                                "name": "_id",
                                "type": "objectId"
                            },
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "type",
                                "type": "string"
                            },
                            {
                                "name": "create_time",
                                "type": "timestamp",
                                "format": "yyyy-MM-dd hh:mm:ss"
                            }
                        ],
                        "replaceKey": "_id",
                        "writeMode": "insert",
                        "collectionName": "click_mid_data_project"
                    }
                }
            }
        ],
        "setting": {
            "restore": {
                "maxRowNumForCheckpoint": 0,
                "isRestore": false,
                "restoreColumnName": "",
                "restoreColumnIndex": 0
            },
            "errorLimit": {
                "record": 100
            },
            "speed": {
                "bytes": 0,
                "channel": 1
            }
        }
    }
}
```

### Anything else

customSql,  startLocation, polling, increColumn 这些key添加与否不影响异常发生

### Version

1.12_release

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ll076110** [comment]
release已经修复
