### ISSUE TITLE
执行binglog2hive报错

### ISSUE THREAD

**Issue by fuliang0904** [DTStack/chunjun#1669]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

执行binglog2hive是出现错误，连接部上hive是版本问题吗？对应应该是什么版本呢！我的地址我确认过是可以正常连接的，单独jdbc连接没问题！
Caused by: java.lang.RuntimeException: connect：jdbc:hive2://172.18.119.231:10000/edupay failed ：java.lang.RuntimeException: com.dtstack.chunjun.throwable.ChunJunRuntimeException: connection info ：jdbc:hive2://172.18.119.231:10000/edupay error message ：java.sql.SQLException: Could not establish connection to jdbc:hive2://172.18.119.231:10000/: Unsupported Hive2 protocol
at org.apache.hive.jdbc.HiveConnection.openSession(HiveConnection.java:601)
at org.apache.hive.jdbc.HiveConnection.(HiveConnection.java:172)
at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:208)
at com.dtstack.chunjun.connector.hive.util.HiveDbUtil.getHiveConnection(HiveDbUtil.java:257)
at com.dtstack.chunjun.connector.hive.util.HiveDbUtil.connect(HiveDbUtil.java:211)
at com.dtstack.chunjun.connector.hive.util.HiveDbUtil.connect(HiveDbUtil.java:203)
at com.dtstack.chunjun.connector.hive.util.HiveDbUtil1.call(HiveDbUtil.java:96)atcom.dtstack.chunjun.connector.hive.util.HiveDbUtil1.call(HiveDbUtil.java:93)
at com.dtstack.chunjun.util.RetryUtilRetry.call(RetryUtil.java:141)atcom.dtstack.chunjun.util.RetryUtilRetry.doRetry(RetryUtil.java:80)
at com.dtstack.chunjun.util.RetryUtil.executeWithRetry(RetryUtil.java:56)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuliang0904** [comment]
用的是chunjun1.12版本

**Comment by ll076110** [comment]
你的hiv版本应该与chunjun的hive驱动不匹配
