### ISSUE TITLE
[Feature][core]  yarn-per-job模式，当有脏数据报错时可以输出脏数据详细信息

### ISSUE THREAD

**Issue by libailin** [DTStack/chunjun#1670]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

在yarn-per-job模式下，当有脏数据报错时，希望可以在yarn 日志里看到脏数据信息，一目了然，提高排查效率。
虽然flink tm log里可以看到脏数据信息，但是人工时时盯着tm log不太现实。并且在yarn-per-job 模式下，当flink job结束后无法再继续查看tm log，只能通过yarn log 查看报错信息了。

以下是来自yarn log 脏数据报错：

```

2023-05-15 06:23:07,573 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: source[1] -> Sink: sink[2] (1/1) (e2a86ebb5ae28b384e5d3ed706b0b08a_cbc357ccb763df2852fee8c4fc7d55f2_0_0) switched from RUNNING to FAILED on container_e225_1683781588671_102673_01_000002 @ 10.x.x.x (dataPort=22478).
com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:99) ~[chunjun-core.jar:?]
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:73) ~[chunjun-core.jar:?]
	at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:134) ~[chunjun-core.jar:?]
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:490) ~[chunjun-core.jar:?]
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:508) ~[chunjun-core.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_60]
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:508) ~[chunjun-core.jar:?]
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:464) ~[chunjun-core.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_60]
2023-05-15 06:23:07,590 INFO  org.apache.flink.runtime.resourcemanager.slotmanager.DeclarativeSlotManager [] - Clearing resource requirements of job 45a2adfa2d799602896f23f37df79b76
2023-05-15 06:23:07,598 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job Flink_Job (45a2adfa2d799602896f23f37df79b76) switched from state RUNNING to FAILING.

```

最终效果：

![image](https://github.com/DTStack/chunjun/assets/3014381/e59c1b93-f177-4370-8583-64d82049f894)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xikl** [comment]
那请问怎么才能知道这个真正的错误是什么呢，在不升级版本的情况下
