### ISSUE TITLE
[Bug] [core] DtInputFormatSourceFunction run NullPointerException

### ISSUE THREAD

**Issue by libailin** [DTStack/chunjun#1683]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

hdfs -> hdfs 时，报错：

```

2023-05-24 02:19:43,777 INFO  org.apache.flink.runtime.dispatcher.MiniDispatcher           [] - Job d6e302309112751b0b21342c2e423672 reached terminal state FAILED.
org.apache.flink.runtime.JobException: Recovery is suppressed by FailureRateRestartBackoffTimeStrategy(FailureRateRestartBackoffTimeStrategy(failuresIntervalMS=3600000,backoffTimeMS=30000,maxFailuresPerInterval=3)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:139)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:83)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.recordTaskFailure(DefaultScheduler.java:256)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:247)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.onTaskFailed(DefaultScheduler.java:240)
	at org.apache.flink.runtime.scheduler.SchedulerBase.onTaskExecutionStateUpdate(SchedulerBase.java:738)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:715)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:78)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:477)
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:309)
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:307)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:222)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:84)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:168)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at StreamExecCalc$91.processElement_trueFilter1_split2(Unknown Source)
	at StreamExecCalc$91.processElement_trueFilter1(Unknown Source)
	at StreamExecCalc$91.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:418)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:513)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$SwitchingOnClose.collect(StreamSourceContexts.java:103)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:127)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:333)
2023-05-24 02:19:43,783 INFO  org.apache.flink.runtime.dispatcher.MiniDispatcher           [] - Job d6e302309112751b0b21342c2e423672 has been registered for cleanup in the JobResultStore after reaching a terminal state.

```

### What you expected to happen

--

### How to reproduce

```

CREATE TABLE source
(
  `raw_message` string
) WITH (
      'file-type' = 'text',
      'filter-regex' = '',
      'field-delimiter' = '',
      'default-fs' = 'xxx',
      'encoding' = 'utf-8',
      'properties.fs.defaultFS' = 'xxx',
      'properties.dfs.client.failover.proxy.provider.ns' = 'org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider',
      'path' = 'hdfs://namenodefd.test.net:9000/home/test/traceClick/2023-05-23',
      'connector' = 'hdfs-x',
      'scan.parallelism' = '1',
      'properties.hadoop.user.name' = 'test',
      'properties.fs.hdfs.impl' = 'org.apache.hadoop.fs.viewfs.ViewFileSystem',
      'properties.fs.hdfs.impl.disable.cache' = 'true'
      );
CREATE TABLE sink
(
  `uid` string,
  `sign` string,
  `url` string,
  `whereis` string,
  `t` string,
  `ext` string
) WITH (
      'file-type' = 'text',
      'field-delimiter' = '\t',
      'write-mode' = 'overwrite',
      'compress' = 'GZIP',
      'next-check-rows' = '20000',
      'max-file-size' = '1073741824',
      'default-fs' = 'hdfs://namenodefd.test.net:9000',
      'encoding' = 'utf-8',
      'properties.fs.defaultFS' = 'hdfs://namenodefd.test.net:9000',
      'properties.dfs.client.failover.proxy.provider.ns' = 'org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider',
      'path' = 'hdfs://namenodefd.test.net:9000/home/hdp-test/test/pday=20230523',
      'connector' = 'hdfs-x',
      'properties.hadoop.user.name' = 'test',
      'properties.fs.hdfs.impl' = 'org.apache.hadoop.fs.viewfs.ViewFileSystem',
      'properties.fs.hdfs.impl.disable.cache' = 'true',
      'file-name' = '',
      'sink.parallelism' = '1'
      );
 CREATE TEMPORARY VIEW source_1 AS 
 select 
 raw_message 
,REGEXP_EXTRACT(raw_message, '(\?|&|<)uid=([^& \">]*)', 2) as `uid`
,REGEXP_EXTRACT(raw_message, '(\?|&|<)sign=([^& \">]*)', 2) as `sign`
,REGEXP_EXTRACT(raw_message, '(\?|&|<)url=([^& \">]*)', 2) as `url`
,REGEXP_EXTRACT(raw_message, '(\?|&|<)where=([^& \">]*)', 2) as `whereis`
,REGEXP_EXTRACT(raw_message, '&t=([0-9]{13})', 1) as `t`
,REGEXP_EXTRACT(raw_message, '(\?|&|<)ext=([^& \">]*)', 2) as `ext`
 from source S 
 where REGEXP(raw_message, 'play_time') is true 
;
 insert into sink 
 select 
 IF(`uid` is null, 'null_n_a', `uid`) as `uid`,
IF(`sign` is null, 'null_n_a', `sign`) as `sign`,
IF(`url` is null, 'null_n_a', `url`) as `url`,
IF(`whereis` is null, 'null_n_a', `whereis`) as `whereis`,
IF(`t` is null, 'null_n_a', `t`) as `t`,
IF(`ext` is null, 'null_n_a', `ext`) as `ext`
 from source_1; 

```

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by libailin** [comment]
```
// 该写法在 1.16里运行报错，在1.12里可以运行的。
IF(`uid` is null, 'null_n_a', `uid`) as `uid` 

// 在1.16里改成下面写法即可解决
IFNULL(`uid`, 'null_n_a') as `uid`,

```
