### ISSUE TITLE
[Bug] [connector] [oracle] java.sql.SQLSyntaxErrorException: ORA-00904: "FieldName": 标识符无效

### ISSUE THREAD

**Issue by libailin** [DTStack/chunjun#1689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

local模式，当stream->oracle 写入数据时报错

```

DirtyDataEntry(jobId=b0443e8c849263b45a52a2c23a24b74c, jobName=insert-into_default_catalog.default_database.sink_oracle, operatorName=Sink: sink_oracle[2], dirtyContent={"rowKind":"INSERT","arity":3}, errorMessage=com.dtstack.chunjun.throwable.WriteRecordException: 
JdbcOutputFormat [insert-into_default_catalog.default_database.sink_oracle] writeRecord error: when converting field[0] in Row(+I(8391,FMRPJ,196))
java.sql.SQLSyntaxErrorException: ORA-00904: "age": 标识符无效

	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.processWriteException(JdbcOutputFormat.java:418)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:217)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:488)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:509)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:509)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:465)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "age": 标识符无效

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:910)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at com.dtstack.chunjun.connector.jdbc.statement.FieldNamedPreparedStatementImpl.execute(FieldNamedPreparedStatementImpl.java:173)
	at com.dtstack.chunjun.connector.jdbc.sink.wrapper.SimpleStatementWrapper.writeSingleRecord(SimpleStatementWrapper.java:54)
	at com.dtstack.chunjun.connector.jdbc.sink.wrapper.SimpleStatementWrapper.writeSingleRecord(SimpleStatementWrapper.java:29)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:209)
	... 12 more
Caused by: Error : 904, Position : 60, Sql = INSERT INTO "SYSTEM"."FLINKX_ORACLE_TEST"("id", "username", "age") VALUES (:1 , :2 , :3 ), OriginalSql = INSERT INTO "SYSTEM"."FLINKX_ORACLE_TEST"("id", "username", "age") VALUES (?, ?, ?), Error Msg = ORA-00904: "age": 标识符无效

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 29 more
, fieldName=null, createTime=2023-05-29 10:35:27.297)

```

### What you expected to happen

--

### How to reproduce

```

CREATE TABLE source_stream (
    id       bigint,
    username varchar,
    age      int
)WITH(
     'connector' = 'stream-x',
     'number-of-rows' = '1'
     );

CREATE TABLE sink_oracle (
    id    bigint,
    username varchar,
    age    int
) WITH (
    'connector' = 'oracle-x',
    'url' = 'jdbc:oracle:thin:@test.net:1521:orcl',
    'schema' = 'SYSTEM',
    'table-name' = 'FLINKX_ORACLE_TEST',
    'username' = 'xxxx',
    'password' = 'xxxxx',
    'sink.buffer-flush.max-rows' = '1024', 
    'sink.buffer-flush.interval' = '1000', 
    'sink.all-replace' = 'false'
    ,'sink.pre-sql' = 'delete from "SYSTEM"."FLINKX_ORACLE_TEST" where id=3;'
    ,'sink.post-sql' = ''
);

INSERT INTO sink_oracle SELECT * FROM source_stream;

```

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by libailin** [comment]
来自oracle sql  developer 管理执行截图

![image](https://github.com/DTStack/chunjun/assets/3014381/df7de170-77cf-4112-9538-12f46a079346)

**Comment by libailin** [comment]
oracle 字段是区分大小写的。

sql 声明的时候需要与物理表保持一致。

改成这样就可以了
```
CREATE TABLE sink_oracle (
    -- 字段名区分大小写
     ID       bigint,
     USERNAME varchar,
     AGE      int
)
```
