### ISSUE TITLE
[Bug] yarn.provided.lib.dirs参数不生效

### ISSUE THREAD

**Issue by zhourui999** [DTStack/chunjun#1739]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

        // 任务配置参数
        List<String> argsList = new ArrayList<>();
        argsList.add("-mode");
        //        argsList.add("local");
        argsList.add("yarn-per-job");
        argsList.add("-chunjunDistDir");
        argsList.add(chunjunDistDir);
        argsList.add("-flinkLibDir");
        argsList.add("/opt/flink-1.16.1/lib");
        argsList.add("-hadoopConfDir");
        argsList.add("/opt/env");
        argsList.add("-flinkConfDir");
        argsList.add("/opt/flink-1.16.1/conf");

        argsList.add("-confProp");
        // 脏数据相关配置信息
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder
                .append("{")
                .append("\"execution.target\":\"yarn-per-job\"")
                .append(", ")

                //
                .append("\"yarn.provided.lib.dirs\":\"/user/badmin/ruitest/flink-1.16.1/lib\"")
                .append(", ")
                .append("\"yarn.application.queue\":\"root.badmin\"")
                .append("} ");
        argsList.add(stringBuilder.toString());
        // 替换脚本中的值
        // argsList.add("-p");
        // argsList.add("$aa=aaa, $bb=bbb");
        String content = readFile(jobPath);

Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.data.RowData
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_121]
	at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_121]
	at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1475) ~[?:1.8.0_121]
	at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:72) ~[?:1.8.0_121]
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:498) ~[?:1.8.0_121]
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:472) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:472) ~[?:1.8.0_121]
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369) ~[?:1.8.0_121]
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1829) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1829) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[?:1.8.0_121]
	at java.util.HashMap.readObject(HashMap.java:1404) ~[?:1.8.0_121]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]

### What you expected to happen

yarn.provided.lib.dirs参数生效

### How to reproduce

如问题描述中的参数配置

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhourui999** [comment]
远程hdfs文件包没有上传完整
