### ISSUE TITLE
[Bug] [chunjun-metrics] 配置监控，flink启动监控失败

### ISSUE THREAD

**Issue by liuzx8888** [DTStack/chunjun#1762]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

当把chunjun放在flink的lib目录下，启动flink监控报错，[Pushgateway]无法获取到推送的监控信息，把chunjun的chunjun-metrics目录删掉，就能正常的推送消息到 Pushgateway

### What you expected to happen

```
2023-07-17 21:07:38,409 INFO  akka.remote.Remoting                                         [] - Starting remoting
2023-07-17 21:07:38,480 INFO  akka.remote.Remoting                                         [] - Remoting started; listening on addresses :[akka.tcp://flink@192.168.2.183:31079]
2023-07-17 21:07:38,569 INFO  org.apache.flink.runtime.rpc.akka.AkkaRpcServiceUtils        [] - Actor system started at akka.tcp://flink@192.168.2.183:31079
2023-07-17 21:07:38,581 INFO  org.apache.flink.runtime.taskexecutor.TaskManagerRunner      [] - Using working directory: WorkingDirectory(/tmp/tm_192.168.2.183:31079-a913ae)
2023-07-17 21:07:38,601 WARN  org.apache.flink.runtime.metrics.ReporterSetup               [] - Multiple implementations of the same reporter were found in 'lib' and/or 'plugins' directories for org.apache.flink.metrics.prometheu
s.PrometheusReporterFactory. It is recommended to remove redundant reporter JARs to resolve used versions' ambiguity.
2023-07-17 21:07:38,601 WARN  org.apache.flink.runtime.metrics.ReporterSetup               [] - Multiple implementations of the same reporter were found in 'lib' and/or 'plugins' directories for org.apache.flink.metrics.prometheu
s.PrometheusPushGatewayReporterFactory. It is recommended to remove redundant reporter JARs to resolve used versions' ambiguity.
2023-07-17 21:07:38,601 WARN  org.apache.flink.runtime.metrics.ReporterSetup               [] - The reporter configuration of 'promgateway' configures the reporter class, which is a deprecated approach to configure reporters. The
 used reporter might not support this configuration, which would cause errors while loading the reporter. Please configure a factory class instead: 'metrics.reporter.promgateway.factory.class: <factoryClass>' to ensure that the c
onfiguration continues to work with future versions.
2023-07-17 21:07:38,604 ERROR org.apache.flink.runtime.metrics.ReporterSetup               [] - Could not instantiate metrics reporter promgateway. Metrics might not be exposed/reported.
java.lang.InstantiationException: org.apache.flink.metrics.prometheus.PrometheusPushGatewayReporter
	at java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_361]
	at org.apache.flink.runtime.metrics.ReporterSetup.loadViaReflection(ReporterSetup.java:468) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.metrics.ReporterSetup.loadReporter(ReporterSetup.java:410) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.metrics.ReporterSetup.setupReporters(ReporterSetup.java:328) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.metrics.ReporterSetup.fromConfiguration(ReporterSetup.java:209) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.startTaskManagerRunnerServices(TaskManagerRunner.java:223) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.start(TaskManagerRunner.java:288) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManager(TaskManagerRunner.java:481) ~[chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.lambda$runTaskManagerProcessSecurely$5(TaskManagerRunner.java:525) ~[chunjun-restore-mysql.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_361]
	at javax.security.auth.Subject.doAs(Subject.java:422) [?:1.8.0_361]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836) [flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:2.8.3-10.0]
	at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41) [chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManagerProcessSecurely(TaskManagerRunner.java:525) [chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManagerProcessSecurely(TaskManagerRunner.java:505) [chunjun-restore-mysql.jar:?]
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.main(TaskManagerRunner.java:463) [chunjun-restore-mysql.jar:?]
Caused by: java.lang.NoSuchMethodException: org.apache.flink.metrics.prometheus.PrometheusPushGatewayReporter.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_361]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_361]
	... 15 more
2023-07-17 21:07:38,607 INFO  org.apache.flink.runtime.metrics.MetricRegistryImpl          [] - No metrics reporter configured, no metrics will be exposed/reported.
2023-07-17 21:07:38,609 INFO  org.apache.flink.runtime.rpc.akka.AkkaRpcServiceUtils        [] - Trying to start actor system, external address 192.168.2.183:0, bind address 0.0.0.0:0.

```

### How to reproduce

当把chunjun放在flink的lib目录下，启动flink，chunjun 版本master  flink版本 1.16.1

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liuzx8888** [comment]
1.16.1的监控参数跟以前发生了变化，没有仔细查看官方文档
https://nightlies.apache.org/flink/flink-docs-master/zh/docs/deployment/metric_reporters/
```
metrics.reporter.promgateway.factory.class: org.apache.flink.metrics.prometheus.PrometheusPushGatewayReporterFactory
metrics.reporter.promgateway.hostUrl: http://localhost:9091
metrics.reporter.promgateway.jobName: myJob
metrics.reporter.promgateway.randomJobNameSuffix: true
metrics.reporter.promgateway.deleteOnShutdown: false
metrics.reporter.promgateway.groupingKey: k1=v1;k2=v2
metrics.reporter.promgateway.interval: 60 SECONDS
```

metrics.reporter.promgateway.factory.class: org.apache.flink.metrics.prometheus.PrometheusPushGatewayReporterFactory
