### ISSUE TITLE
standalone提交任务运行报错

### ISSUE THREAD

**Issue by blysin** [DTStack/chunjun#1797]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

错误信息：
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
        ... 20 more

### What you expected to happen

正常启动

### How to reproduce

配置：
CREATE TABLE ops_config
(
    id          INT,
    config_key  VARCHAR,
    type        VARCHAR
) WITH (
      'connector' = 'mysql-x',
      'url' = 'jdbc:mysql://192.168.5.133:3306/iot_db_ops',
      'table-name' = 'ops_config',
      'username' = '123',
      'password' = '123'
      );

CREATE TABLE ops_config_copy (
  id INT,
  config_key VARCHAR,
  type VARCHAR
) WITH (
    'connector' = 'stream-x',
    'print' = 'true'
);

insert into ops_config_copy
select *
from ops_config;

启动：sh bin/chunjun-standalone.sh -job job/batch-temp.sql

启动日志：start command: /data/home/blysin/software/jdk1.8.0_381/bin/java -cp /home/blysin/software/chunjun/chunjun-dist/../lib/chunjun-clients.jar:/home/blysin/software/chunjun/chunjun-dist/../lib/* com.dtstack.chunjun.client.Launcher -job job/batch-temp.sql -mode standalone -jobType sync -chunjunDistDir /home/blysin/software/chunjun/chunjun-dist -flinkConfDir /data/home/blysin/software/flink/conf -flinkLibDir /data/home/blysin/software/flink/lib

### Anything else

相同的bug为什么没处理直接关了？#89

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhanghaiyang9999** [comment]
还有没有人维护啊？今天最新版本还是这个错！我是local模式
