### ISSUE TITLE
本地执行mysqlcdcreader到streamwriter，GenericRowData类型无法支持rowSize！

### ISSUE THREAD

**Issue by BaoPiao** [DTStack/chunjun#1888]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

chunjun版本：1.12.8
执行json：
   ```{
  "job": {
    "content": [
      {
        "reader": {
          "name": "mysqlcdcreader",
          "parameter": {
            "username": "***",
            "password": "***",
            "databaseList": [
              "test"
            ],
            "tableList": [
              "test.test1"
            ],
            "host": "****",
            "port": "3306",
            "serverId": 1001
          }
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print": true
          }
        },
        "setting": {
          "speed": {
            "channel": 1,
            "bytes": 0
          }
        }
      }
    ]
  }
}
```
执行报错：
Caused by: java.lang.RuntimeException: not support get rowSize for org.apache.flink.table.data.GenericRowData
	at com.dtstack.chunjun.metrics.RowSizeCalculator$SyncCalculator.getObjectSize(RowSizeCalculator.java:104)
	at com.dtstack.chunjun.metrics.RowSizeCalculator$SyncCalculator.getObjectSize(RowSizeCalculator.java:95)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:296)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:89)
	at com.dtstack.chunjun.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:117)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:54)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
	... 15 more
	
请问还需要增加一个转换吗？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BaoPiao** [comment]
执行环境：本地执行
