### ISSUE TITLE
[Bug] [chunjun-connector-jdbc-base] clickhouse jdbc connection not supported setAutoCommit(false)

### ISSUE THREAD

**Issue by fengjian1129** [DTStack/chunjun#1913]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

When I tried to implement the synchronization function of clickhouse2hive, I found the following error message.
`Caused by: java.sql.SQLFeatureNotSupportedException: Transactions are not supported
		at ru.yandex.clickhouse.ClickHouseConnectionImpl.setAutoCommit(ClickHouseConnectionImpl.java:219)
		at com.dtstack.flinkx.connector.jdbc.source.JdbcInputFormat.openInternal(JdbcInputFormat.java:114)`

I think the problem lies in this piece of code
![image](https://github.com/user-attachments/assets/c0e4eec6-32cb-41b6-b7ee-eed514af4f91)

### What you expected to happen

I hope to control clickhouse-source to skip opening transactions by configuring parameters,for example:
![image](https://github.com/user-attachments/assets/3bc90508-9979-436e-b8e7-93864c6ea2f6)
Because the default value is `"semantic":` "at-least-once"`, it does not affect other synchronization functions

### How to reproduce

When using clickhouse-source to read data, this type of problem may occur

### Anything else

null

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fengjian1129** [comment]
I think this can unify the management of whether transactions are enabled or not, without the need to change setAutoCommit for every chunjun-connector-module
