### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by laixueyong** [DTStack/chunjun#1922]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

报hdfs文件不存在
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
        at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
        at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:811)
        at com.dtstack.chunjun.environment.MyLocalStreamEnvironment.execute(MyLocalStreamEnvironment.java:194)
        at com.dtstack.chunjun.Main.exeSyncJob(Main.java:227)
        at com.dtstack.chunjun.Main.main(Main.java:118)
        at com.dtstack.chunjun.client.local.LocalClusterClientHelper.submit(LocalClusterClientHelper.java:35)
        at com.dtstack.chunjun.client.Launcher.main(Launcher.java:119)
Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
        at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:118)
        at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:80)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:233)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:224)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:215)
        at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:666)
        at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:89)
        at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:446)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)
        at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
        at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
        at akka.actor.ActorCell.invoke(ActorCell.scala:561)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: com.dtstack.chunjun.throwable.ChunJunRuntimeException: error to create hdfs splits
        at com.dtstack.chunjun.connector.hdfs.source.BaseHdfsInputFormat.lambda$createInputSplitsInternal$0(BaseHdfsInputFormat.java:81)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1709)
        at com.dtstack.chunjun.connector.hdfs.source.BaseHdfsInputFormat.createInputSplitsInternal(BaseHdfsInputFormat.java:75)
        at com.dtstack.chunjun.source.format.BaseRichInputFormat.createInputSplits(BaseRichInputFormat.java:128)
        at org.apache.flink.runtime.executiongraph.ExecutionJobVertex.<init>(ExecutionJobVertex.java:247)
        at org.apache.flink.runtime.executiongraph.ExecutionGraph.attachJobGraph(ExecutionGraph.java:866)
        at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:311)
        at org.apache.flink.runtime.scheduler.SchedulerBase.createExecutionGraph(SchedulerBase.java:322)
        at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:276)
        at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:249)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:133)
        at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:111)
        at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:342)
        at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:327)
        at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:95)
        at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:39)
        at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:163)
        at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:86)
        at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:472)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: java.io.FileNotFoundException: File hdfs://nameservice1/user/hive/warehouse/pec.db/px/* does not exist.
        at com.dtstack.chunjun.connector.hdfs.source.HdfsParquetInputFormat.createHdfsSplit(HdfsParquetInputFormat.java:110)
        at com.dtstack.chunjun.connector.hdfs.source.BaseHdfsInputFormat.lambda$createInputSplitsInternal$0(BaseHdfsInputFormat.java:79)
        ... 24 more
Caused by: java.io.FileNotFoundException: File hdfs://nameservice1/user/hive/warehouse/pec.db/px/* does not exist.
        at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:1058)
        at org.apache.hadoop.hdfs.DistributedFileSystem.access$1000(DistributedFileSystem.java:131)
        at org.apache.hadoop.hdfs.DistributedFileSystem$24.doCall(DistributedFileSystem.java:1118)
        at org.apache.hadoop.hdfs.DistributedFileSystem$24.doCall(DistributedFileSystem.java:1115)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:1125)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1868)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1910)
        at com.dtstack.chunjun.connector.hdfs.source.HdfsParquetInputFormat.getAllPartitionPath(HdfsParquetInputFormat.java:90)
        at com.dtstack.chunjun.connector.hdfs.source.HdfsParquetInputFormat.createHdfsSplit(HdfsParquetInputFormat.java:108)
        ... 25 more

        at com.dtstack.chunjun.source.format.BaseRichInputFormat.open(BaseRichInputFormat.java:150)
        at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:126)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laixueyong** [comment]
{
  "job": {
    "content": [
      {
        "reader": {
          "name": "hdfsreader",
          "parameter": {
            "defaultFS": "hdfs://nameservice1",
            "path": "hdfs://nameservice1/user/hive/warehouse/pec.db/px/*",
            "hadoopConfig": {
              "dfs.nameservices": "nameservice1",
              "dfs.ha.namenodes.nameservice1": "namenode67,namenode103",
              "dfs.namenode.rpc-address.nameservice1.namenode67": "cdhtest01:8020",
              "dfs.namenode.rpc-address.nameservice1.namenode103": "cdhtest05:8020",
              "dfs.client.failover.proxy.provider.nameservice1": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider",
              "hadoop.security.authorization": "true",
              "hadoop.security.authentication": "Kerberos",
              "dfs.namenode.kerberos.principal": "hive/cdhtest01@PEC.COM.CN",
              "dfs.namenode.keytab.file": "/home/extimp/lxy_work/datax_format/PARQURT/datax/keytab/hive.keytab",
              "java.security.krb5.conf": "/etc/krb5.conf",
              "principalFile": "/home/extimp/lxy_work/datax_format/PARQURT/datax/keytab/hive.keytab",
              "useLocalFile": true
            },
            "column": [
              {
                "name": "sku",
                "type": "string"
              },
              {
                "name": "sku_name",
                "type": "string"
              },
              {
                "name": "com_name",
                "type": "string"
              }
            ],
            "fileType": "parquet"
          }
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print": true
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": 0
      }
    }
  }
}

**Comment by laixueyong** [comment]
ome/extimp/lxy_work/datax_format/PARQURT/datax/keytab/hive.keytab
2024-09-19 13:50:17.733 [mini-cluster-io-thread-12] INFO  com.dtstack.chunjun.security.KerberosUtil  - parse principal:HTTP/cdhtest01@PEC.COM.CN from keytab:/home/extimp/lxy_work/datax_format/PARQURT/datax/keytab/hive.keytab
2024-09-19 13:50:17.733 [mini-cluster-io-thread-12] INFO  com.dtstack.chunjun.security.KerberosUtil  - will use local file:/etc/krb5.conf
2024-09-19 13:50:18.027 [mini-cluster-io-thread-12] WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-09-19 13:50:18.081 [mini-cluster-io-thread-12] INFO  com.dtstack.chunjun.security.KerberosUtil  - login user:HTTP/cdhtest01@PEC.COM.CN with keytab:/home/extimp/lxy_work/datax_format/PARQURT/datax/keytab/hive.keytab
2024-09-19 13:50:18.243 [mini-cluster-io-thread-12] INFO  com.dtstack.chunjun.connector.hdfs.source.HdfsParquetInputFormat  - user:HTTP, 
2024-09-19 13:50:18.245 [mini-cluster-io-thread-12] INFO  com.dtstack.chunjun.security.KerberosUtil  - will use local file:/home/extimp/lxy_work/datax_format/PARQURT/datax/keytab/hive.keytab
2024-09-19 13:50:18.246 [mini-cluster-io-thread-12] INFO  com.dtstack.chunjun.security.KerberosUtil  - parse principal:HTTP/cdhtest01@PEC.COM.CN from keytab:/home/extimp/lxy_work/datax_format/PARQURT/datax/keytab/hive.keytab
2024-09-19 13:50:18.246 [mini-cluster-io-thread-12] INFO  com.dtstack.chunjun.security.KerberosUtil  - will use local file:/etc/krb5.conf
2024-09-19 13:50:18.264 [mini-cluster-io-thread-12] INFO  com.dtstack.chunjun.security.KerberosUtil  - login user:HTTP/cdhtest01@PEC.COM.CN with keytab:/home/extimp/lxy_work/datax_format/PARQURT/datax/keytab/hive.keytab
2024-09-19 13:50:18.886 [mini-cluster-io-thread-12] WARN  com.dtstack.chunjun.connector.hdfs.source.HdfsParquetInputFormat  - error to create InputSplits

这边也显示我认证成功了

**Comment by laixueyong** [comment]
但是就是说我表的路径不存在
