### ISSUE TITLE
flink1.10 java.lang.IllegalArgumentException: WritingRecordError: error writing record [101] exceed limit [100]

### ISSUE THREAD

**Issue by heluo** [DTStack/chunjun#275]
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: WritingRecordError: error writing record [101] exceed limit [100]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at com.dtstack.flinkx.rdb.outputformat.JdbcOutputFormat.processWriteException(JdbcOutputFormat.java:222)
        at com.dtstack.flinkx.rdb.outputformat.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:210)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:339)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:434)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:448)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:64)
        at com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:110)
        at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:52)
        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:641)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:616)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:596)
        at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:730)
        at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:708)
        at org.apache.flink.streaming.api.operators.StreamSourceContexts$NonTimestampContext.collect(StreamSourceContexts.java:104)
        at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:137)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:196)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.dtstack.flinkx.rdb.outputformat.JdbcOutputFormat.getField(JdbcOutputFormat.java:316)
        at com.dtstack.flinkx.rdb.outputformat.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:205)
        ... 18 more

**Comment by xwuyuan521** [comment]
这个错，是因为你限制错误次数是100，当错误次数超过的时候，就判定这个任务为执行失败了。你应该需要在跑这个任务的时候，看flink日志，看是具体什么错误，然后解决这个错误，就好了。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
