### ISSUE TITLE
flinkx standalone 报无法提交任务

### ISSUE THREAD

**Issue by temptrack** [DTStack/chunjun#290]
flink版本1.8.3
flinkx版本1.8.8
hadoop :hdp 2.7.3
步骤:
1、flink standalone
bin/start-cluster.sh

启动后可以正常访问flink

2、提交flinkx任务

/var2/packages/flinkx/bin/flinkx -mode standalone \
-job /var2/job/demo01.json \
-pluginRoot /var2/packages/flinkx/plugins \
-flinkconf /var2/packages/flink/conf -confProp {\"flink.checkpoint.interval\":60000} 

read the Flink documentation on "Data Types & Serialization" for details of the effect on performance.
17:42:55.490 [main] INFO com.dtstack.flinkx.classloader.ClassLoaderManager - jarUrl:file:/var2/packages/flinkx/plugins/clickhousewriter/flinkx-clickhouse-writer-release_1.8.8.jar_file:/var2/packages/flinkx/plugins/common/flinkx-rdb-core-release_1.8.8.jar_file:/var2/packages/flinkx/plugins/common/flinkx-rdb-reader-release_1.8.8.jar_file:/var2/packages/flinkx/plugins/common/flinkx-rdb-writer-release_1.8.8.jar create ClassLoad successful...
17:42:55.513 [main] WARN org.apache.flink.streaming.api.environment.StreamContextEnvironment - Job was executed in detached mode, the results will be available on completion.
17:42:55.564 [main] INFO org.apache.flink.client.program.rest.RestClusterClient - Submitting job d8d39ae8fd9dcfb910a0801f30598f43 (detached: true).
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not submit job (JobID: d8d39ae8fd9dcfb910a0801f30598f43)
        at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:250)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:483)
        at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:429)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:142)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
        at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:388)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$5(FutureUtils.java:208)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:929)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.runtime.rest.util.RestClientException: [Could not upload job files.]
        at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:389)
        at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$3(RestClient.java:373)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        ... 4 more

**Comment by temptrack** [comment]
demo1.json:
{
  "job": {
    "content": [{
      "reader": {
        "parameter" : {
          "column" : [ {
            "name" : "id",
            "type" : "varchar",
            "key" : "id"
          }, {
            "name" : "US_NOX",
            "type" : "bigint",
            "key" : "US_NOX"
          }, {
            "name" : "DS_NOX",
            "type" : "bigint",
            "key" : "DS_NOX"
          } ],
          "username" : "",
          "password" : "",
          "connection" : [ {
            "jdbcUrl" : [ "jdbc:phoenix:bdp.node17.yaxon.com,bdp.node18.yaxon.com,bdp.node19.yaxon.com:2181" ],
            "table" : [ "VNG6Q_ENGINE_INFO_202010" ]
          } ],
          "where": "id > 1",
          "splitPk": "id",
          "fetchSize": 1000,
          "queryTimeOut": 1000,
          "customSql": " ",
          "polling": true,
          "pollingInterval": 3000,
          "requestAccumulatorInterval": 2
        },
        "name" : "phoenixreader"
      },
      "writer": {
        "name": "clickhousewriter",
        "parameter": {
          "connection": [{
            "jdbcUrl": "jdbc:clickhouse://172.16.10.111:8123/stg",
            "table": [
              "VNG6Q_ENGINE_INFO_202010"
            ]
          }],
          "username": "default",
          "password": "6lYaUiFi",
          "column": [
            {
            "name": "id",
            "type": "varchar",
            "key": "id"
          },
            {
              "name": "US_NOX",
              "type": "INT32",
              "key": "US_NOX"
            },
            {
              "name": "DS_NOX",
              "type": "INT32",
              "key": "DS_NOX"
            }],
          "writeMode": "insert",
          "batchSize": 1024,
          "preSql": [],
          "postSql": []
        }
      }
    }],
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": 0
      },
      "errorLimit": {
        "record": 1
      },
      "restore": {
        "maxRowNumForCheckpoint": 0,
        "isRestore": false,
        "restoreColumnName": "",
        "restoreColumnIndex": 0
      },
      "log" : {
        "isLogger": false,
        "level" : "debug",
        "path" : "",
        "pattern":""
      }
    }
  }
}

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
