### ISSUE TITLE
在hdfs 3.1.1集群上，使用hivewriter,按orc格式写入数据，报Unrecognized Hadoop major version number: 3.1.1

### ISSUE THREAD

**Issue by gitriver** [DTStack/chunjun#316]
Caused by: java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.1.1
        at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:169)
        at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:134)
        at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:95)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:354)
        ... 28 more

全部堆栈信息：
java.lang.ExceptionInInitializerError: null
        at org.apache.hadoop.hive.ql.io.orc.MemoryManager.<init>(MemoryManager.java:83)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile.getMemoryManager(OrcFile.java:482)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile.access$000(OrcFile.java:34)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile$WriterOptions.<init>(OrcFile.java:262)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile.writerOptions(OrcFile.java:418)
        at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat.getOptions(OrcOutputFormat.java:134)
        at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat.getRecordWriter(OrcOutputFormat.java:180)
        at com.dtstack.flinkx.hdfs.writer.HdfsOrcOutputFormat.nextBlock(HdfsOrcOutputFormat.java:144)
        at com.dtstack.flinkx.outputformat.BaseFileOutputFormat.openInternal(BaseFileOutputFormat.java:106)
        at com.dtstack.flinkx.hdfs.writer.BaseHdfsOutputFormat.openInternal(BaseHdfsOutputFormat.java:89)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.open(BaseRichOutputFormat.java:232)
        at com.dtstack.flinkx.hive.writer.HiveOutputFormat.createHdfsOutputFormat(HiveOutputFormat.java:296)
        at com.dtstack.flinkx.hive.writer.HiveOutputFormat.getHdfsOutputFormat(HiveOutputFormat.java:276)
        at com.dtstack.flinkx.hive.writer.HiveOutputFormat.writeRecord(HiveOutputFormat.java:220)
        at com.dtstack.flinkx.hive.writer.HiveOutputFormat.writeRecord(HiveOutputFormat.java:53)
        at com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:110)
        at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:52)
        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
        at org.apache.flink.streaming.api.operators.StreamSourceContexts$NonTimestampContext.collect(StreamSourceContexts.java:104)
        at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:139)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:213)
Caused by: java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.1.1
        at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:169)
        at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:134)
        at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:95)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:354)
        ... 28 common frames omitted
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
        at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:147)
        at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:677)
        at com.dtstack.flink.api.java.MyLocalStreamEnvironment.execute(MyLocalStreamEnvironment.java:153)
        at com.dtstack.flinkx.Main.main(Main.java:141)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:91)
Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
        at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:116)
        at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:78)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:192)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:185)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:179)
        at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:590)
        at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:384)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:286)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:201)
        at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:74)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:154)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
        at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
        at akka.actor.ActorCell.invoke(ActorCell.scala:561)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ExceptionInInitializerError
        at org.apache.hadoop.hive.ql.io.orc.MemoryManager.<init>(MemoryManager.java:83)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile.getMemoryManager(OrcFile.java:482)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile.access$000(OrcFile.java:34)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile$WriterOptions.<init>(OrcFile.java:262)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile.writerOptions(OrcFile.java:418)
        at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat.getOptions(OrcOutputFormat.java:134)
        at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat.getRecordWriter(OrcOutputFormat.java:180)
        at com.dtstack.flinkx.hdfs.writer.HdfsOrcOutputFormat.nextBlock(HdfsOrcOutputFormat.java:144)
        at com.dtstack.flinkx.outputformat.BaseFileOutputFormat.openInternal(BaseFileOutputFormat.java:106)
        at com.dtstack.flinkx.hdfs.writer.BaseHdfsOutputFormat.openInternal(BaseHdfsOutputFormat.java:89)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.open(BaseRichOutputFormat.java:232)
        at com.dtstack.flinkx.hive.writer.HiveOutputFormat.createHdfsOutputFormat(HiveOutputFormat.java:296)
        at com.dtstack.flinkx.hive.writer.HiveOutputFormat.getHdfsOutputFormat(HiveOutputFormat.java:276)
        at com.dtstack.flinkx.hive.writer.HiveOutputFormat.writeRecord(HiveOutputFormat.java:220)
        at com.dtstack.flinkx.hive.writer.HiveOutputFormat.writeRecord(HiveOutputFormat.java:53)
        at com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:110)
        at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:52)
        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
        at org.apache.flink.streaming.api.operators.StreamSourceContexts$NonTimestampContext.collect(StreamSourceContexts.java:104)
        at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:139)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:213)
Caused by: java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.1.1
        at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:169)
        at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:134)
        at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:95)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:354)
        ... 28 more

**Comment by kanata163** [comment]
FlinkX目前还没有去适配Hadoop3.x，可能存在一些问题

**Comment by 1069355234** [comment]
@kanata163 目前用的1.12-beta版本，也还是会报这个问题，请问现在还是没支持hadoop 3.x吗？用的是cdh版本的hadoop 3.0.0-cdh6.2.0

**Comment by pomelolee** [comment]
@kanata163  用1.12版本，启用local模式都可以正常写入 hadoop3.0，用yarn-per-job启动 也会报上面的错

**Comment by pomelolee** [comment]
已经解决
1.编译更改 hadoop版本为3.0.0
2.更改hive的版本为2.1.0 （flinkx-connector-hive）
3.移除flink lib下的 flink-shaded-hadoop-2-uber-3.0.0-cdh6.3.1-10.0.jar
可以用yarn-per-job 正常提交和跑数据了

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
