### ISSUE TITLE
Error registering AppInfo mbean

### ISSUE THREAD

**Issue by jlon** [DTStack/chunjun#324]
分支：1.11
异常：
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=consumer-1
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:62)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:773)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:635)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:617)
        at com.dtstack.flinkx.kafka.client.KafkaClient.<init>(KafkaClient.java:75)
        at com.dtstack.flinkx.kafka.client.KafkaConsumer.createClient(KafkaConsumer.java:45)
        at com.dtstack.flinkx.kafkabase.format.KafkaBaseInputFormat.openInternal(KafkaBaseInputFormat.java:99)
        at com.dtstack.flinkx.inputformat.BaseRichInputFormat.open(BaseRichInputFormat.java:171)
        at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:124)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:213)

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
