### ISSUE TITLE
binlog同步至Kudu时报错not support type of class java.util.HashMap convert to Integer.

### ISSUE THREAD

**Issue by roohom** [DTStack/chunjun#333]
在本地编译并提交到Flink On Yarn 使用yarnPer模式提交任务，目的是使用FlinkX读取MySQL的binlog然后使用Kuduwriter实时同步写入到Kudu，MySQL中只是简单的字段id(int)和name(string)，当提交运行之后，我尝试在MySQL中插入一条数据，查看Kudu并没有成功写入，查看日志反而报了如下错误:

 Source: binlogreader -> Sink: kuduwriter (1/1)hread] com.dtstack.flinkx.kudu.writer.K
uduOutputFormat.writeData(KuduOutputFormat.java:164)evel com.dtstack.flinkx.kudu.writer.KuduOutputFormat.writeData(KuduOutputFormat.j
ava:164)ogger{60}  - Write data error, index = 0, row = {schema=cat, after_name=dog, after_id=31, type=INSERT, table=apple, ts=676443
6349224357888}, e = java.lang.RuntimeException: not support type of class java.util.HashMap convert to Integer.
        at com.dtstack.flinkx.util.ValueUtil.getIntegerVal(ValueUtil.java:97)
        at com.dtstack.flinkx.kudu.writer.KuduOutputFormat.writeData(KuduOutputFormat.java:136)
        at com.dtstack.flinkx.kudu.writer.KuduOutputFormat.writeSingleRecordInternal(KuduOutputFormat.java:98)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:342)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:447)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:66)
        at com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:110)

望得到解答

**Comment by lvyanquan** [comment]
参考这个使用文档 https://github.com/DTStack/flinkx/blob/1.10_release/docs/realTime/reader/binlogreader.md
我们目前从binlog解析后的数据保存了变更前后的信息，并不是同离线mysql那样可以直接向下游写入的，现在向下游写入还需要根据pavingData设值来建表。像你这种直接向下游传递的方式还在设计实现中，需要等待之后的版本了。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
