### ISSUE TITLE
NoClassDefFoundError org/apache/commons/lang/StringUtils

### ISSUE THREAD

**Issue by szs122** [DTStack/chunjun#345]
Flink 1.11 standlone 模式

java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at com.dtstack.flinkx.util.TelnetUtil.telnet(TelnetUtil.java:80)
	at com.dtstack.flinkx.rdb.util.DbUtil.getConnectionInternal(DbUtil.java:118)
	at com.dtstack.flinkx.rdb.util.DbUtil.getConnection(DbUtil.java:146)
	at com.dtstack.flinkx.rdb.outputformat.JdbcOutputFormat.openInternal(JdbcOutputFormat.java:153)
	at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.open(BaseRichOutputFormat.java:232)
	at com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction.open(DtOutputFormatSinkFunction.java:88)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:291)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$0(StreamTask.java:473)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:469)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:522)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:61)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 17 more

**Comment by ChrisLiu47937** [comment]
我也遇到类似问题，jar包里我看了下缺失没有相关的包。
我在core的pom文件里加了三个依赖。        
<dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>
        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
            <version>3.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.4</version>
        </dependency>

并且把artifactSet加上了org.apache.commons的包，发现好像可以了。
<artifactSet>
      <includes>
          <include>com.google.guava:*</include>
          <include>com.google.code.gson:*</include>
          <include>ch.qos.logback:*</include>
          <include>org.slf4j:*</include>
          <include>org.apache.httpcomponents:*</include>
          <include>io.prometheus:*</include>
          <include>org.apache.avro:*</include>
          <include>com.fasterxml.jackson.core:*</include>
          <include>commons-*:*</include>
          <include>org.apache.commons:*</include>
      </includes>
  </artifactSet>

我猜想是不是flink在yarn上跑的时候，这些jar包是yarn提供的，但是standalone并没有。
maven的shade插件好像也不会打包循环依赖。
仅供参考，不知道这样改对其他模式有没有影响。

**Comment by baoziaichiyu** [comment]
standalone模式 flinkx-clients-master.jar   放入flink下的lib中。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
