### ISSUE TITLE
1.11_release kafka reader error

### ISSUE THREAD

**Issue by baiwx-sh** [DTStack/chunjun#372]
15:32:07.940 [flink-akka.actor.default-dispatcher-14] INFO org.apache.flink.runtime.executiongraph.ExecutionGraph - Source: kafka11reader -> Sink: mysqlwriter (1/1) (c3aec8ec7aff990837228fb034991933) switched from RUNNING to FAILED on org.apache.flink.runtime.jobmaster.slotpool.SingleLogicalSlot@7a67ebf7.
java.lang.ClassCastException: org.apache.flink.core.io.GenericInputSplit cannot be cast to com.dtstack.flinkx.kafkabase.KafkaInputSplit
	at com.dtstack.flinkx.kafkabase.format.KafkaBaseInputFormat.openInternal(KafkaBaseInputFormat.java:100)
	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.open(BaseRichInputFormat.java:171)
	at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:124)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:201)

**Comment by zoudaokoulife** [comment]
@baiwx-sh 是否能提供下json 。方便我们定位。另外运行模式也发下。比如perjob, session 还是local.

**Comment by baiwx-sh** [comment]
local mode 和standalone模式结果相同。flink版本是1.11.0。
mysql -> kafka结果正常，kafka -> mysql发生异常。
配置如下，如果有问题麻烦指出：
{"job":{"setting":{"speed":{"channel":1},"restore":{"isRestore":false,"isStream":true}},"content":[{"reader":{"name":"kafka11reader","parameter":{"topic":"a01","codec":"text","mode":"timestamp","timestamp":1616465112400,"consumerSettings":{"bootstrap.servers":"127.0.0.1:9092"},"column":["id"]}},"writer":{"name":"mysqlwriter","parameter":{"writeMode":"update","username":"root","password":"password","column":["id"],"batchSize":100,"connection":[{"jdbcUrl":"jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai","table":["a01"]}]}}}]}}

**Comment by baiwx-sh** [comment]
DtInputFormatSourceFunction.jave, line217: split = provider.getNextInputSplit(getRuntimeContext().getUserCodeClassLoader());返回值类型是GenericInputSplit，从而导致KafkaBaseInputFormat.java中openInternal函数中的语句(KafkaInputSplit) inputSplit类型强转抛出异常。

打印如下：
[Legacy Source Thread - Source: kafka11reader -> Sink: mysqlwriter (1/1)] INFO com.dtstack.flinkx.kafkabase.format.KafkaBaseInputFormat - inputSplit = GenericSplit (0/1)


java.lang.ClassCastException: org.apache.flink.core.io.GenericInputSplit cannot be cast to com.dtstack.flinkx.kafkabase.KafkaInputSplit

**Comment by kanata163** [comment]
重新pull一下代码，这个问题已经解掉了

**Comment by baiwx-sh** [comment]
代码更新后，仍然失败，错误打印有变化。
配置如下：
"reader": {
  "name": "kafkareader",
  "parameter": {
    "topic": "test",
    "codec": "text",
    "mode": "specific-offsets",
    "offset": "partition:0,offset:0",
    "consumerSettings": {
      "bootstrap.servers": "10.64.3.31:9092"
    }
  }
},

错误打印如下：
2021-03-31 15:32:31.676 [Legacy Source Thread - Source: kafkareader -> Sink: mysqlwriter (1/1)] WARN  org.apache.kafka.common.utils.AppInfoParser  - Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=consumer-1
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:62)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:773)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:635)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:617)
        at com.dtstack.flinkx.kafka.client.KafkaClient.<init>(KafkaClient.java:75)
        at com.dtstack.flinkx.kafka.client.KafkaConsumer.createClient(KafkaConsumer.java:45)
        at com.dtstack.flinkx.kafkabase.format.KafkaBaseInputFormat.openInternal(KafkaBaseInputFormat.java:98)
        at com.dtstack.flinkx.inputformat.BaseRichInputFormat.open(BaseRichInputFormat.java:171)
        at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:124)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:213)

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
