### ISSUE TITLE
hadoop 3.2.* 不兼容

### ISSUE THREAD

**Issue by duhanmin** [DTStack/chunjun#392]
`2021-04-21 03:59:38.127 [main] INFO  org.apache.flink.yarn.YarnClusterDescriptor  - Waiting for the cluster to be allocated
2021-04-21 03:59:38.128 [main] INFO  org.apache.flink.yarn.YarnClusterDescriptor  - Deploying cluster, current state ACCEPTED
Exception in thread "main" org.apache.flink.client.deployment.ClusterDeploymentException: Could not deploy Yarn job cluster.
	at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:397)
	at com.dtstack.flinkx.launcher.perJob.PerJobSubmitter.submit(PerJobSubmitter.java:78)
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:111)
Caused by: org.apache.flink.yarn.YarnClusterDescriptor$YarnDeploymentException: The YARN application unexpectedly switched to state FAILED during deployment. `

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
