### ISSUE TITLE
Cannot resolve path parameter (jobid) from value "null".

### ISSUE THREAD

**Issue by StormWangxhu** [DTStack/chunjun#421]
## General Question
数据同步作业不管是mysql到hdfs，还是oracler到hdfs有时作业会报如下错误：
21/06/12 21:08:00 ERROR job.JobAccumulatorsHandler: Exception occurred in REST handler: Bad request, could not parse parameters: Cannot resolve path parameter (jobid) from value "null".
21/06/12 21:08:00 INFO executiongraph.ExecutionGraph: Source: oraclereader (2/4) (c466d7b54024c1558da4ec6ba4b62eb6) switched from RUNNING to FINISHED.
21/06/12 21:08:00 ERROR job.JobAccumulatorsHandler: Could not create the handler request.
org.apache.flink.runtime.rest.handler.HandlerRequestException: Cannot resolve path parameter (jobid) from value "null".
	at org.apache.flink.runtime.rest.handler.HandlerRequest.<init>(HandlerRequest.java:71)
	at org.apache.flink.runtime.rest.handler.AbstractHandler.respondAsLeader(AbstractHandler.java:144)
	at org.apache.flink.runtime.rest.handler.RedirectHandler.lambda$null$0(RedirectHandler.java:142)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)

导致作业同步失败，失败后重试作业才会成功，这里使用的flink-1.7.2,flinkx版本是1.7。暂未升级到1.11，可以麻烦解答下是为什么吗

**Comment by luckyfish0826** [comment]
我们也遇到了。follow一下。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
