### ISSUE TITLE
flinkx不能自动创建目的表 & binlogreader不能与mysqlwriter配合使用？

### ISSUE THREAD

**Issue by Peter-YAN** [DTStack/chunjun#429]
运行local版本，

1. 报如下异常，应该是目的表没有被创建。目的表要手工创建吗？
2. 配置binlogreader和mysqlwriter，通过日志可以实时看到binlogreader打印的ROWDATA信息，但是不能写入目的表。不能交叉使用？

我有配置presql如下：
![image](https://user-images.githubusercontent.com/11254009/123248272-519c5d00-d51a-11eb-98ed-ab729caa07b0.png)

但是没有生效。是遗漏什么配置项吗？

Caused by: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'test-sync.ACCOUNTRELATEDWITHBONDISSUE' doesn't exist
        at com.dtstack.flinkx.rdb.outputformat.JdbcOutputFormat.analyzeTable(JdbcOutputFormat.java:211)
        at com.dtstack.flinkx.rdb.outputformat.JdbcOutputFormat.openInternal(JdbcOutputFormat.java:170)
        at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.open(BaseRichOutputFormat.java:232)
        at com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction.open(DtOutputFormatSinkFunction.java:88)
        at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
        at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.initializeStateAndOpen(StreamTask.java:990)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$0(StreamTask.java:453)
        at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:94)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:448)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:460)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:708)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:533)

**Comment by kanata163** [comment]
除Hivesink插件外，其余插件均不支持自动建表

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
