### ISSUE TITLE
sap hana数据库多个channel运行失败

### ISSUE THREAD

**Issue by dik111** [DTStack/chunjun#481]
flinkx版本:1.11
flink版本:1.11
我看了一下源码，好像是构造分片切分语句引起的？
`
mysql执行 SELECT xx from table  where column MOD n=m; 可以运行,同样的SQL在SAP HANA中运行失败，

SAP HANA需要改成 SELECT xx from table where MOD(column,n) =m; 

`Caused by: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [257] (at 2415): sql syntax error: incorrect syntax near "mod": line 1 col 2415 (at pos 2415)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:191)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42)
	at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:836)
	at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:157)
	at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
	at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4168)
	at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:1655)
	at com.sap.db.jdbc.StatementSapDB._executeDirect(StatementSapDB.java:1657)
	at com.sap.db.jdbc.StatementSapDB._execute(StatementSapDB.java:1637)
	at com.sap.db.jdbc.StatementSapDB._execute(StatementSapDB.java:1577)
	at com.sap.db.jdbc.StatementSapDB._executeQuery(StatementSapDB.java:1533)
	at com.sap.db.jdbc.StatementSapDB.executeQuery(StatementSapDB.java:203)
	at com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat.executeQuery(JdbcInputFormat.java:788)
	at com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat.openInternal(JdbcInputFormat.java:149)
	... 5 more
`

json文件:
`
....
"setting":{
"speed":{
                "channel":"4"
            }
}
`

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
