### ISSUE TITLE
SLF4J 冲突 在lib文件夹中

### ISSUE THREAD

**Issue by marjezhang** [DTStack/chunjun#513]
**SLF4J 冲突 **

**To Reproduce**
1. 正确编译，生产flinkx的插件后
2. 将flinkx-clients-1.12_release.jar 放入到lib 中，以及flinkx放入bin中，还有文件夹flink-dist
3.   执行普通flink run **.jar 提交任务
4.   报错：

**Expected behavior**
# root @ centos-64 in /flink/flink-1.14.0 [23:32:38] 
$ ./bin/flink run ./examples/frauddetection-0.1.jar 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/flink/flink-1.14.0/lib/flinkx-clients-1.12_release.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/flink/flink-1.14.0/lib/log4j-slf4j-impl-2.14.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.NoSuchMethodError: org.apache.flink.runtime.jobgraph.SavepointRestoreSettings.fromConfiguration(Lorg/apache/flink/configuration/ReadableConfig;)Lorg/apache/flink/runtime/jobgraph/SavepointRestoreSettings;
	at org.apache.flink.client.cli.ExecutionConfigAccessor.getSavepointRestoreSettings(ExecutionConfigAccessor.java:94)
	at org.apache.flink.client.deployment.executors.PipelineExecutorUtils.getJobGraph(PipelineExecutorUtils.java:65)
	at org.apache.flink.client.deployment.executors.AbstractSessionClusterExecutor.execute(AbstractSessionClusterExecutor.java:67)
	at org.apache.flink.api.java.ExecutionEnvironment.executeAsync(ExecutionEnvironment.java:1053)
	at org.apache.flink.client.program.ContextEnvironment.executeAsync(ContextEnvironment.java:131)
	at org.apache.flink.client.program.ContextEnvironment.execute(ContextEnvironment.java:70)
	at org.apache.flink.api.java.ExecutionEnvironment.execute(ExecutionEnvironment.java:942)
	at org.apache.flink.api.java.DataSet.collect(DataSet.java:417)
	at org.apache.flink.api.java.DataSet.print(DataSet.java:1748)
	at spendreport.FraudDetectionJob.main(FraudDetectionJob.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1754)
	at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)

**Comment by marjezhang** [comment]
flinkx1.12  要用1.12.5版本flink  新版本flink1.14 有该错误。

**Comment by coverYouth** [comment]
目前有什么方法可以兼容到flink1.14的版本吗？
