### ISSUE TITLE
启动命令中如何加断点续传的参数

### ISSUE THREAD

**Issue by hellochueng** [DTStack/chunjun#520]
## General Question

version 1.12
启动命令如下
./bin/flinkx  \
    -mode standalone  \
    -jobType sync  \
    -job /data/service/flinkxjson/oracle_hdfs_checkpoint.json  \
    -flinkxDistDir /data/service/flinkx/flinkx-dist  \
    -flinkConfDir /data/service/flink-1.12.2/conf \
    -confProp {\"execution.checkpointing.interval\":\"30000\"}
开启断点续传任务后，停止任务
重新启动任务命令中如何添加savepoint path
按文档中
bin/flinkx \
    -mode yarn-per-job \
    -jobType sync \
    -job /data/service/flinkxjson/oracle_hdfs_checkpoint.json \
	-flinkConfDir /data/service/flink-1.12.2/conf \
	-flinkLibDir /data/service/flink-1.12.2/lib \
	-flinkxDistDir flinkx-dist \
	-hadoopConfDir /etc/hadoop/conf
    -confProp {\"flink.checkpoint.interval\":30000} \
    -queue default \
    -s hdfs://ns/flink180/checkpoints/metadata/10c4c972de4240c717e482d6c1b4d7bf/chk-1
-s不可识别
./bin/flinkx  \
    -mode standalone  \
    -jobType sync  \
    -job /data/service/flinkxjson/oracle_hdfs_checkpoint.json  \
    -flinkxDistDir /data/service/flinkx/flinkx-dist  \
    -flinkConfDir /data/service/flink-1.12.2/conf \
    -confProp {\"execution.savepoint.path\":\"hdfs://idc-bigdata-185-56.jdy.kd.internal:8020/flink/checkpoints/c25d49579f591aa7c43db68b61152a75/chk-2\",\"execution.checkpointing.interval\":\"30000\"}
加在confProp中会抛出gson的异常
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:899)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)
        at com.dtstack.flinkx.util.PropertiesUtil.confToMap(PropertiesUtil.java:67)
        at com.dtstack.flinkx.options.Options.loadFlinkConfiguration(Options.java:85)
        at com.dtstack.flinkx.client.standalone.StandaloneClusterClientHelper.submit(StandaloneClusterClientHelper.java:52)
        at com.dtstack.flinkx.client.Launcher.main(Launcher.java:126)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        ... 7 more
官方文档没人去维护吗，公司要解散了吗

**Comment by larryju** [comment]
-confProp 参数改成字符串
