### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: shade.core.com.google.common.collect.Sets

### ISSUE THREAD

**Issue by whhpc19891120** [DTStack/chunjun#522]
restapi_stream connector

"C:\Program Files\Java\jdk1.8.0_181\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:62711,suspend=y,server=n -javaagent:C:\Users\hanpc\AppData\Local\JetBrains\IntelliJIdea2020.2\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath D:\Temp\classpath639625993.jar com.dtstack.flinkx.local.test.LocalTest
Connected to the target VM, address: '127.0.0.1:62711', transport: 'socket'
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/install/mvn_repository/org/slf4j/slf4j-log4j12/1.7.30/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/install/mvn_repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2021-10-19 16:47:31,528 - 0    WARN  [main] com.dtstack.flinkx.local.test.LocalTest:-----
2021-10-19 16:47:34,946 - 3418 INFO  [main] com.dtstack.flinkx.Main:------------program params-------------------------
2021-10-19 16:47:35,022 - 3494 INFO  [main] com.dtstack.flinkx.Main:-mode
2021-10-19 16:47:35,022 - 3494 INFO  [main] com.dtstack.flinkx.Main:local
2021-10-19 16:47:35,025 - 3497 INFO  [main] com.dtstack.flinkx.Main:-jobType
2021-10-19 16:47:35,026 - 3498 INFO  [main] com.dtstack.flinkx.Main:sql
2021-10-19 16:47:35,026 - 3498 INFO  [main] com.dtstack.flinkx.Main:-job
2021-10-19 16:47:35,026 - 3498 INFO  [main] com.dtstack.flinkx.Main:CREATE+TABLE+source%0D%0A%28%0D%0A++++id+++++++++++++int%2C%0D%0A++++name+++++++++++varchar%0D%0A%29+WITH+%28%0D%0A++++++%27connector%27+%3D+%27restapi-x%27%0D%0A++++++%2C%27url%27+%3D+%27http%3A%2F%2Fdev.insight.dtstack.cn%2Fapi%2Fstreamapp%2Fservice%2FstreamCatalogue%2FgetCatalogue%27%0D%0A++++++%2C%27intervalTime%27%3D+%273000%27%0D%0A+++++++%2C%27requestMode%27%3D%27post%27%0D%0A++++++++%2C%27decode%27%3D+%27json%27%0D%0A++++++++%2C%27body%27%3D+%27%5B%0D%0A++++++++++++++%7B%0D%0A++++++++++++++%22key%22%3A+%22catalogueType%22%2C%0D%0A++++++++++++++%22value%22%3A+%22TaskDevelop%22%2C%0D%0A++++++++++++++%22type%22%3A+%22String%22%0D%0A++++++++++++++%7D%2C%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22key%22%3A+%22nodePid%22%2C%0D%0A++++++++++++++++%22value%22%3A+75%2C%0D%0A++++++++++++++++%22type%22%3A+%22int%22%0D%0A++++++++++++++%7D%2C%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22key%22%3A+%22isGetFile%22%2C%0D%0A++++++++++++++++%22value%22%3A+true%2C%0D%0A++++++++++++++++%22type%22%3A+%22boolean%22%0D%0A++++++++++++++%7D%0D%0A++++++++++++%5D%27%0D%0A++++++++%2C%27header%27%3D%27%5B%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22key%22%3A+%22Cookie%22%2C%0D%0A++++++++++++++++%22value%22%3A+%22experimentation_subject_id%3DImZhODEyZGQ4LTllZDItNGUyZi1iZGVjLWZjOGMyNzQxNDk3NSI%3D--d51083bdcc50a5c9140cad574678f156d2bd6ff1%3B+dt_language%3Dzh%3B+sysLoginType%3D%7B%5C%22sysId%5C%22%3A1%2C%5C%22sysType%5C%22%3A0%7D%3B+dt_user_id%3D1%3B+dt_username%3Dadmin%40dtstack.com%3B+dt_can_redirect%3Dfalse%3B+dt_cookie_time%3D2021-06-20%2B17%3A59%3A08%3B+dt_token%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0ZW5hbnRfaWQiOiIxIiwidXNlcl9pZCI6IjEiLCJ1c2VyX25hbWUiOiJhZG1pbkBkdHN0YWNrLmNvbSIsImV4cCI6MTYzOTEzMDIzNywiaWF0IjoxNjA4MDI2MjUyfQ.6cuG5Zuo0GzBtnfEPWDyFqAac1Umh3HbxycbEN5fGsg%3B+dt_tenant_id%3D1%3B+dt_tenant_name%3DDTStack%E7%A7%9F%E6%88%B7%3B+dt_is_tenant_admin%3Dtrue%3B+dt_is_tenant_creator%3Dfalse%3B+dt_product_code%3DRDOS%3B+JSESSIONID%3D56C0AB7D249B1076A14CA305E871DAE8%3B+DT_SESSION_ID%3Da761788a-e504-4d51-b1b0-128f9f8865e3%22%0D%0A++++++++++++++%7D%2C%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22key%22%3A+%22Content-Type%22%2C%0D%0A++++++++++++++++%22value%22%3A+%22text%2Fplain%3Bcharset%3DUTF-8%22%0D%0A++++++++++++++%7D%0D%0A++++++++++++%5D%27%0D%0A++++++++++++%2C%27column%27%3D%27%5B%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22name%22%3A+%22data.id%22%2C%0D%0A++++++++++++++++%22type%22%3A+%22int%22%0D%0A++++++++++++++%7D%2C%0D%0A++++++++++++++%7B%0D%0A++++++++++++++++%22name%22%3A+%22data.name%22%2C%0D%0A++++++++++++++++%22type%22%3A+%22string%22%0D%0A++++++++++++++%7D%0D%0A++++++++++++%5D%27%0D%0A++++++%29%3B%0D%0A%0D%0ACREATE+TABLE+sink%0D%0A%28%0D%0A++++id+++++++++++++int%2C%0D%0A++++name++++++varchar%0D%0A%29+WITH+%28%0D%0A++++++%27connector%27+%3D+%27stream-x%27%0D%0A++++++%29%3B%0D%0A%0D%0Ainsert+into+sink%0D%0Aselect+*%0D%0Afrom+source+u%3B%0D%0A
2021-10-19 16:47:35,026 - 3498 INFO  [main] com.dtstack.flinkx.Main:-jobName
2021-10-19 16:47:35,026 - 3498 INFO  [main] com.dtstack.flinkx.Main:flinkStreamSQLLocalTest
2021-10-19 16:47:35,026 - 3498 INFO  [main] com.dtstack.flinkx.Main:-flinkxDistDir
2021-10-19 16:47:35,026 - 3498 INFO  [main] com.dtstack.flinkx.Main:E:\git\flinkx\flinkx-dist
2021-10-19 16:47:35,027 - 3499 INFO  [main] com.dtstack.flinkx.Main:-remoteFlinkxDistDir
2021-10-19 16:47:35,027 - 3499 INFO  [main] com.dtstack.flinkx.Main:E:\git\flinkx\flinkx-dist
2021-10-19 16:47:35,027 - 3499 INFO  [main] com.dtstack.flinkx.Main:-pluginLoadMode
2021-10-19 16:47:35,027 - 3499 INFO  [main] com.dtstack.flinkx.Main:LocalTest
2021-10-19 16:47:35,029 - 3501 INFO  [main] com.dtstack.flinkx.Main:-flinkConfDir
2021-10-19 16:47:35,029 - 3501 INFO  [main] com.dtstack.flinkx.Main:E:\git\flinkx
2021-10-19 16:47:35,029 - 3501 INFO  [main] com.dtstack.flinkx.Main:-------------------------------------------
2021-10-19 16:47:35,168 - 3640 INFO  [main] org.apache.flink.configuration.GlobalConfiguration:Loading configuration property: rest.bind-port, 8888
Exception in thread "main" java.lang.NoClassDefFoundError: shade/core/com/google/common/collect/Sets
	at com.dtstack.flinkx.connector.restapi.common.ConstantValue.<clinit>(ConstantValue.java:48)
	at com.dtstack.flinkx.connector.restapi.source.RestapiDynamicTableSource.lambda$getScanRuntimeProvider$0(RestapiDynamicTableSource.java:76)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:459)
	at com.dtstack.flinkx.connector.restapi.source.RestapiDynamicTableSource.getScanRuntimeProvider(RestapiDynamicTableSource.java:76)
	at org.apache.flink.table.planner.sources.DynamicSourceUtils.validateScanSource(DynamicSourceUtils.java:254)
	at org.apache.flink.table.planner.sources.DynamicSourceUtils.prepareDynamicSource(DynamicSourceUtils.java:71)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:101)
	at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:165)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:157)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:902)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:871)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:250)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:564)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:248)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:77)
	at org.apache.flink.table.api.internal.StatementSetImpl.addInsertSql(StatementSetImpl.java:50)
	at com.dtstack.flinkx.sql.parser.InsertStmtParser.execStmt(InsertStmtParser.java:47)
	at com.dtstack.flinkx.sql.parser.AbstractStmtParser.handleStmt(AbstractStmtParser.java:50)
	at com.dtstack.flinkx.sql.parser.AbstractStmtParser.handleStmt(AbstractStmtParser.java:52)
	at com.dtstack.flinkx.sql.parser.AbstractStmtParser.handleStmt(AbstractStmtParser.java:52)
	at com.dtstack.flinkx.sql.parser.SqlParser.lambda$parseSql$1(SqlParser.java:68)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.dtstack.flinkx.sql.parser.SqlParser.parseSql(SqlParser.java:65)
	at com.dtstack.flinkx.Main.exeSqlJob(Main.java:128)
	at com.dtstack.flinkx.Main.main(Main.java:96)
	at com.dtstack.flinkx.local.test.LocalTest.main(LocalTest.java:105)
Caused by: java.lang.ClassNotFoundException: shade.core.com.google.common.collect.Sets
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 52 more
Disconnected from the target VM, address: '127.0.0.1:62711', transport: 'socket'

Process finished with exit code 1

**Comment by whhpc19891120** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好邮件已收到~查阅后会尽快回复~O(∩_∩)O谢谢~
