### ISSUE TITLE
flinkx k8s application develop error --" flinkx FactoryUtil can't overide flink FactoryUtil"

### ISSUE THREAD

**Issue by etdick** [DTStack/chunjun#549]
i use deploy flinkx job to k8s by appliction native pattern
there is error like this " flinkx FactoryUtil can't overide flink FactoryUtil"

=============================
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "com/dtstack/flinkx/util/FactoryHelper"
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
 at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
 at org.apache.flink.table.factories.FactoryUtil.discoverFactory(FactoryUtil.java:271)
 at org.apache.flink.table.factories.FactoryUtil.getDynamicTableFactory(FactoryUtil.java:415)
 at org.apache.flink.table.factories.FactoryUtil.createTableSource(FactoryUtil.java:168)
===========================================

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
