### ISSUE TITLE
mysql读取使用自定义customSql参数时遇到的相关bug

### ISSUE THREAD

**Issue by libailin** [DTStack/chunjun#672]
**Describe the bug**
mysql读取使用自定义customSql参数时，文档上标注了， 当指定了此参数时，connection里指定的table无效，但是程序报错还是要求传入table参数，其实当指定customSql参数时，table应该不需要再传，因为自定义sql有可能有是多表关联查询，只传一个表名显然不对。

**配置json**

```
{
  "job": {
    "content": [{
      "reader": {
        "name": "mysqlreader",
        "parameter": {
          "username": "root",
          "password": "123456",
          "connection": [
            {
              "jdbcUrl": [
                "jdbc:mysql://10.202.254.2:3306/flinkx_test?useunicode=true&characterEncoding=utf8&useSSL=false&useCursorFetch=true"
              ],
              "table": []
            }
          ],
          "customSql": "SELECT a.id,a.username,a.email,b.city from user a LEFT JOIN dim_area b on a.id = b.user_id",
          "column": [
            {
              "name": "id",
              "type": "bigint"
            },
            {
              "name": "username",
              "type": "varchar"
            },
            {
              "name": "email",
              "type": "varchar",
              "notNull" : true
            },
            {
              "name": "city",
              "type": "varchar"
            }
          ]
        }
      },
      "writer": {
        "name": "mysqlwriter",
        "parameter": {
          "username": "root",
          "password": "123456",
          "connection": [
            {
              "jdbcUrl": 
                "jdbc:mysql://10.202.254.2:3306/flinkx_test?useunicode=true&characterEncoding=utf8&useSSL=false"
              ,
              "table": [
                "sea_test"
              ],
              "schema":"flinkx_test"
            }
          ],
          "column": [
            {
              "name": "id",
              "type": "bigint"
            },
            {
              "name": "info",
              "type": "varchar"
            },
            {
              "name": "name",
              "type": "varchar"
            },
            {
              "name": "message",
              "type": "varchar",
              "notNull" : true
            }
          ],
          "preSql": [
            "truncate table seatunnel_test;"
          ],
          "postSql":[],
          "writeMode": "insert"
        }
      }
    }],
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": 0,
        "rebalance": false
      }
    }
  }
}

```

**Expected behavior**

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dtstack.flinkx.local.test.LocalTest.main(LocalTest.java:180)
	... 5 more
Caused by: com.dtstack.flinkx.throwable.FlinkxRuntimeException: java.lang.reflect.InvocationTargetException
	at com.dtstack.flinkx.util.DataSyncFactoryUtil.discoverSource(DataSyncFactoryUtil.java:67)
	at com.dtstack.flinkx.Main.exeSyncJob(Main.java:174)
	at com.dtstack.flinkx.Main.main(Main.java:111)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.dtstack.flinkx.util.DataSyncFactoryUtil.lambda$discoverSource$0(DataSyncFactoryUtil.java:64)
	at com.dtstack.flinkx.classloader.ClassLoaderSupplierCallBack.callbackAndReset(ClassLoaderSupplierCallBack.java:33)
	at com.dtstack.flinkx.classloader.ClassLoaderManager.newInstance(ClassLoaderManager.java:66)
	at com.dtstack.flinkx.util.DataSyncFactoryUtil.discoverSource(DataSyncFactoryUtil.java:57)
	... 12 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.dtstack.flinkx.connector.jdbc.conf.JdbcConf.getTable(JdbcConf.java:125)
	at com.dtstack.flinkx.connector.jdbc.util.JdbcUtil.resetSchemaAndTable(JdbcUtil.java:434)
	at com.dtstack.flinkx.connector.jdbc.source.JdbcSourceFactory.rebuildJdbcConf(JdbcSourceFactory.java:211)
	at com.dtstack.flinkx.connector.jdbc.source.JdbcSourceFactory.<init>(JdbcSourceFactory.java:96)
	at com.dtstack.flinkx.connector.mysql.source.MysqlSourceFactory.<init>(MysqlSourceFactory.java:41)
	... 20 more
```

最新master代码：
4cf9f364ae875ab0b313eb891819ff4fd36a580b

**Comment by libailin** [comment]
其实会引发一系列小bug，己提交pr，麻烦review，

**Comment by libailin** [comment]
最新master代码己解决此问题，
