### ISSUE TITLE
sftp同步报错

### ISSUE THREAD

**Issue by baoziaichiyu** [DTStack/chunjun#716]
![image](https://user-images.githubusercontent.com/39789485/163504525-ac3e067b-ea75-466d-a85b-18d6d20fd87f.png)
csv数据
![image](https://user-images.githubusercontent.com/39789485/163504563-3ea54d30-2dd5-473d-bc7d-bcce91e65d97.png)
这个是格式问题吗

**Comment by baoziaichiyu** [comment]
2022-04-15 09:34:32,349 INFO  com.dtstack.flinkx.connector.ftp.source.FtpInputFormat       [] - [FtpInputFormat] open successfully, 
inputSplit = com.dtstack.flinkx.connector.ftp.source.FtpInputSplit@5bfbba78, 
[FtpConfig]: 
{
  "semantic" : "at-least-once",
  "errorRecord" : 100,
  "checkFormat" : true,
  "parallelism" : 1,
  "flushIntervalMills" : 10000,
  "writeMode" : "APPEND",
  "firstLineHeader" : false,
  "fieldDelimiter" : ",",
  "timeout" : 5000,
  "path" : "/app/sftp/flinkx/source/data.csv",
  "password" : "******",
  "protocol" : "sftp",
  "metricPluginRoot" : "/app/flinkx/flinkx-dist/metrics",
  "host" : "localhost",
  "nextCheckRows" : 5000,
  "isFirstLineHeader" : false,
  "column" : [ {
    "name" : "c_id",
    "type" : "int",
    "index" : 0,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_boolean",
    "type" : "string",
    "index" : 1,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_tinyint",
    "type" : "tinyint",
    "index" : 2,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_smallint",
    "type" : "smallint",
    "index" : 3,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_int",
    "type" : "int",
    "index" : 4,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_bigint",
    "type" : "bigint",
    "index" : 5,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_float",
    "type" : "float",
    "index" : 6,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_double",
    "type" : "double",
    "index" : 7,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_decimal",
    "type" : "decimal",
    "index" : 8,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_string",
    "type" : "string",
    "index" : 9,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_varchar",
    "type" : "varchar",
    "index" : 10,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "c_char",
    "type" : "char",
    "index" : 11,
    "notNull" : false,
    "part" : false
  } ],
  "controlEncoding" : "UTF-8",
  "errorPercentage" : -1,
  "maxFileSize" : 1073741824,
  "encoding" : "utf-8",
  "fieldNameList" : [ ],
  "fromLine" : 1,
  "listHiddenFiles" : true,
  "port" : 22,
  "batchSize" : 1,
  "speedBytes" : 0,
  "metricPluginName" : "prometheus",
  "username" : "root",
  "connectPattern" : "PASV"
} 
2022-04-15 09:34:32,355 ERROR com.dtstack.flinkx.connector.ftp.converter.FtpColumnConverter [] - value [﻿1] convent failed 
2022-04-15 09:34:32,355 ERROR com.dtstack.flinkx.source.DtInputFormatSourceFunction        [] - Exception happened, start to close format
java.lang.NullPointerException: null
	at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:194) ~[blob_p-fde6dadab333f5822d6cb734241377ac320b814c-89b2013a52f6293f247841aa64c9893d:?]
	at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67) ~[blob_p-fde6dadab333f5822d6cb734241377ac320b814c-89b2013a52f6293f247841aa64c9893d:?]
	at com.dtstack.flinkx.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133) [blob_p-fde6dadab333f5822d6cb734241377ac320b814c-89b2013a52f6293f247841aa64c9893d:?]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66) [flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267) [flink-dist_2.11-1.12.7.jar:1.12.7]
2022-04-15 09:34:32,359 INFO  com.dtstack.flinkx.dirty.log.LogDirtyDataCollector           [] - Print consumer closed.
2022-04-15 09:34:42,360 INFO  com.dtstack.flinkx.connector.ftp.source.FtpInputFormat       [] - subtask input close finished
2022-04-15 09:34:42,361 INFO  com.dtstack.flinkx.connector.ftp.sink.FtpOutputFormat        [] - taskNumber[0] close()
2022-04-15 09:34:52,364 INFO  com.dtstack.flinkx.dirty.log.LogDirtyDataCollector           [] - Print consumer closed.
2022-04-15 09:34:52,364 INFO  com.dtstack.flinkx.connector.ftp.sink.FtpOutputFormat        [] - subtask[0}] close() finished
2022-04-15 09:34:52,365 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: ftpsourcefactory -> Sink: ftpsinkfactory (1/1)#0 (8d269eab5f0db4d4d88caa1bf740bb09) switched from RUNNING to FAILED.
java.lang.NullPointerException: null
	at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:194) ~[blob_p-fde6dadab333f5822d6cb734241377ac320b814c-89b2013a52f6293f247841aa64c9893d:?]
	at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67) ~[blob_p-fde6dadab333f5822d6cb734241377ac320b814c-89b2013a52f6293f247841aa64c9893d:?]
	at com.dtstack.flinkx.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133) ~[blob_p-fde6dadab333f5822d6cb734241377ac320b814c-89b2013a52f6293f247841aa64c9893d:?]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267) ~[flink-dist_2.11-1.12.7.jar:1.12.7]
2022-04-15 09:34:52,365 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - Freeing task resources for Source: ftpsourcefactory -> Sink: ftpsinkfactory (1/1)#0 (8d269eab5f0db4d4d88caa1bf740bb09).

**Comment by WTZ468071157** [comment]
能否提交下任务脚本呢？以及当前任务是在哪个分支下的问题呢？

**Comment by baoziaichiyu** [comment]
bin/flinkx -mode standalone  -jobType sync -jobName flink_ftp  -job /app/flinkx/job/ftp_ftp.json -flinkxDistDir /app/flinkx/flinkx-dist -flinkConfDir /app/flink-1.12.7/conf  > /app/flinkx/job-log/1291649838962026.out

**Comment by baoziaichiyu** [comment]
{
  "job":{
    "content":[
      {
        "reader":{
          "parameter":{
            "path":"/app/sftp/flinkx/source/data.csv",
            "protocol":"sftp",
            "port":22,
            "isFirstLineHeader":false,
            "host":"localhost",
            "column":[
              {
                "index":0,
                "type":"int",
                "name": "c_id"
              },
              {
                "index":1,
                "type":"boolean",
                "name": "c_boolean"
              },
              {
                "index":2,
                "type":"tinyint",
                "name": "c_tinyint"
              },
              {
                "index":3,
                "type":"smallint",
                "name": "c_smallint"
              },
              {
                "index":4,
                "type":"int",
                "name": "c_int"
              },
              {
                "index":5,
                "type":"bigint",
                "name": "c_bigint"
              },
              {
                "index":6,
                "type":"float",
                "name": "c_float"
              },
              {
                "index":7,
                "type":"double",
                "name": "c_double"
              },
              {
                "index":8,
                "type":"decimal",
                "name": "c_decimal"
              },
              {
                "index":9,
                "type":"string",
                "name": "c_string"
              },
              {
                "index":10,
                "type":"varchar",
                "name": "c_varchar"
              },
              {
                "index":11,
                "type":"char",
                "name": "c_char"
              }
            
            ],
            "password":"Xingyi2021#$",
            "fieldDelimiter":",",
            "encoding":"utf-8",
            "username":"root"
          },
          "name":"ftpreader"
        },
        "writer":{
          "parameter": {
            "path": "/app/sftp/flinkx/sink",
            "protocol": "sftp",
            "port": 22,
            "writeMode": "append",
            "host": "localhost",
            "column":[
              {
                "index":0,
                "type":"int",
                "name": "c_id"
              },
              {
                "index":1,
                "type":"boolean",
                "name": "c_boolean"
              },
              {
                "index":2,
                "type":"tinyint",
                "name": "c_tinyint"
              },
              {
                "index":3,
                "type":"smallint",
                "name": "c_smallint"
              },
              {
                "index":4,
                "type":"int",
                "name": "c_int"
              },
              {
                "index":5,
                "type":"bigint",
                "name": "c_bigint"
              },
              {
                "index":6,
                "type":"float",
                "name": "c_float"
              },
              {
                "index":7,
                "type":"double",
                "name": "c_double"
              },
              {
                "index":8,
                "type":"decimal",
                "name": "c_decimal"
              },
              {
                "index":9,
                "type":"string",
                "name": "c_string"
              },
              {
                "index":10,
                "type":"varchar",
                "name": "c_varchar"
              },
              {
                "index":11,
                "type":"char",
                "name": "c_char"
              }
             
            ],
            "password": "Xingyi2021#$",
            "fieldDelimiter": ",",
            "encoding": "utf-8",
            "username": "root"
          },
          "name":"ftpwriter"
        }
      }
    ],
    "setting":{
      "restore":{
        "maxRowNumForCheckpoint":0,
        "isRestore":false,
        "restoreColumnName":"",
        "restoreColumnIndex":0
      },
      "errorLimit":{
        "record":100
      },
      "speed":{
        "bytes":0,
        "channel":1
      }
    }
  }
}

**Comment by baoziaichiyu** [comment]
不是是sftp插件BUG吧

**Comment by baoziaichiyu** [comment]
1.12版本
