### ISSUE TITLE
flinkx standalone导入报错

### ISSUE THREAD

**Issue by linbaicome** [DTStack/chunjun#742]
相关组件版本 hive3 hadoop3 flink12.4

同一个json文件 local模式能导入数据
flinkx -job /shell/flinxjson/mysql2hive.json -jobType sync

standalone报错
flinkx  -mode standalone  -jobType sync  -job /shell/flinxjson/mysql2hive.json  -flinkxDistDir  $FLINKX_HOME/flinkx-dist  -flinkConfDir $FLINK_HOME/conf
ob failed during initialization of JobManager
org.apache.flink.runtime.client.JobInitializationException: Could not instantiate JobManager.
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:494)
.....
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Source: mysqlsourcefactory -> Sink: hdfssinkfactory': Loading the input/output formats failed: 
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:239)
.......
	... 4 more
Caused by: java.lang.Exception: Loading the input/output formats failed: 
....	.
	... 16 more
Caused by: java.lang.RuntimeException: Deserializing the input/output formats failed: Lorg/apache/hadoop/fs/FileSystem;
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:69)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initInputOutputformatContainer(InputOutputFormatVertex.java:168)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: Lorg/apache/hadoop/fs/FileSystem;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)

**Comment by linbaicome** [comment]
相关组件版本 hive3 hadoop3 flink12.4

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
