### ISSUE TITLE
standalone模式启动flink，提交flinkx任务，在重启flink后任务未恢复

### ISSUE THREAD

**Issue by codingxmh** [DTStack/chunjun#745]
standalone启动，flink配置如下

state.backend: filesystem
state.checkpoints.dir: file:///data/flink-checkpoints
state.savepoints.dir: file:///data/flink-savepoints

**Comment by codingxmh** [comment]
发现在任务停止的时候会报错，导致任务保存失败

[Legacy Source Thread - Source: sqlservercdcsourcefactory -> Sink: kafkasinkfactory (1/1)#0] ERROR c.d.f.c.sqlservercdc.inputFormat.SqlServerCdcInputFormat  - takeEvent interrupted error:java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684)
	at com.dtstack.flinkx.connector.sqlservercdc.inputFormat.SqlServerCdcInputFormat.nextRecordInternal(SqlServerCdcInputFormat.java:127)
	at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:192)
	at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67)
	at com.dtstack.flinkx.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
