### ISSUE TITLE
oracle oracle-x 数据库varchar 报错

### ISSUE THREAD

**Issue by lidong2021** [DTStack/chunjun#749]
oracle表
create table a (
id number(12) primary key,
uname varchar(20)
);

flinkxsql
CREATE TABLE source
(
    ID                decimal(38,0),
    UNAME             string
) WITH (
      'connector' = 'oracle-x',
      'url' = 'jdbc:oracle:thin:@localhost:1521:orcl',
      'table-name' = 'A',
      'username' = 'oracle',
      'password' = 'oracle',
      'scan.fetch-size' = '1',
      'scan.query-timeout' = '10'
      );

CREATE TABLE sink
(
    ID             decimal(38,0),
    UNAME          string
) WITH (
     'connector' = 'stream-x',
     'print' = 'true'
      );

insert into sink
select *
from source;

报错
2022-04-26 13:59:14.558 [Legacy Source Thread - Source: TableSourceScan(table=[[default_catalog, default_database, source]], fields=[ID, UNAME]) -> Sink: Sink(table=[default_catalog.default_database.sink], fields=[ID, UNAME]) (1/1)#0] ERROR c.d.flinkx.connector.oracle.converter.OracleRowConverter  - value [aa] convent failed 
2022-04-26 13:59:14.624 [dirty-consumer-pool-1-thread-1] WARN  com.dtstack.flinkx.dirty.log.LogDirtyDataCollector  - 
====================Dirty Data=====================
DirtyDataEntry[jobId='513b398ae58686268cd0be7691ae488a', jobName='Flink_Job', operatorName='Source: TableSourceScan(table=[[default_catalog, default_database, source]], fie', dirtyContent='{"arity":2,"nullBitsSizeInBytes":8,"offset":0,"sizeInBytes":0}', errorMessage='com.dtstack.flinkx.throwable.ReadRecordException: 
java.lang.ClassCastException: java.lang.String cannot be cast to oracle.sql.CLOB
	at com.dtstack.flinkx.connector.jdbc.source.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:274)
	at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:192)
	at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67)
	at com.dtstack.flinkx.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to oracle.sql.CLOB
	at com.dtstack.flinkx.connector.oracle.converter.OracleRowConverter.lambda$createInternalConverter$f047096$11(OracleRowConverter.java:165)
	at com.dtstack.flinkx.converter.AbstractRowConverter.lambda$wrapIntoNullableInternalConverter$a543b3ee$1(AbstractRowConverter.java:97)
	at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.toInternal(JdbcRowConverter.java:94)
	at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.toInternal(JdbcRowConverter.java:51)
	at com.dtstack.flinkx.connector.jdbc.source.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:252)

**Comment by yudedipan** [comment]
请问一下 ，怎么解决的 ？？

**Comment by lidong2021** [comment]
flink对应映射类型改成varchar，不要用string就可以了
