### ISSUE TITLE
MysqlBinlog->Elasticsearch Validation Failed: 1: id is missing

### ISSUE THREAD

**Issue by HendSame** [DTStack/chunjun#799]
## General Question
```
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: id is missing;
	at com.dtstack.flinkx.connector.elasticsearch7.sink.ElasticsearchOutputFormat.writeSingleRecordInternal(ElasticsearchOutputFormat.java:75)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:436)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:247)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:84)
	at com.dtstack.flinkx.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:117)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:54)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28)
	at SinkConversion$5.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28)
	at StreamExecCalc$3.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:317)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:411)
	at com.dtstack.flinkx.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:135)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)
Caused by: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: id is missing;
	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:26)
	at org.elasticsearch.action.delete.DeleteRequest.validate(DeleteRequest.java:136)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1480)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1454)
	at org.elasticsearch.client.RestHighLevelClient.delete(RestHighLevelClient.java:945)
	at com.dtstack.flinkx.connector.elasticsearch7.sink.ElasticsearchOutputFormat.writeSingleRecordInternal(ElasticsearchOutputFormat.java:68)
	... 34 more
', fieldName='null', createTime=2022-05-13 11:01:44.111]
```
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/9264192/168205539-16d00128-fc12-4823-b3c3-e244313adf2a.png">
<img width="884" alt="image" src="https://user-images.githubusercontent.com/9264192/168205613-747ace00-0656-4d4d-be17-a249f7f7bae5.png">

* /docs/connectors/elasticsearch-x 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/9264192/168205740-ec5c9a32-1891-4873-a427-92f8c80b6b78.png">

* 这里是不是缺失了对 ids 的配置的 说明？
* 目前发现，在数据更新和删除的时候，强关联了这个配置

**Comment by FlechazoW** [comment]
能否提交pr 修复下这个问题呢？

**Comment by HendSame** [comment]
可以
