### ISSUE TITLE
在执行mysql到mysql中 customSql 填写查询语句运行就报错 不填写 customSql  就可以正常运行 请问是什么问题呢

### ISSUE THREAD

**Issue by 2417380371** [DTStack/chunjun#809]
## General Question

[JdbcConf]:
{
  "semantic" : "at-least-once",
  "errorRecord" : 0,
  "checkFormat" : true,
  "parallelism" : 1,
  "pollingInterval" : 3000,
  "increment" : false,
  "flushIntervalMills" : 10000,
  "polling" : false,
  "querySql" : "SELECT * FROM (select id,aa,time from aa) flinkx_tmp WHERE  1=1 ",
  "mode" : "INSERT",
  "password" : "******",
  "customSql" : "select id,aa,time from aa",
  "startLocation" : "",
  "increColumn" : "",
  "metricPluginRoot" : "flinkx-dist/metrics",
  "restoreColumn" : "id",
  "restoreColumnIndex" : 0,
  "connection" : [ {
    "table" : [ "aa" ],
    "jdbcUrl" : [ "jdbc:mysql://192.168.66.128:3306/test1" ]
  } ],
  "where" : "",
  "splitPk" : "",
  "queryTimeOut" : 1000,
  "restoreColumnType" : "int",
  "fetchSize" : -2147483648,
  "useMaxFunc" : false,
  "column" : [ {
    "name" : "id",
    "type" : "int",
    "index" : 0,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "aa",
    "type" : "string",
    "index" : 1,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "time",
    "type" : "date",
    "index" : 2,
    "notNull" : false,
    "part" : false
  } ],
  "errorPercentage" : -1,
  "fieldNameList" : [ ],
  "withNoLock" : false,
  "increColumnIndex" : -1,
  "allReplace" : false,
  "splitStrategy" : "range",
  "initReporter" : true,
  "jdbcUrl" : "jdbc:mysql://192.168.66.128:3306/test1",
  "connectTimeOut" : 600,
  "batchSize" : 1,
  "speedBytes" : 0,
  "metricPluginName" : "prometheus",
  "properties" : {
    "user" : "root",
    "password" : "******",
    "useCursorFetch" : "true",
    "rewriteBatchedStatements" : "true"
  },
  "username" : "root"
}
2022-05-17 12:28:23.224 [Legacy Source Thread - Source: mysqlsourcefactory -> Sink: mysqlsinkfactory (1/1)#0] ERROR c.d.flinkx.connector.jdbc.converter.JdbcColumnConverter  - value [2022-05-09 09:24:15.0] convent failed
2022-05-17 12:28:23.229 [dirty-consumer-pool-2-thread-2] WARN  com.dtstack.flinkx.dirty.log.LogDirtyDataCollector  -
====================Dirty Data=====================
DirtyDataEntry[jobId='768abc6cb6a870e2b28551262e425342', jobName='Flink_Job', operatorName='Source: mysqlsourcefactory', dirtyContent='null', errorMessage='com.dtstack.flinkx.throwable.ReadRecordException:
java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.sql.Date
        at com.dtstack.flinkx.connector.jdbc.source.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:274)
        at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:192)
        at com.dtstack.flinkx.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67)
        at com.dtstack.flinkx.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)
Caused by: java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.sql.Date
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcColumnConverter.lambda$createInternalConverter$f047096$9(JdbcColumnConverter.java:154)
        at com.dtstack.flinkx.converter.AbstractRowConverter.lambda$wrapIntoNullableInternalConverter$a543b3ee$1(AbstractRowConverter.java:97)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcColumnConverter.toInternal(JdbcColumnConverter.java:99)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcColumnConverter.toInternal(JdbcColumnConverter.java:54)
        at com.dtstack.flinkx.connector.jdbc.source.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:252)
        ... 6 more
', fieldName='null', createTime=2022-05-17 12:28:23.225]

**Comment by 2417380371** [comment]
解决了，好像是没有声明写部分的数据类型
