### ISSUE TITLE
mysql binlog同步mysql报错com.alibaba.otter.canal.parse.exception.CanalParseException

### ISSUE THREAD

**Issue by yunfeng79** [DTStack/chunjun#820]
mysql binlog同步mysql报错

版本：mysql5.7
          flink 1.12.2、 hadoop 3.3.1、chunjun v1.12.3

同步json
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "username" : "chunjun",
          "password" : "chunjun",
          "cat" : "insert,delete,update",
          "jdbcUrl" : "jdbc:mysql://192.168.1.xx:3307/chunjun?useSSL=false",
          "host" : "192.168.1.207",
          "port" : 3307,
          "start" : {
          },
          "table" : [ "mytest1" ],
          "splitUpdate" : true,
          "pavingData" : true,
          "column": [
            {
              "name": "id",
              "type": "BIGINT"
            },
            {
              "name": "user_id",
              "type": "BIGINT"
            },
            {
              "name": "name",
              "type": "VARCHAR"
            }
          ]
        },
        "table": {
          "tableName": "mytest1"
        },
        "name" : "binlogreader"
      },
      "writer": {
        "name": "mysqlwriter",
        "parameter": {
          "username": "chunjun",
          "password": "chunjun",
          "connection": [
            {
              "jdbcUrl": "jdbc:mysql://192.168.1.xx:3307/chunjun?useSSL=false",
              "table": [
                "mytest1_sync"
              ]
            }
          ],
          "writeMode": "insert",
          "column": [
            {
              "name": "id",
              "type": "BIGINT"
            },
            {
              "name": "user_id",
              "type": "BIGINT"
            },
            {
              "name": "name",
              "type": "VARCHAR"
            }
          ]
        }
      }
    } ],
    "setting" : {
      "speed" : {
        "bytes" : 0,
        "channel" : 1
      }
    }
  }
}

运行脚本
sh ./bin/flinkx -mode yarn \ -jobName chunjun_session_01 \ -jobType sync -job $CHUNJUN_DIST/flinkx-examples/json/binlog/my_binlog_stream_transformer_207.json \ -hadoopConfDir $HADOOP_CONF_DIR  \ -flinkxDistDir $CHUNJUN_DIST/flinkx-dist \ -flinkConfDir $FLINK_CONF \ -confProp {\"yarn.application.id\":\"application_1652790451834_0006\"}

FLINK运行job后
报错信息如下：
com.alibaba.otter.canal.parse.exception.CanalParseException: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
Caused by: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:59) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:451) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:274) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[flinkx-connector-binlog-master.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: java.lang.ExceptionInInitializerError
	at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24) ~[flinkx-connector-binlog-master.jar:?]
	at Script_1652866925835_0.execute0(Unknown Source) ~[?:?]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:451) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:274) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[flinkx-connector-binlog-master.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]

请教下是什么原因。

**Comment by yunfeng79** [comment]
com.alibaba.otter.canal.parse.exception.CanalParseException: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
Caused by: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:59) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:451) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:274) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[flinkx-connector-binlog-master.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: java.lang.ExceptionInInitializerError
	at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24) ~[flinkx-connector-binlog-master.jar:?]
	at Script_1652939977810_0.execute0(Unknown Source) ~[?:?]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:451) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:274) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[flinkx-connector-binlog-master.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.google.common.collect.MapMaker.softValues()
	at com.google.common.collect.MapMakerHelper.softValues(MapMakerHelper.java:34) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.PatternUtils.<clinit>(PatternUtils.java:43) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24) ~[flinkx-connector-binlog-master.jar:?]
	at Script_1652939977810_0.execute0(Unknown Source) ~[?:?]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:451) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:274) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[flinkx-connector-binlog-master.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
Caused by: java.lang.NoSuchMethodException: com.google.common.collect.MapMaker.softValues()
	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_301]
	at com.google.common.collect.MapMakerHelper.softValues(MapMakerHelper.java:30) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.PatternUtils.<clinit>(PatternUtils.java:43) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24) ~[flinkx-connector-binlog-master.jar:?]
	at Script_1652939977810_0.execute0(Unknown Source) ~[?:?]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:451) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:274) ~[flinkx-connector-binlog-master.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[flinkx-connector-binlog-master.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[flinkx-connector-binlog-master.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
2022-05-19 14:02:35,288 ERROR com.dtstack.flinkx.connector.binlog.listener.BinlogAlarmHandler [] - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
Caused by: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:59)
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:451)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:274)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
	at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24)
	at Script_1652939977810_0.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53)
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.google.common.collect.MapMaker.softValues()
	at com.google.common.collect.MapMakerHelper.softValues(MapMakerHelper.java:34)
	at com.alibaba.otter.canal.filter.PatternUtils.<clinit>(PatternUtils.java:43)
	... 14 more
Caused by: java.lang.NoSuchMethodException: com.google.common.collect.MapMaker.softValues()
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.google.common.collect.MapMakerHelper.softValues(MapMakerHelper.java:30)
	... 15 more
]

**Comment by yqwoe** [comment]
还是一样的问题

**Comment by yqwoe** [comment]
local模式运行报的和上边一样的错
