### ISSUE TITLE
Java type conversion exception:  org.apache.flink.table.data.binary.BinaryStringData cannot be cast to org.apache.flink.table.data.DecimalData, which occurs when using MySQL binlog to synchronize data to Postgres

### ISSUE THREAD

**Issue by t291436520** [DTStack/chunjun#839]
**Version**
chunjun 1.12.3

**Describe the bug**
Java type conversion exception, which occurs when using MySQL binlog to synchronize data to Postgres

Config info：
```
{
    "job": {
        "content": [
            {
                "reader": {
                    "name": "binlogreader",
                    "table": {
                        "tableName": "sourceTable"
                    },
                    "parameter": {
                        "column": [
                            {
                                "name": "id",
                                "type": "BIGINT"
                            },
                            {
                                "name": "guid",
                                "type": "varchar"
                            },
                            {
                                "name": "consumption_guid",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_guid",
                                "type": "varchar"
                            },
                            {
                                "name": "product_guid",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_name",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_specification",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_unit",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_num",
                                "type": "varchar"
                            },
                            {
                                "name": "is_main_good",
                                "type": "int"
                            },
                            {
                                "name": "main_good_guid",
                                "type": "varchar"
                            },
                            {
                                "name": "surcharge",
                                "type": "decimal"
                            },
                            {
                                "name": "remark",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_type",
                                "type": "int"
                            },
                            {
                                "name": "subtotal",
                                "type": "decimal"
                            },
                            {
                                "name": "pay_price",
                                "type": "decimal"
                            },
                            {
                                "name": "dish_original_unit_price",
                                "type": "decimal"
                            },
                            {
                                "name": "dish_sell_unit_price",
                                "type": "decimal"
                            },
                            {
                                "name": "discount_money",
                                "type": "decimal"
                            },
                            {
                                "name": "gmt_create",
                                "type": "timestamp"
                            },
                            {
                                "name": "gmt_update",
                                "type": "timestamp"
                            },
                            {
                                "name": "gmt_modified",
                                "type": "timestamp"
                            }
                        ],
                        "username": "root",
                        "password": "root",
                        "cat": "insert,delete,update",
                        "jdbcUrl": "jdbc:mysql://******:3306/test?useSSL=false",
                        "host": "*********",
                        "port": 3306,
                        "start": {},
                        "table": [
                            "test.test"
                        ],
                        "splitUpdate": true,
                        "pavingData": true
                    }
                },
                "writer": {
                    "name": "postgresqlwriter",
                    "table": {
                        "tableName": "sinkTable"
                    },
                    "parameter": {
                        "print": true,
                        "username": "postgres",
                        "password": "postgres",
                        "connection": [
                            {
                                "jdbcUrl": "jdbc:postgresql://*******:5000/test?useSSL=false",
                                "table": [
                                    "test.test"
                                ]
                            }
                        ],
                        "batchSize": 1024,
                        "writeMode": "insert",
                        "flushIntervalMills": "3000",
                        "column": [
                            {
                                "name": "id",
                                "type": "BIGINT"
                            },
                            {
                                "name": "guid",
                                "type": "varchar"
                            },
                            {
                                "name": "consumption_guid",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_guid",
                                "type": "varchar"
                            },
                            {
                                "name": "product_guid",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_name",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_specification",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_unit",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_num",
                                "type": "numeric"
                            },
                            {
                                "name": "is_main_good",
                                "type": "int"
                            },
                            {
                                "name": "main_good_guid",
                                "type": "varchar"
                            },
                            {
                                "name": "surcharge",
                                "type": "numeric"
                            },
                            {
                                "name": "remark",
                                "type": "varchar"
                            },
                            {
                                "name": "dish_type",
                                "type": "int"
                            },
                            {
                                "name": "subtotal",
                                "type": "numeric"
                            },
                            {
                                "name": "pay_price",
                                "type": "numeric"
                            },
                            {
                                "name": "dish_original_unit_price",
                                "type": "numeric"
                            },
                            {
                                "name": "dish_sell_unit_price",
                                "type": "numeric"
                            },
                            {
                                "name": "discount_money",
                                "type": "numeric"
                            },
                            {
                                "name": "gmt_create",
                                "type": "timestamp"
                            },
                            {
                                "name": "gmt_update",
                                "type": "timestamp"
                            },
                            {
                                "name": "gmt_modified",
                                "type": "timestamp"
                            }
                        ]
                    }
                },
                "transformer": {
                    "transformSql": "select id,guid,consumption_guid,dish_guid,product_guid,dish_name,dish_specification,dish_unit,dish_num,is_main_good,main_good_guid,surcharge,remark,dish_type,subtotal,pay_price,dish_original_unit_price,dish_sell_unit_price,discount_money,gmt_create,gmt_update,gmt_modified from sourceTable"
                }
            }
        ],
        "setting": {
            "speed": {
                "channel": 1,
                "bytes": 0
            }
        }
    }
}
```
Run script:
```
./bin/flinkx -mode local -jobType sync -flinkxDistDir flinkx-dist -job test-mysql-binlog-to-postgres.json -flinkConfDir $FLINK_HOME/conf
```

Error log：
```
java.lang.ClassCastException: org.apache.flink.table.data.binary.BinaryStringData cannot be cast to org.apache.flink.table.data.DecimalData
        at org.apache.flink.table.data.GenericRowData.getDecimal(GenericRowData.java:174)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.lambda$createExternalConverter$ce7c3648$1(JdbcRowConverter.java:227)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.lambda$wrapIntoNullableExternalConverter$579ce5d$1(JdbcRowConverter.java:84)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.toExternal(JdbcRowConverter.java:113)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.toExternal(JdbcRowConverter.java:51)
        at com.dtstack.flinkx.connector.jdbc.sink.PreparedStmtProxy.convertToExternal(PreparedStmtProxy.java:123)
        at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.writeMultipleRecordsInternal(JdbcOutputFormat.java:212)
        at com.dtstack.flinkx.connector.postgresql.sink.PostgresOutputFormat.writeMultipleRecordsInternal(PostgresOutputFormat.java:126)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:444)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:404)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2022-05-20 10:01:47.143 [timer-data-write-thread-pool-1-thread-1] ERROR c.d.flinkx.connector.postgresql.sink.PostgresOutputFormat  - Writing records failed. com.dtstack.flinkx.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
        at com.dtstack.flinkx.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105)
        at com.dtstack.flinkx.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79)
        at com.dtstack.flinkx.dirty.manager.DirtyManager.collect(DirtyManager.java:140)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:430)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:448)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:448)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:404)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

2022-05-20 10:01:47.143 [dirty-consumer-pool-2-thread-2] WARN  com.dtstack.flinkx.dirty.log.LogDirtyDataCollector  - 
====================Dirty Data=====================
DirtyDataEntry[jobId='d722de2c54afeb17e28fce6eea2ea419', jobName='Flink_Job', operatorName='Sink: postgresqlsinkfactory', dirtyContent='{"arity":22,"rowKind":"UPDATE_BEFORE"}', errorMessage='com.dtstack.flinkx.throwable.WriteRecordException: 
JdbcOutputFormat [Flink_Job] writeRecord error: when converting field[0] in Row(-U(7926059,6923107686875660288,6923107274634297344,6733921430901096448,6733921430901096448,菜花1,6733921430905290752,份,1.0,1,null,0.000000000000000000,null,2,10.000000000000000000,10.000000000000000000,10.000000000000000000,10.000000000000000000,0.000000000000000000,2022-04-22T11:18:17,2022-05-20T09:56:42,2022-05-20T09:56:42))
java.lang.ClassCastException: org.apache.flink.table.data.binary.BinaryStringData cannot be cast to org.apache.flink.table.data.DecimalData
        at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.processWriteException(JdbcOutputFormat.java:349)
        at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:193)
        at com.dtstack.flinkx.connector.postgresql.sink.PostgresOutputFormat.writeSingleRecordInternal(PostgresOutputFormat.java:98)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:427)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:448)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:448)
        at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:404)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassCastException: org.apache.flink.table.data.binary.BinaryStringData cannot be cast to org.apache.flink.table.data.DecimalData
        at org.apache.flink.table.data.GenericRowData.getDecimal(GenericRowData.java:174)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.lambda$createExternalConverter$ce7c3648$1(JdbcRowConverter.java:227)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.lambda$wrapIntoNullableExternalConverter$579ce5d$1(JdbcRowConverter.java:84)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.toExternal(JdbcRowConverter.java:113)
        at com.dtstack.flinkx.connector.jdbc.converter.JdbcRowConverter.toExternal(JdbcRowConverter.java:51)
        at com.dtstack.flinkx.connector.jdbc.sink.PreparedStmtProxy.writeSingleRecordInternal(PreparedStmtProxy.java:194)
        at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:190)
        ... 13 more
', fieldName='null', createTime=2022-05-20 10:01:47.096]

===================================================
```

**Comment by PaddyMelody** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/46181516/169490207-ace10ffc-cff1-495c-b35b-623677991b29.png">
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/46181516/169490298-557b21a0-7d34-4f49-af40-e8028c4ff1e6.png">


This is not a bug
The reason for the problem is：column 'dish_num' is varchar type in mysql,but is numeric type in pg
If you are still in doubt about this problem, we can reopen this issue

**Comment by t291436520** [comment]
Thinks
 
 
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 5月20日 16:45，Paddy GU ***@***.***> 写道： 
   
   
   
  This is not a bug
 The reason for the problem is：column 'dish_num' is varchar type in mysql,but is numeric type in pg
 If you are still in doubt about this problem, we can reopen this issue
