### ISSUE TITLE
preSql没有执行权限会把异常catch掉

### ISSUE THREAD

**Issue by liugddx** [DTStack/chunjun#840]
com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat#executeBatch

`protected void executeBatch(List<String> sqlList) {
        if (CollectionUtils.isNotEmpty(sqlList)) {
            try (Connection conn = getConnection();
                    Statement stmt = conn.createStatement()) {
                for (String sql : sqlList) {
                    // 兼容多条SQL写在同一行的情况
                    String[] strings = sql.split(";");
                    for (String s : strings) {
                        if (StringUtils.isNotBlank(s)) {
                            LOG.info("add sql to batch, sql = {}", sql);
                            stmt.addBatch(sql);
                        }
                    }
                }
                stmt.executeBatch();
            } catch (SQLException e) {
                LOG.error(
                        "execute sql failed, sqlList = {}, e = {}",
                        JsonUtil.toPrintJson(sqlList),
                        e);
            }
        }
    }
`
catch中 JsonUtil.toPrintJson(sqlList)方法抛出异常
`Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
	at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:811)
	at com.dtstack.flinkx.environment.MyLocalStreamEnvironment.execute(MyLocalStreamEnvironment.java:174)
	at com.dtstack.flinkx.Main.exeSyncJob(Main.java:226)
	at com.dtstack.flinkx.Main.main(Main.java:119)
	at com.dtstack.flinkx.client.local.LocalClusterClientHelper.submit(LocalClusterClientHelper.java:36)
	at com.dtstack.flinkx.client.Launcher.main(Launcher.java:127)
Caused by: org.apache.flink.runtime.client.JobInitializationException: Could not instantiate JobManager.
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Source: oraclesourcefactory -> SinkConversionToTuple2 -> Map -> Sink: oraclesinkfactory': error parse [[truncate table API_GW.T_SHD_API_BLACKWHITE_LIST_BIND]] to json
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:293)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createExecutionGraph(SchedulerBase.java:322)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:276)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:249)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:133)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:111)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:342)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:327)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:95)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:39)
	at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:163)
	at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:86)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:472)
	... 4 more
Caused by: java.lang.RuntimeException: error parse [[truncate table API_GW.T_SHD_API_BLACKWHITE_LIST_BIND]] to json
	at com.dtstack.flinkx.util.JsonUtil.toPrintJson(JsonUtil.java:120)
	at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.executeBatch(JdbcOutputFormat.java:304)
	at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.initializeGlobal(JdbcOutputFormat.java:74)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:110)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:289)
	... 16 more
Caused by: org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.HashMap<java.lang.Object,java.lang.Object>` out of START_ARRAY token
 at [Source: (String)"["truncate table API_GW.T_SHD_API_BLACKWHITE_LIST_BIND"]"; line: 1, column: 1]
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1126)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmpty(StdDeserializer.java:639)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:360)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at com.dtstack.flinkx.util.JsonUtil.toPrintJson(JsonUtil.java:116)
	... 20 more
`

**Comment by PaddyMelody** [comment]
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/46181516/169488587-6b2dafa8-3800-4d28-af66-e0a4a12081ef.png">
Problems that have been solved
