### ISSUE TITLE
配置文件导致的oracle写入错误（包含表结构，配置文件，报错的信息，参数，位置）

### ISSUE THREAD

**Issue by EngonVHKxZ** [DTStack/chunjun#940]
## 数据库表结构

| 表空间 | 表名 | 字段名 | 字段类型 |
| :-: | :-: | :-: | :-: |
| ROMA_LOGMINER | LOGMINER_FROM |        |          |
|  |  | ID | VARCHAR2 |
|  |  | NAME | VARCHAR2 |
|  |  | AGE | NUMBER |
| ROMA_LOGMINER | LOGMINER_TO |        |          |
|  |  | ID | VARCHAR2 |
|  |  | NAME | VARCHAR2 |
|  |  | AGE | NUMBER |

## 配置文件

```
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@192.168.174.128:1521:helowin",
            "username": "roma_logminer",
            "password": "roma_logminer",
            "supportAutoAddLog": false,
            "table": ["ROMA_LOGMINER.LOGMINER_FROM"],
            "cat": "INSERT,UPDATE,DELETE",
            "pavingData" : true,
            "readPosition" : "current",
            "queryTimeout": 3000
          },
          "name": "oraclelogminerreader"
        },
        "writer": {
          "parameter": {
            "writeMode":"update",
            "updateKey": {
              "key": ["ID"]
            },
            "allReplace": true,
            "username": "roma_logminer",
            "password": "roma_logminer",
            "connection": [{
              "jdbcUrl": "jdbc:oracle:thin:@192.168.174.128:1521:helowin",
              "table": ["ROMA_LOGMINER.LOGMINER_TO"]
            }],
            "column": [
              {
                "name": "ID",
                "type": "string"
              },
              {
                "name": "NAME",
                "type": "string"
              }
            ]
          },
          "name": "oraclewriter"
        },
        "nameMapping":{
          "schemaMappings":{
            "ROMA_LOGMINER":"ROMA_LOGMINER"
          },
          "tableMappings":{
            "ROMA_LOGMINER":{
              "LOGMINER_FROM": "LOGMINER_TO"
            }
          },
          "fieldMappings":{
            "ROMA_LOGMINER":{
              "LOGMINER_FROM":{
                "ID": "ID",
                "NAME": "NAME"
              }
            }
          }
        }
      }
    ],
    "setting" : {
      "speed" : {
        "bytes" : 0,
        "channel" : 1
      }
    }
  }
}

```

### 报错日志

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.toExternal(JdbcColumnConverter.java:125)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.toExternal(JdbcColumnConverter.java:55)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.convertToExternal(PreparedStmtProxy.java:133)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeMultipleRecordsInternal(JdbcOutputFormat.java:216)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:483)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2022-06-10 16:14:34,690 - 70333 INFO  [LogMinerConnection-pool-0] com.dtstack.chunjun.connector.oraclelogminer.listener.LogMinerConnection:query LogMiner data, startScn:1363131,endScn:1363149,timeConsuming 0
2022-06-10 16:14:36,219 - 71862 INFO  [LogMiner-pool-0] com.dtstack.chunjun.connector.oraclelogminer.listener.LogMinerConnection:getEndScn success,startScn:1363131,endScn:1363157, loadRedoLog:true
2022-06-10 16:14:36,281 - 71924 WARN  [dirty-consumer-pool-2-thread-2] com.dtstack.chunjun.dirty.log.LogDirtyDataCollector:
====================Dirty Data=====================
DirtyDataEntry[jobId='d6f58edf254dddf04c69ebf3291994b0', jobName='Flink_Job', operatorName='Sink: oraclesinkfactory', dirtyContent='{"extHeader":["schema","opTime","table","scn","ts"],"byteSize":1697,"headers":["scn","schema","table","ts","opTime","type","before_ID","before_NAME","before_AGE","after_NAME","after_ID","after_AGE"],"string":"(1363130,ROMA_LOGMINER,LOGMINER_TO,6940939183850655744,2022-06-10 16:14:00.000000,UPDATE,1,after,3,after,1,3)","rowKind":"INSERT","arity":12,"headerInfo":{"scn":0,"schema":1,"table":2,"ts":3,"opTime":4,"type":5,"before_ID":6,"before_NAME":7,"before_AGE":8,"after_NAME":9,"after_ID":10,"after_AGE":11}}', errorMessage='com.dtstack.chunjun.throwable.WriteRecordException: 
JdbcOutputFormat [Flink_Job] writeRecord error: when converting field[0] in Row(+I(1363130,ROMA_LOGMINER,LOGMINER_TO,6940939183850655744,2022-06-10 16:14:00.000000,UPDATE,1,after,3,after,1,3))
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.processWriteException(JdbcOutputFormat.java:359)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:197)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:466)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:487)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:487)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.toExternal(JdbcColumnConverter.java:125)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.toExternal(JdbcColumnConverter.java:55)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.writeSingleRecordInternal(PreparedStmtProxy.java:202)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:194)
	... 13 more
', fieldName='null', createTime=2022-06-10 16:14:36.211]

===================================================
2022-06-10 16:14:36,281 - 71924 ERROR [timer-data-write-thread-pool-1-thread-1] com.dtstack.chunjun.sink.format.BaseRichOutputFormat:Writing records failed. com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105)
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79)
	at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:140)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:469)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:487)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:487)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### 报错位置

```
com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.FieldNamedPreparedStatement toExternal(RowData rowData, FieldNamedPreparedStatement statement);
```

### 报错参数

```
RowData:  +I(1363248,ROMA_LOGMINER,LOGMINER_TO,6940939768704405504,2022-06-10 16:16:24.000000,INSERT,null,null,null,2,INSERT,4)
toExternalConverters: [
	VARCHAR(3999),
	VARCHAR(3999)
]
```

### 报错日志

```
DirtyDataEntry[jobId='d502bd47322aaf8e5307e9f45fc91717', jobName='Flink_Job', operatorName='Sink: oraclesinkfactory', dirtyContent='{"extHeader":["schema","opTime","table","scn","ts"],"byteSize":1577,"string":"(1363487,ROMA_LOGMINER,LOGMINER_TO,6940941100953767936,2022-06-10 16:21:42.000000,DELETE,2,INSERT,4,null,null,null)","headers":["scn","schema","table","ts","opTime","type","before_ID","before_NAME","before_AGE","after_ID","after_NAME","after_AGE"],"arity":12,"headerInfo":{"scn":0,"schema":1,"table":2,"ts":3,"opTime":4,"type":5,"before_ID":6,"before_NAME":7,"before_AGE":8,"after_ID":9,"after_NAME":10,"after_AGE":11},"rowKind":"DELETE"}', errorMessage='com.dtstack.chunjun.throwable.WriteRecordException: 
JdbcOutputFormat [Flink_Job] writeRecord error: when converting field[0] in Row(-D(1363487,ROMA_LOGMINER,LOGMINER_TO,6940941100953767936,2022-06-10 16:21:42.000000,DELETE,2,INSERT,4,null,null,null))
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IndexOutOfBoundsException: Index: -1, Size: 3
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.processWriteException(JdbcOutputFormat.java:359)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:197)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:466)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:487)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:487)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IndexOutOfBoundsException: Index: -1, Size: 3
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4790)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.getOrCreateFieldNamedPstmt(PreparedStmtProxy.java:151)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.writeSingleRecordInternal(PreparedStmtProxy.java:199)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:194)
	... 13 more
Caused by: java.lang.IndexOutOfBoundsException: Index: -1, Size: 3
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.getColumnMeta(DynamicPreparedStmt.java:240)
	at com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.buildStmt(DynamicPreparedStmt.java:84)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.lambda$getOrCreateFieldNamedPstmt$0(PreparedStmtProxy.java:155)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	... 18 more
', fieldName='null', createTime=2022-06-10 16:22:22.188]

===================================================
2022-06-10 16:22:22,377 - 60448 ERROR [timer-data-write-thread-pool-1-thread-1] com.dtstack.chunjun.sink.format.BaseRichOutputFormat:Writing records failed. com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105)
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79)
	at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:140)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:469)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:487)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:487)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### 报错位置

```
com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.getColumnMeta(String schema, String table, Connection dbConn);
```

### 报错参数

```
schema: ROMA_LOGMINER
table: LOGMINER_TO
nameList: [
	"ID","NAME","AGE"
]
typeList: [
	"VARCHAR2","VARCHAR2","NUMBER"
]
```

**Comment by queyijun** [comment]
```
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@192.168.147.128:1521:helowin",
            "username": "qyj",
            "password": "qyj",
            "supportAutoAddLog": false,
            "table": ["QYJ.test_01"],
            "cat": "UPDATE,INSERT,DELETE",
            "split":true,
            "readPosition": "CURRENT",
            "queryTimeout": 3000
          },
          "name": "oraclelogminerreader"
        },
        "writer": {
          "parameter": {
            "writeMode": "update",
            "updateKey": {
              "key": ["id"]
            },
            "allReplace": true,
            "username": "qyj",
            "password": "qyj",
            "connection": [{
                "schema": "QYJ",
                "jdbcUrl": "jdbc:oracle:thin:@192.168.147.128:1521:helowin",
                "table": ["test_02"]
            }],
            "column": [
              {
                "name": "id",
                "type": "string"
              },
              {
                "name": "name",
                "type": "string"
              }
            ]

          },
          "name": "oraclewriter"
        },
        "nameMapping":{
          "schemaMappings":{
            "QYJ":"QYJ"
          },
          "tableMappings":{
            "QYJ":{
              "test_01": "test_02"
            }
          },
          "fieldMappings":{
            "QYJ":{
              "test_02":{
                "ID": "ID",
                "NAME": "NAME"
              }
            }
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": 0
      },
      "errorLimit": {
        "record": 1
      },
      "restore": {
        "maxRowNumForCheckpoint": 0,
        "isRestore": false,
        "restoreColumnName": "",
        "restoreColumnIndex": 0
      },
      "log": {
        "isLogger": true,
        "level": "debug",
        "path": "",
        "pattern": ""
      }
    }
  }
}
```

这个试一下

**Comment by yinshaohua77** [comment]
请问一下这个nameMapping配置生效吗？
