### ISSUE TITLE
kuduSource to Stream appear  org.apache.flink.table.data.GenericRowData cannot be cast to com.dtstack.chunjun.element.ColumnRowData

### ISSUE THREAD

**Issue by huaxiapanda** [DTStack/chunjun#957]
**json**
{
  "job": {
    "content": [
      {
        "reader": {
          "name": "kudureader",
          "parameter": {
            "column": [
              {
                "name": "REPORT_TIME",
                "type": "UNIXTIME_MICROS"
              },
              {
                "name": "VEHICLE_TAG",
                "type": "STRING"
              },
              {
                "name": "REV",
                "type": "INT32"
              },
              {
                "name": "LONGITUDE",
                "type": "DOUBLE"
              },
              {
                "name": "LATITUDE",
                "type": "DOUBLE"
              },
              {
                "name": "SPEED",
                "type": "DOUBLE"
              },
              {
                "name": "HEADING",
                "type": "DOUBLE"
              },
              {
                "name": "TRAIN_ASSIGNMENT",
                "type": "STRING"
              },
              {
                "name": "PREDICTABLE",
                "type": "INT32"
              }
            ],
            "masters": "localhost:7051",
            "table": "sfmta_kudu",
            "readMode": "read_latest",
            "workerCount": 2,
            "operationTimeout": 30000,
            "adminOperationTimeout": 30000,
            "queryTimeout": 30000,
            "batchSizeBytes": 1048576
          }
        },
        "writer": {
          "parameter": {
            "print": true
          },
          "name": "streamwriter"
        }
      }
    ],
    "setting": {
      "restore": {
        "maxRowNumForCheckpoint": 0,
        "isRestore": false,
        "restoreColumnName": "",
        "restoreColumnIndex": 0
      },
      "errorLimit": {
        "record": 100
      },
      "speed": {
        "bytes": 0,
        "channel": 1
      },
      "log": {
        "isLogger": false,
        "level": "debug",
        "path": "",
        "pattern": ""
      }
    }
  }
}
**命令**
bin/start-chunjun -mode local -jobType sync -job ./chunjun-examples/json/kudu/kudu_stream_test.json -chunjunDistDir chunjun-dist

**结果**

java.lang.ClassCastException: org.apache.flink.table.data.GenericRowData cannot be cast to com.dtstack.chunjun.element.ColumnRowData
	at com.dtstack.chunjun.metrics.RowSizeCalculator$SyncCalculator.getObjectSize(RowSizeCalculator.java:91)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:207)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)
2022-06-16 12:53:44.712 [flink-akka.actor.default-dispatcher-4] INFO  o.a.f.r.e.f.flip1.RestartPipelinedRegionFailoverStrategy  - Calculating tasks to restart to recover the failed task bc764cd8ddf7a0cff126f51c16239658_0.
2022-06-16 12:53:44.713 [flink-akka.actor.default-dispatcher-4] INFO  o.a.f.r.e.f.flip1.RestartPipelinedRegionFailoverStrategy  - 2 tasks should be restarted to recover the failed task bc764cd8ddf7a0cff126f51c16239658_0. 
2022-06-16 12:53:44.715 [flink-akka.actor.default-dispatcher-4] INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph  - Job Flink_Job (89e11e7a67d9ac250b23a103b9e73826) switched from state RUNNING to FAILING.
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:118)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:80)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:233)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:224)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:215)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:666)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:89)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:446)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage$$$capture(ActorCell.scala:592)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassCastException: org.apache.flink.table.data.GenericRowData cannot be cast to com.dtstack.chunjun.element.ColumnRowData
	at com.dtstack.chunjun.metrics.RowSizeCalculator$SyncCalculator.getObjectSize(RowSizeCalculator.java:91)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:207)
	at com.dtstack.chunjun.source.format.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:67)
	at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:133)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)

**Comment by huaxiapanda** [comment]
场景 kuduSource to KuduSink
**json**
{
  "job": {
    "content": [
      {
        "reader": {
          "name": "kudureader",
          "parameter": {
            "column": [
              {
                "name": "REPORT_TIME",
                "type": "UNIXTIME_MICROS"
              },
              {
                "name": "VEHICLE_TAG",
                "type": "STRING"
              },
              {
                "name": "REV",
                "type": "INT32"
              },
              {
                "name": "LONGITUDE",
                "type": "DOUBLE"
              },
              {
                "name": "LATITUDE",
                "type": "DOUBLE"
              },
              {
                "name": "SPEED",
                "type": "DOUBLE"
              },
              {
                "name": "HEADING",
                "type": "DOUBLE"
              },
              {
                "name": "TRAIN_ASSIGNMENT",
                "type": "STRING"
              },
              {
                "name": "PREDICTABLE",
                "type": "INT32"
              }
            ],
            "masters": "172.29.207.143:7051,172.29.207.143:7151,172.29.207.143:7251",
            "table": "sfmta_kudu",
            "readMode": "read_latest",
            "workerCount": 2,
            "operationTimeout": 30000,
            "adminOperationTimeout": 30000,
            "queryTimeout": 30000,
            "batchSizeBytes": 1048576
          }
        },
        "writer": {
          "parameter": {
            "column": [
              {
                "name": "REPORT_TIME",
                "type": "UNIXTIME_MICROS"
              },
              {
                "name": "VEHICLE_TAG",
                "type": "STRING"
              },
              {
                "name": "REV",
                "type": "INT32"
              },
              {
                "name": "LONGITUDE",
                "type": "DOUBLE"
              },
              {
                "name": "LATITUDE",
                "type": "DOUBLE"
              },
              {
                "name": "SPEED",
                "type": "DOUBLE"
              },
              {
                "name": "HEADING",
                "type": "DOUBLE"
              },
              {
                "name": "TRAIN_ASSIGNMENT",
                "type": "STRING"
              },
              {
                "name": "PREDICTABLE",
                "type": "INT32"
              }
            ],
            "masters": "localhost:7051",
            "table": "sfmta_kudu_one",
            "flushMode": "manual_flush",
            "writeMode": "append",
            "batchSizeBytes": 1048576
          },
          "name": "kuduwriter"
        }
      }
    ],
    "setting": {
      "restore": {
        "maxRowNumForCheckpoint": 0,
        "isRestore": false,
        "restoreColumnName": "",
        "restoreColumnIndex": 0
      },
      "errorLimit": {
        "record": 100
      },
      "speed": {
        "bytes": 0,
        "channel": 1
      },
      "log": {
        "isLogger": false,
        "level": "debug",
        "path": "",
        "pattern": ""
      }
    }
  }
}

**命令**
bin/start-chunjun -mode local -jobType sync -job ./chunjun-examples/json/kudu/kudu_stream_test.json -chunjunDistDir chunjun-dist

**结果**

java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.Long
	at com.dtstack.chunjun.connector.kudu.sink.KuduOutputFormat.writeSingleRecordInternal(KuduOutputFormat.java:77)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:466)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:272)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:92)
	at com.dtstack.chunjun.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:117)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:54)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:191)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:204)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:174)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:398)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:619)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:583)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:758)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:573)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.Long
	at org.apache.flink.table.data.GenericRowData.getLong(GenericRowData.java:154)
	at com.dtstack.chunjun.connector.kudu.converter.KuduColumnConverter.lambda$createExternalConverter$3ab0349a$5(KuduColumnConverter.java:175)
	at com.dtstack.chunjun.connector.kudu.converter.KuduColumnConverter.lambda$wrapIntoNullableExternalConverter$4be2f56a$1(KuduColumnConverter.java:86)
	at com.dtstack.chunjun.connector.kudu.converter.KuduColumnConverter.toExternal(KuduColumnConverter.java:106)
	at com.dtstack.chunjun.connector.kudu.converter.KuduColumnConverter.toExternal(KuduColumnConverter.java:52)
	at com.dtstack.chunjun.connector.kudu.sink.KuduOutputFormat.writeSingleRecordInternal(KuduOutputFormat.java:72)
	... 16 more
', fieldName='null', createTime=2022-06-16 13:55:57.308]

**分析**
kudu UNIXTIME_MICROS原先设计映射成flink table的bigint类型，但是在进行kudusink的时候，RowData的类型是Timestamp因此，出现类型转换异常

**Comment by huaxiapanda** [comment]
@FlechazoW
