### ISSUE TITLE
写入hdfs 失败

### ISSUE THREAD

**Issue by lordk911** [DTStack/chunjun#987]
**Describe the bug**
使用1.12.4版本测试， 运行之前正常的任务，报错：

```
2022-06-22 15:15:49.849 [flink-akka.actor.default-dispatcher-3] INFO  org.apache.flink.runtime.rpc.akka.AkkaRpcService  - Stopped Akka RPC service.
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
        at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
        at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:811)
        at com.dtstack.chunjun.environment.MyLocalStreamEnvironment.execute(MyLocalStreamEnvironment.java:174)
        at com.dtstack.chunjun.Main.exeSyncJob(Main.java:227)
        at com.dtstack.chunjun.Main.main(Main.java:122)
        at com.dtstack.chunjun.client.local.LocalClusterClientHelper.submit(LocalClusterClientHelper.java:35)
        at com.dtstack.chunjun.client.Launcher.main(Launcher.java:119)
Caused by: org.apache.flink.runtime.client.JobInitializationException: Could not instantiate JobManager.
        at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:488)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Sink: hdfssinkfactory': null
        at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:293)
        at org.apache.flink.runtime.scheduler.SchedulerBase.createExecutionGraph(SchedulerBase.java:322)
        at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:276)
        at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:249)
        at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:133)
        at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:111)
        at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:342)
        at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:327)
        at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:95)
        at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:39)
        at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:163)
        at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:86)
        at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:472)
        ... 4 more
Caused by: java.lang.NullPointerException
        at com.dtstack.chunjun.connector.hdfs.sink.HdfsOrcOutputFormat.openSource(HdfsOrcOutputFormat.java:107)
        at com.dtstack.chunjun.sink.format.BaseFileOutputFormat.initVariableFields(BaseFileOutputFormat.java:112)
        at com.dtstack.chunjun.connector.hdfs.sink.BaseHdfsOutputFormat.initVariableFields(BaseHdfsOutputFormat.java:97)
        at com.dtstack.chunjun.sink.format.BaseFileOutputFormat.initializeGlobal(BaseFileOutputFormat.java:65)
        at org.apache.flink.runtime.jobgraph.InputOutputFormatVertex.initializeOnMaster(InputOutputFormatVertex.java:110)
        at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:289)
        ... 16 more
```

我把hdfs-site.xml\ core-site.xml 打入了chunjun-connector-hdfs-master.jar , 在之前的版本也是这么做的。

**Comment by lordk911** [comment]
```
cat /data/soft/chunjun/chunjun-examples/json/hdfs/stream_hdfs_orc2.json
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "sliceRecordCount": ["100000"],
            "column": [
              {
                "name": "id",
                "type": "int"
              },
              {
                "name": "col_boolean",
                "type": "boolean"
              },
              {
                "name": "col_tinyint",
                "type": "tinyint"
              },
              {
                "name": "col_smallint",
                "type": "smallint"
              },
              {
                "name": "col_int",
                "type": "int"
              },
              {
                "name": "col_bigint",
                "type": "bigint"
              },
              {
                "name": "col_float",
                "type": "float"
              },
              {
                "name": "col_double",
                "type": "double"
              },
              {
                "name": "col_string",
                "type": "string"
              },
              {
                "name": "col_varchar",
                "type": "varchar(255)"
              },
              {
                "name": "col_char",
                "type": "char(255)"
              },
              {
                "name": "col_binary",
                "type": "binary"
              },
              {
                "name": "col_timestamp",
                "type": "timestamp"
              },
              {
                "name": "col_date",
                "type": "date"
              }
            ]
          },
          "name": "streamreader"
        },
        "writer": {
          "name": "hdfswriter",
          "parameter": {
            "path": "hdfs://nsprd/tmp/datax/tmp/flinkx/test1",
            "defaultFS": "hdfs://nsprd",
            "column": [
              {
                "name": "id",
                "type": "int"
              },
              {
                "name": "col_boolean",
                "type": "boolean"
              },
              {
                "name": "col_tinyint",
                "type": "tinyint"
              },
              {
                "name": "col_smallint",
                "type": "smallint"
              },
              {
                "name": "col_int",
                "type": "int"
              },
              {
                "name": "col_bigint",
                "type": "bigint"
              },
              {
                "name": "col_float",
                "type": "float"
              },
              {
                "name": "col_double",
                "type": "double"
              },
              {
                "name": "col_string",
                "type": "string"
              },
              {
                "name": "col_varchar",
                "type": "varchar(255)"
              },
              {
                "name": "col_char",
                "type": "char(255)"
              },
              {
                "name": "col_binary",
                "type": "binary"
              },
              {
                "name": "col_timestamp",
                "type": "timestamp"
              },
              {
                "name": "col_date",
                "type": "date"
              }
            ],
            "fileType": "orc",
            "maxFileSize": 10485760,
            "nextCheckRows": 20000,
            "fieldDelimiter": ",",
            "encoding": "utf-8",
            "fileName": "pt=20201214",
            "writeMode": "overwrite"
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": 0
      }
    }
  }
}
```

**Comment by lordk911** [comment]
![企业微信截图_97df79bd-51b9-4242-bb7b-460d898dc085](https://user-images.githubusercontent.com/19989300/174987764-c08a173c-5c72-4281-89c5-572404704d79.png)

**Comment by ChestnutQiang** [comment]
1. 你是用 json 还是 sql。 目前 sql 还不支持。 我还在想办法做的更通用。 json 的情况需要手动填上这两个字段。
2. text 的处理逻辑是直接切分。但是无法拿到所有的元数据信息。  orc 和 parquet 是可以根据文件拿到所有字段的元数据信息的。
