### ISSUE TITLE
oraclelogminer to mysql appears IndexOutOfBoundsException

### ISSUE THREAD

**Issue by huaxiapanda** [DTStack/chunjun#988]
**Describe the bug**
执行oraclelogminer 写入 mysql的案例中，出现索引越界异常

**To Reproduce**
1. 按照如下配置
`json
{
  "job": {
    "content": [
      {
        "nameMapping": {
          "schemaMappings": {
            "TXJT": "report"
          },
          "tableMappings": {
            "TXJT": {
               "SYS_USER": "SYS_USER"
            }
          },
          "fiedMappings": {
            "TXJT": {
              "SYS_USER": {
                "ID": "ID",
                "USERNAME": "USERNAME",
                "PASSWORD": "PASSWORD",
                "AUTHORITY": "AUTHORITY",
                "STATUS": "STATUS",
                "DEPT": "DEPT"
              }
            }
          }
        },
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@172.29.120.2:1521:XE",
            "username": "system",
            "password": "123456",
            "supportAutoAddLog": false,
            "table": ["TXJT.SYS_USER"],
            "cat": "UPDATE,INSERT,DELETE",
            "pavingData" : false,
            "readPosition" : "all",
            "queryTimeout": 1800
          },
          "name": "oraclelogminerreader"
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "root",
            "password": "123456",
            "connection": [
              {
                "jdbcUrl": "jdbc:mysql://127.0.0.1:3306/report?useSSL=false",
                "table": [
                  "SYS_USER"
                ],
                "schema":"report"
              }
            ],
            "writeMode": "insert",
            "column": [
             {
              "name": "ID",
              "type": "bigint"
              },
              {
              "name": "USERNAME",
              "type": "varchar"
              },
              {
              "name": "PASSWORD",
              "type": "varchar"
              },
              {
              "name": "AUTHORITY",
              "type": "varchar"
              },
              {
              "name": "STATUS",
              "type": "varchar"
              },
              {
              "name": "DEPT",
              "type": "varchar"
              }
            ]
          }
        }
      }
    ],
    "setting": {
      "restore": {
        "isRestore": true,
        "isStream": true
      },
      "speed": {
        "readerChannel": 1,
        "writerChannel": 1
      }
    }
  }
} 
`
2. 命令bin/start-chunjun -mode local -jobType sync -job D:\oraclemysql.json -chunjunDistDir chunjun-dist 
3. 错误信息
2022-06-22 15:30:22.160 [timer-data-write-thread-pool-1-thread-1] ERROR com.dtstack.chunjun.connector.mysql.sink.MysqlOutputFormat  - Writing records failed. com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105)
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79)
	at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:140)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:469)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:487)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:487)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2022-06-22 15:30:22.160 [dirty-consumer-pool-2-thread-2] WARN  com.dtstack.chunjun.dirty.log.LogDirtyDataCollector  - 
====================Dirty Data=====================
DirtyDataEntry[jobId='13aedd86d05bcf3cb50e546e9b159eb9', jobName='Flink_Job', operatorName='Sink: mysqlsinkfactory', dirtyContent='{"extHeader":["schema","opTime","table","scn","ts"],"byteSize":1167,"string":"(1712293,report,SYS_USER,6945276743322308608,2022-06-22 11:25:50.000000,INSERT,{},{\"ID\":\"2\",\"USERNAME\":\"user\",\"PASSWORD\":\"$2a$10$YwfzKEw2fzlLa5IfNgBm9e7pskhzu1nEndeV5yFRXWOWdlAuSTyWe\",\"AUTHORITY\":\"USER\",\"STATUS\":\"0\",\"DEPT\":\"JT\"})","headers":["scn","schema","table","ts","opTime","type","before","after"],"arity":8,"rowKind":"INSERT","headerInfo":{"scn":0,"schema":1,"table":2,"ts":3,"opTime":4,"type":5,"before":6,"after":7}}', errorMessage='com.dtstack.chunjun.throwable.WriteRecordException: 
JdbcOutputFormat [Flink_Job] writeRecord error: when converting field[0] in Row(+I(1712293,report,SYS_USER,6945276743322308608,2022-06-22 11:25:50.000000,INSERT,{},{"ID":"2","USERNAME":"user","PASSWORD":"$2a$10$YwfzKEw2fzlLa5IfNgBm9e7pskhzu1nEndeV5yFRXWOWdlAuSTyWe","AUTHORITY":"USER","STATUS":"0","DEPT":"JT"}))
java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.processWriteException(JdbcOutputFormat.java:359)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:197)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:466)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:487)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:487)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.toExternal(JdbcColumnConverter.java:125)
	at com.dtstack.chunjun.connector.jdbc.converter.JdbcColumnConverter.toExternal(JdbcColumnConverter.java:55)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.writeSingleRecordInternal(PreparedStmtProxy.java:200)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:194)
	... 12 more
', fieldName='null', createTime=2022-06-22 15:30:22.105]

**分析结果**
经调试，发现上游的oraclelogminer和下游mysql所需要的rowData的格式有点不一样，下游的mysql使用jdbc写入，而JdbcColumnConverter.java 这个类型中的toExternal()方法，是给sql语句进行填充值的，但是按照下图的rowData进行填充就会出现问题，因为我整个表就6个字段，因此toExternalConverters列表也就是6个，但是现在上游的rowData的getArity()是8，就会出现索引越界异常，且这里只需要上游rowData的after数据即可！
![image](https://user-images.githubusercontent.com/55483248/174972220-fead7af0-b03c-4c6a-98c1-319190e17a99.png)

**Comment by huaxiapanda** [comment]
`{
  "job": {
    "content": [
      {
        "nameMapping": {
          "schemaMappings": {
            "TXJT": "report"
          },
          "tableMappings": {
            "TXJT": {
               "SYS_USER": "SYS_USER"
            }
          }
        },
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@172.29.120.2:1521:XE",
            "username": "system",
            "password": "123456",
            "split": true,          
            "table": ["TXJT.SYS_USER"],
            "cat": "UPDATE,INSERT,DELETE",
            "pavingData" : false,
            "readPosition" : "current",
            "queryTimeout": 1800,
            "schema": "TXJT"
          },
          "name": "oraclelogminerreader",
          "type": 2
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "root",
            "password": "7^7V#EcgbjBUYYtR",
            "connection": [
              {
                "jdbcUrl": "jdbc:mysql://127.0.0.1:3306/report?useSSL=false",
                 # 上游是binlog或者oraclelogminer的，下游的rdb不需要配置column，程序会解析数据里的字段信息
                "table": [
                  "*"
                ]
              }
            ],
            "writeMode": "APPEND"
          }
        }
      }
    ],
    "setting": {
      "restore": {
        "isRestore": true,
        "isStream": true
      },
      "speed": {
        "readerChannel": 1,
        "writerChannel": 1
      }
    }
  }
} `

**Comment by hj102015** [comment]
我也遇到了这个问题，不过在配置了nameMapping tableMapping fieldMappings后，就好了

**Comment by waryars** [comment]
我的为什么报这个错？ 


shade.core.com.google.common.util.concurrent.UncheckedExecutionException: com.dtstack.chunjun.throwable.ChunJunRuntimeException: error to get meta from [ROMA_LOGMINER.TEST_LOGMR]
	at shade.core.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at shade.core.com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at shade.core.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.getOrCreateFieldNamedPstmt(PreparedStmtProxy.java:154)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.convertToExternal(PreparedStmtProxy.java:125)
	at com.dtstack.chunjun.connector.jdbc.sink.JdbcOutputFormat.writeMultipleRecordsInternal(JdbcOutputFormat.java:161)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:496)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: error to get meta from [ROMA_LOGMINER.TEST_LOGMR]
	at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:192)
	at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:137)
	at com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.getColumnMeta(DynamicPreparedStmt.java:176)
	at com.dtstack.chunjun.connector.jdbc.sink.DynamicPreparedStmt.buildStmt(DynamicPreparedStmt.java:81)
	at com.dtstack.chunjun.connector.jdbc.sink.PreparedStmtProxy.lambda$getOrCreateFieldNamedPstmt$0(PreparedStmtProxy.java:158)
	at shade.core.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at shade.core.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at shade.core.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at shade.core.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at shade.core.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 14 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'roma_logminer.test_logmr' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:174)
	... 23 more
2023-10-12 16:07:28,814 - 95899 ERROR [timer-data-write-thread-pool-1-thread-1] com.dtstack.chunjun.sink.format.BaseRichOutputFormat:Writing records failed. com.dtstack.chunjun.throwable.NoRestartException: The dirty consumer shutdown, due to the consumed count exceed the max-consumed [0]
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.addConsumed(DirtyDataCollector.java:105)
	at com.dtstack.chunjun.dirty.consumer.DirtyDataCollector.offer(DirtyDataCollector.java:79)
	at com.dtstack.chunjun.dirty.manager.DirtyManager.collect(DirtyManager.java:140)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:482)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$writeRecordInternal$1(BaseRichOutputFormat.java:500)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:500)
	at com.dtstack.chunjun.sink.format.BaseRichOutputFormat.lambda$initTimingSubmitTask$0(BaseRichOutputFormat.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
