### ISSUE TITLE
SQL mode binlog->kafka

### ISSUE THREAD

**Issue by IsisPolei** [DTStack/chunjun#989]
使用SQL执行binlog->kafka时，实际输出到kafka的消息与guide里展示的不同。并没有before_,after_等字段。
CREATE TABLE binlog_test (
    user_id int,
    platform varchar
) WITH (
      'connector' = 'binlog-x'
      ,'username' = 'test'
      ,'password' = ''
      ,'cat' = 'insert,delete,update'
      ,'url' = 'jdbc:mysql://localhost:3306/test?useSSL=false'
      ,'host' = '10.136.11.10'
      ,'port' = '3306'
--   ,'journal-name' = 'mysql-bin.000001'
      ,'table' = 'test.test'
      ,'timestamp-format.standard' = 'SQL'
      );

CREATE TABLE kafka_test
(
    user_id int,
    platform varchar,
    PRIMARY KEY (user_id) NOT ENFORCED
) WITH (
       'connector' = 'upsert-kafka-x'
      ,'topic' = 'topic'
      ,'properties.bootstrap.servers' = 'localhost:9092'
      ,'properties.group.id' = 'flinkSQLTest'
      ,'key.format' = 'json'
      ,'value.format' = 'json'
      ,'value.fields-include' = 'ALL'
      );

INSERT INTO kafka_test
SELECT *
from binlog_test;

![image](https://user-images.githubusercontent.com/41672192/174984340-32f3002a-cdb0-438f-8773-b52de000bddc.png)

实际kafka中的消息：
![image](https://user-images.githubusercontent.com/41672192/174984445-96f37e0d-18a8-4702-bb0a-5132d9b3d2eb.png)
使用json模式输出符合预期：
![image](https://user-images.githubusercontent.com/41672192/174985617-cfbd3737-a2a8-4775-b07c-74d6a22d50f3.png)

**Comment by J1aHe** [comment]
你好，用你的这个会报错，能不能麻烦看看哪里有问题
```sql
CREATE TABLE source
(
    jid  int,
    jname varchar,
    jdouble double
) WITH (
      'connector' = 'binlog-x'
      ,'username' = 'root'
      ,'password' = '123123123'
      ,'cat' = 'insert,delete,update'
      ,'url' = 'jdbc:mysql://localhost:3333/ddddb'
      ,'host' = ''
      ,'port' = '3333'
-- ,'journal-name' = 'mysql-bin.000001'
      ,'table' = 'testest'
      ,'timestamp-format.standard' = 'SQL'
      );

CREATE TABLE sink
(
    ijd  int,
    namej varchar,
    before_jdouble double
) WITH (
      'connector' = 'kafka-x'
      ,'topic' = 'topic'
      ,'properties.bootstrap.servers' = 'localhost:3333'
      ,'value.format' = 'json'
      );

INSERT INTO sink
SELECT *
from source;
```

这个是报错
```Exception
Exception in thread "main" com.dtstack.chunjun.throwable.ChunJunRuntimeException: org.apache.flink.table.api.TableException: Table sink 'default_catalog.default_database.sink' doesn't support consuming update and delete changes which is produced by node TableSourceScan(table=[[default_catalog, default_database, source]], fields=[jid, jname, jdouble])
	at com.dtstack.chunjun.Main.exeSqlJob(Main.java:160)
	at com.dtstack.chunjun.Main.main(Main.java:119)
	at com.dtstack.chunjun.local.test.LocalTest.main(LocalTest.java:173)
Caused by: org.apache.flink.table.api.TableException: Table sink 'default_catalog.default_database.sink' doesn't support consuming update and delete changes which is produced by node TableSourceScan(table=[[default_catalog, default_database, source]], fields=[jid, jname, jdouble])
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram$SatisfyModifyKindSetTraitVisitor.createNewNode(FlinkChangelogModeInferenceProgram.scala:384)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram$SatisfyModifyKindSetTraitVisitor.visit(FlinkChangelogModeInferenceProgram.scala:302)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram$SatisfyModifyKindSetTraitVisitor.visitChild(FlinkChangelogModeInferenceProgram.scala:341)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram$SatisfyModifyKindSetTraitVisitor.$anonfun$visitChildren$1(FlinkChangelogModeInferenceProgram.scala:330)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram$SatisfyModifyKindSetTraitVisitor.$anonfun$visitChildren$1$adapted(FlinkChangelogModeInferenceProgram.scala:329)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.immutable.Range.foreach(Range.scala:155)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram$SatisfyModifyKindSetTraitVisitor.visitChildren(FlinkChangelogModeInferenceProgram.scala:329)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram$SatisfyModifyKindSetTraitVisitor.visit(FlinkChangelogModeInferenceProgram.scala:125)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram.optimize(FlinkChangelogModeInferenceProgram.scala:55)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChangelogModeInferenceProgram.optimize(FlinkChangelogModeInferenceProgram.scala:39)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkGroupProgram.$anonfun$optimize$2(FlinkGroupProgram.scala:63)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:156)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:154)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkGroupProgram.$anonfun$optimize$1(FlinkGroupProgram.scala:60)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkGroupProgram.$anonfun$optimize$1$adapted(FlinkGroupProgram.scala:55)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:156)
	at scala.collection.immutable.Range.foreach(Range.scala:155)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:154)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkGroupProgram.optimize(FlinkGroupProgram.scala:55)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram.$anonfun$optimize$1(FlinkChainedProgram.scala:62)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:156)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:154)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram.optimize(FlinkChainedProgram.scala:58)
	at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.optimizeTree(StreamCommonSubGraphBasedOptimizer.scala:163)
	at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.doOptimize(StreamCommonSubGraphBasedOptimizer.scala:83)
	at org.apache.flink.table.planner.plan.optimize.CommonSubGraphBasedOptimizer.optimize(CommonSubGraphBasedOptimizer.scala:77)
	at org.apache.flink.table.planner.delegation.PlannerBase.optimize(PlannerBase.scala:287)
	at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:160)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1329)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:676)
	at org.apache.flink.table.api.internal.StatementSetImpl.execute(StatementSetImpl.java:98)
	at com.dtstack.chunjun.Main.exeSqlJob(Main.java:152)
	... 2 more
```
